
-- ENTITIES
INSERT INTO tellos.tellos_entity ("label", total_employees, creation_date, linkedin, color_gradiant_left, color_gradiant_right, color_header, color_sticker, description, active, created_at, updated_at, deleted_at, created_by, updated_by, logo_id, organigramme_id, "type", membership_number, identifier_number) VALUES('TELLOS', null, null, null, '#004578', '#002F5B', '#00508B', '#005497', '', true, now(), now(), null, null, null, null, null, 'GROUPE TELLOS', null, '0');
INSERT INTO tellos.tellos_entity ("label", total_employees, creation_date, linkedin, color_gradiant_left, color_gradiant_right, color_header, color_sticker, description, active, created_at, updated_at, deleted_at, created_by, updated_by, logo_id, organigramme_id, "type", membership_number, identifier_number) VALUES('SOGECA', null, null, null, '#EEA413', '#EE6213', '#EFAE14', '#EF8A14', '', true, now(), now(), null, null, null, null, null, 'CIBTP', null, '1');
INSERT INTO tellos.tellos_entity ("label", total_employees, creation_date, linkedin, color_gradiant_left, color_gradiant_right, color_header, color_sticker, description, active, created_at, updated_at, deleted_at, created_by, updated_by, logo_id, organigramme_id, "type", membership_number, identifier_number) VALUES('SOGECA THERM', null, null, null, '#007833', '#165b00', '#009758', '#009758', '', true, now(), now(), null, null, null, null, null, 'CIBTP', null, '9');
INSERT INTO tellos.tellos_entity ("label", total_employees, creation_date, linkedin, color_gradiant_left, color_gradiant_right, color_header, color_sticker, description, active, created_at, updated_at, deleted_at, created_by, updated_by, logo_id, organigramme_id, "type", membership_number, identifier_number) VALUES('SMTPF', null, null, null, '#a13586', '#a1037a', '#a14d8c', '#a14d8c', '', true, now(), now(), null, null, null, null, null, 'CIBTP', null, '4');
INSERT INTO tellos.tellos_entity ("label", total_employees, creation_date, linkedin, color_gradiant_left, color_gradiant_right, color_header, color_sticker, description, active, created_at, updated_at, deleted_at, created_by, updated_by, logo_id, organigramme_id, "type", membership_number, identifier_number) VALUES('TELLOS IMMOBILIER', null, null, null, '#465257', '#384348', '#626c70', '#626c70', '', true, now(), now(), null, null, null, null, null, 'GROUPE TELLOS', null, '2');
INSERT INTO tellos.tellos_entity ("label", total_employees, creation_date, linkedin, color_gradiant_left, color_gradiant_right, color_header, color_sticker, description, active, created_at, updated_at, deleted_at, created_by, updated_by, logo_id, organigramme_id, "type", membership_number, identifier_number) VALUES('SABLIERE', null, null, null, '#AEB703', '#AEB703', '#777703', '#777703', '', true, now(), now(), null, null, null, null, null, 'GROUPE TELLOS', null, '6');
INSERT INTO tellos.tellos_entity ("label", total_employees, creation_date, linkedin, color_gradiant_left, color_gradiant_right, color_header, color_sticker, description, active, created_at, updated_at, deleted_at, created_by, updated_by, logo_id, organigramme_id, "type", membership_number, identifier_number) VALUES('CGR', null, null, null, '#fa8202', '#fa7602', '#f78c19', '#f78c19', '', true, now(), now(), null, null, null, null, null, 'CIBTP', null, '5');
INSERT INTO tellos.tellos_entity ("label", total_employees, creation_date, linkedin, color_gradiant_left, color_gradiant_right, color_header, color_sticker, description, active, created_at, updated_at, deleted_at, created_by, updated_by, logo_id, organigramme_id, "type", membership_number, identifier_number) VALUES('TDR', null, null, null, '#ed5ab8', '#eb2da6', '#f279c6', '#f279c6', '', true, now(), now(), null, null, null, null, null, 'GROUPE TELLOS', null, '3');

-- WORK UNIT
INSERT INTO tellos_work_entity (title, active, created_at, updated_at, deleted_at, created_by, updated_by, division_factor) VALUES('PNX', true, now(), now(), '', '', '', 0);
INSERT INTO tellos_work_entity (title, active, created_at, updated_at, deleted_at, created_by, updated_by, division_factor) VALUES('BTE', true, now(), now(), '', '', '', 0);
INSERT INTO tellos_work_entity (title, active, created_at, updated_at, deleted_at, created_by, updated_by, division_factor) VALUES('CX', true, now(), now(), '', '', '', 0);
INSERT INTO tellos_work_entity (title, active, created_at, updated_at, deleted_at, created_by, updated_by, division_factor) VALUES('%', true, now(), now(), '', '', '', 100);
INSERT INTO tellos_work_entity (title, active, created_at, updated_at, deleted_at, created_by, updated_by, division_factor) VALUES('% KG', true, now(), now(), '', '', '', 100);
INSERT INTO tellos_work_entity (title, active, created_at, updated_at, deleted_at, created_by, updated_by, division_factor) VALUES('% O', true, now(), now(), '', '', '', 1000);
INSERT INTO tellos_work_entity (title, active, created_at, updated_at, deleted_at, created_by, updated_by, division_factor) VALUES('% ML', true, now(), now(), '', '', '', 100);
INSERT INTO tellos_work_entity (title, active, created_at, updated_at, deleted_at, created_by, updated_by, division_factor) VALUES('HRE', true, now(), now(), '', '', '', 0);
INSERT INTO tellos_work_entity (title, active, created_at, updated_at, deleted_at, created_by, updated_by, division_factor) VALUES('KG', true, now(), now(), '', '', '', 0);
INSERT INTO tellos_work_entity (title, active, created_at, updated_at, deleted_at, created_by, updated_by, division_factor) VALUES('JR', true, now(), now(), '', '', '', 0);
INSERT INTO tellos_work_entity (title, active, created_at, updated_at, deleted_at, created_by, updated_by, division_factor) VALUES('KM', true, now(), now(), '', '', '', 0);
INSERT INTO tellos_work_entity (title, active, created_at, updated_at, deleted_at, created_by, updated_by, division_factor) VALUES('L', true, now(), now(), '', '', '', 0);
INSERT INTO tellos_work_entity (title, active, created_at, updated_at, deleted_at, created_by, updated_by, division_factor) VALUES('ML', true, now(), now(), '', '', '', 0);
INSERT INTO tellos_work_entity (title, active, created_at, updated_at, deleted_at, created_by, updated_by, division_factor) VALUES('M2', true, now(), now(), '', '', '', 0);
INSERT INTO tellos_work_entity (title, active, created_at, updated_at, deleted_at, created_by, updated_by, division_factor) VALUES('M3', true, now(), now(), '', '', '', 0);
INSERT INTO tellos_work_entity (title, active, created_at, updated_at, deleted_at, created_by, updated_by, division_factor) VALUES('PRE', true, now(), now(), '', '', '', 0);
INSERT INTO tellos_work_entity (title, active, created_at, updated_at, deleted_at, created_by, updated_by, division_factor) VALUES('RLX', true, now(), now(), '', '', '', 0);
INSERT INTO tellos_work_entity (title, active, created_at, updated_at, deleted_at, created_by, updated_by, division_factor) VALUES('SAC', true, now(), now(), '', '', '', 0);
INSERT INTO tellos_work_entity (title, active, created_at, updated_at, deleted_at, created_by, updated_by, division_factor) VALUES('Tonnes', true, now(), now(), '', '', '', 0);
INSERT INTO tellos_work_entity (title, active, created_at, updated_at, deleted_at, created_by, updated_by, division_factor) VALUES('Unité', true, now(), now(), '', '', '', 0);
INSERT INTO tellos_work_entity (title, active, created_at, updated_at, deleted_at, created_by, updated_by, division_factor) VALUES('M', true, now(), now(), '', '', '', 0);
INSERT INTO tellos_work_entity (title, active, created_at, updated_at, deleted_at, created_by, updated_by, division_factor) VALUES('Forfait', true, now(), now(), '', '', '', 0);


