import { MigrationInterface, QueryRunner } from 'typeorm';
import { TransactionnalMigration } from '../../libs/databases/decorators/classes/TransactionnalMigration';

@TransactionnalMigration()
export class InitDatabase1683817807405 implements MigrationInterface {
  name = 'InitDatabase1683817807405';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "tellos_upload" ("id" SERIAL NOT NULL, "original_name" character varying(255) NOT NULL, "name" character varying(255) NOT NULL, "directory" character varying(255) NOT NULL, "directories_names" json, "extension" character varying(255) NOT NULL, "type" character varying(255) NOT NULL, "title" character varying(255), "description" character varying(255), "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), CONSTRAINT "UQ_b67f2f1b40675e0922478a10af2" UNIQUE ("name", "deleted_at"), CONSTRAINT "PK_c9b98c098b04efb734719659544" PRIMARY KEY ("id")); COMMENT ON COLUMN "tellos_upload"."title" IS 'Translation column title'; COMMENT ON COLUMN "tellos_upload"."description" IS 'Translation column description'`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_entity" ("id" SERIAL NOT NULL, "label" character varying, "total_employees" integer, "creation_date" date, "linkedin" character varying(255), "color_gradiant_left" character varying, "color_gradiant_right" character varying, "color_header" character varying, "color_sticker" character varying, "description" text, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), "logo_id" integer, "organigramme_id" integer, CONSTRAINT "UQ_a9d6270dccb9006c9af1a156766" UNIQUE ("label", "deleted_at"), CONSTRAINT "PK_5b06466ce253748955260cdbae3" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_qualification_name" ("id" SERIAL NOT NULL, "name" character varying, "validity" integer, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), CONSTRAINT "UQ_71b7e8dba5b1acdc28728202c1b" UNIQUE ("name", "deleted_at"), CONSTRAINT "PK_0ea2909bccfb2b9f669862dd7e0" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_qualification_type" ("id" SERIAL NOT NULL, "name" character varying, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), CONSTRAINT "UQ_104037b16e61884808c57b800b2" UNIQUE ("name", "deleted_at"), CONSTRAINT "PK_9be9da28c7984d6fc0e68ca74b3" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_qualification" ("id" SERIAL NOT NULL, "number" character varying, "delivery" date, "deadline" date, "validity" integer, "comment" text, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), "entity_id" integer, "department_id" integer, "employee_id" integer, "type_id" integer, "name_id" integer, "document_id" integer, CONSTRAINT "UQ_a16ea3a7d3cd0babbb12de9bf8c" UNIQUE ("number", "deleted_at"), CONSTRAINT "PK_78215963167b5d4546559f7ddd4" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_leave_type_enum" AS ENUM('PAID_LEAVE', 'UNPAID_ABSENCE', 'RECOVERY', 'SICK_LEAVE', 'STOP_WORK_ACCIDENT', 'ANNOUNCEMENT_OF_A_DISABILITY_IN_A_CHILD', 'BEREAVEMENT_LEAVE_FOR_A_CHILD', 'SICK_CHILD', 'WEDDING', 'CHILD_WEDDIND', 'BIRTH_ADOPTION', 'ADOPTION', 'In_LAWS_FUNERAL', 'SPOUSE_FUNERAL', 'CHILD_FUNERAL', 'BROTHER_FUNERAL', 'SISTER_FUNERAL', 'PARENTS_FUNERAL')`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_leave_entity_enum" AS ENUM('TELLOS', 'SOGECA', 'SOGECA_THERM', 'SMTPF', 'SMARTFIB', 'SABLIERE', 'CGR', 'ABILCITY')`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_leave_contract_enum" AS ENUM('CDI', 'CDD', 'Interim', 'Contrat pro', 'Stage', 'Alternant', 'Renew')`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_leave_decision_enum" AS ENUM('REQUESTED', 'ACCEPTED', 'DENIED')`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_leave_gender_enum" AS ENUM('MALE', 'FEMALE')`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_leave" ("id" SERIAL NOT NULL, "request_date" TIMESTAMP NOT NULL DEFAULT now(), "type" "tellos"."tellos_leave_type_enum", "start_date" date NOT NULL, "end_date" date NOT NULL, "entity" "tellos"."tellos_leave_entity_enum", "contract" "tellos"."tellos_leave_contract_enum", "decision" "tellos"."tellos_leave_decision_enum" NOT NULL, "gender" "tellos"."tellos_leave_gender_enum", "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), "employee_id" integer, "service_id" integer, "decision_maker_id" integer, CONSTRAINT "PK_976e0f456110b7d6c4922a37914" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_department" ("id" SERIAL NOT NULL, "name" character varying, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), CONSTRAINT "UQ_dad9b174e16c40dd6cdaf539310" UNIQUE ("name", "deleted_at"), CONSTRAINT "PK_4af88af4286a2192bd9364594b0" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_token_name_enum" AS ENUM('TOKEN_RESET_PASSWORD')`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_token" ("id" SERIAL NOT NULL, "name" "tellos"."tellos_token_name_enum" NOT NULL, "value" character varying(255) NOT NULL, "expire_at" TIMESTAMP NOT NULL, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c01b3279aa25feab67d31112a5f" UNIQUE ("value"), CONSTRAINT "PK_cf7aab3182c14ee63e4754c0348" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_permission_name_enum" AS ENUM('PERMISSION_DASHBOARD_DASHBOARD_READ', 'PERMISSION_DASHBOARD_DASHBOARD_CREATE', 'PERMISSION_DASHBOARD_DASHBOARD_UPDATE', 'PERMISSION_DASHBOARD_DASHBOARD_SOFT_DELETE', 'PERMISSION_DASHBOARD_ONBOARDING_READ', 'PERMISSION_DASHBOARD_ONBOARDING_CREATE', 'PERMISSION_DASHBOARD_ONBOARDING_UPDATE', 'PERMISSION_DASHBOARD_ONBOARDING_SOFT_DELETE', 'PERMISSION_DASHBOARD_PENDING_APPROVALS_READ', 'PERMISSION_DASHBOARD_PENDING_APPROVALS_CREATE', 'PERMISSION_DASHBOARD_PENDING_APPROVALS_UPDATE', 'PERMISSION_DASHBOARD_PENDING_APPROVALS_SOFT_DELETE', 'PERMISSION_DASHBOARD_ADDRESS_LIST_READ', 'PERMISSION_DASHBOARD_ADDRESS_LIST_CREATE', 'PERMISSION_DASHBOARD_ADDRESS_LIST_UPDATE', 'PERMISSION_DASHBOARD_ADDRESS_LIST_SOFT_DELETE', 'PERMISSION_DASHBOARD_ORGANIZATION_CHART_READ', 'PERMISSION_DASHBOARD_ORGANIZATION_CHART_CREATE', 'PERMISSION_DASHBOARD_ORGANIZATION_CHART_UPDATE', 'PERMISSION_DASHBOARD_ORGANIZATION_CHART_SOFT_DELETE', 'PERMISSION_DASHBOARD_REPORT_READ', 'PERMISSION_DASHBOARD_REPORT_CREATE', 'PERMISSION_DASHBOARD_REPORT_UPDATE', 'PERMISSION_DASHBOARD_REPORT_SOFT_DELETE', 'PERMISSION_DASHBOARD_STATISTICS_READ', 'PERMISSION_DASHBOARD_STATISTICS_CREATE', 'PERMISSION_DASHBOARD_STATISTICS_UPDATE', 'PERMISSION_DASHBOARD_STATISTICS_SOFT_DELETE', 'PERMISSION_DASHBOARD_SITE_PLANNING_READ', 'PERMISSION_DASHBOARD_SITE_PLANNING_CREATE', 'PERMISSION_DASHBOARD_SITE_PLANNING_UPDATE', 'PERMISSION_DASHBOARD_SITE_PLANNING_SOFT_DELETE', 'PERMISSION_DASHBOARD_TEAM_PLANNING_READ', 'PERMISSION_DASHBOARD_TEAM_PLANNING_CREATE', 'PERMISSION_DASHBOARD_TEAM_PLANNING_UPDATE', 'PERMISSION_DASHBOARD_TEAM_PLANNING_SOFT_DELETE', 'PERMISSION_DASHBOARD_HOLIDAY_PLANNING_READ', 'PERMISSION_DASHBOARD_HOLIDAY_PLANNING_CREATE', 'PERMISSION_DASHBOARD_HOLIDAY_PLANNING_UPDATE', 'PERMISSION_DASHBOARD_HOLIDAY_PLANNING_SOFT_DELETE', 'PERMISSION_DASHBOARD_FLEET_PLANNING_READ', 'PERMISSION_DASHBOARD_FLEET_PLANNING_CREATE', 'PERMISSION_DASHBOARD_FLEET_PLANNING_UPDATE', 'PERMISSION_DASHBOARD_FLEET_PLANNING_SOFT_DELETE', 'PERMISSION_DASHBOARD_TRAVEL_PLANNING_READ', 'PERMISSION_DASHBOARD_TRAVEL_PLANNING_CREATE', 'PERMISSION_DASHBOARD_TRAVEL_PLANNING_UPDATE', 'PERMISSION_DASHBOARD_TRAVEL_PLANNING_SOFT_DELETE', 'PERMISSION_DASHBOARD_CA_TIME_STATEMENT_READ', 'PERMISSION_DASHBOARD_CA_TIME_STATEMENT_CREATE', 'PERMISSION_DASHBOARD_CA_TIME_STATEMENT_UPDATE', 'PERMISSION_DASHBOARD_CA_TIME_STATEMENT_SOFT_DELETE', 'PERMISSION_DASHBOARD_NEWS_READ', 'PERMISSION_DASHBOARD_NEWS_CREATE', 'PERMISSION_DASHBOARD_NEWS_UPDATE', 'PERMISSION_DASHBOARD_NEWS_SOFT_DELETE', 'PERMISSION_DASHBOARD_CATERER_READ', 'PERMISSION_DASHBOARD_CATERER_CREATE', 'PERMISSION_DASHBOARD_CATERER_UPDATE', 'PERMISSION_DASHBOARD_CATERER_SOFT_DELETE', 'PERMISSION_DASHBOARD_BONUS_READ', 'PERMISSION_DASHBOARD_BONUS_CREATE', 'PERMISSION_DASHBOARD_BONUS_UPDATE', 'PERMISSION_DASHBOARD_BONUS_SOFT_DELETE', 'PERMISSION_SITE_DASHBOARD_READ', 'PERMISSION_SITE_DASHBOARD_CREATE', 'PERMISSION_SITE_DASHBOARD_UPDATE', 'PERMISSION_SITE_DASHBOARD_SOFT_DELETE', 'PERMISSION_SITE_DIRECTORY_OF_PROJECTS_READ', 'PERMISSION_SITE_DIRECTORY_OF_PROJECTS_CREATE', 'PERMISSION_SITE_DIRECTORY_OF_PROJECTS_UPDATE', 'PERMISSION_SITE_DIRECTORY_OF_PROJECTS_SOFT_DELETE', 'PERMISSION_SITE_DIRECTORY_OF_WORK_SITES_READ', 'PERMISSION_SITE_DIRECTORY_OF_WORK_SITES_CREATE', 'PERMISSION_SITE_DIRECTORY_OF_WORK_SITES_UPDATE', 'PERMISSION_SITE_DIRECTORY_OF_WORK_SITES_SOFT_DELETE', 'PERMISSION_SITE_PLANNING_OF_THE_SITES_READ', 'PERMISSION_SITE_PLANNING_OF_THE_SITES_CREATE', 'PERMISSION_SITE_PLANNING_OF_THE_SITES_UPDATE', 'PERMISSION_SITE_PLANNING_OF_THE_SITES_SOFT_DELETE', 'PERMISSION_SITE_MAP_OF_WORK_SITES_READ', 'PERMISSION_SITE_MAP_OF_WORK_SITES_CREATE', 'PERMISSION_SITE_MAP_OF_WORK_SITES_UPDATE', 'PERMISSION_SITE_MAP_OF_WORK_SITES_SOFT_DELETE', 'PERMISSION_SITE_TEAM_PROGRAM_READ', 'PERMISSION_SITE_TEAM_PROGRAM_CREATE', 'PERMISSION_SITE_TEAM_PROGRAM_UPDATE', 'PERMISSION_SITE_TEAM_PROGRAM_SOFT_DELETE', 'PERMISSION_SITE_TEMPORARY_STAFFING_NEEDS_READ', 'PERMISSION_SITE_TEMPORARY_STAFFING_NEEDS_CREATE', 'PERMISSION_SITE_TEMPORARY_STAFFING_NEEDS_UPDATE', 'PERMISSION_SITE_TEMPORARY_STAFFING_NEEDS_SOFT_DELETE', 'PERMISSION_SITE_REVENUE_REPORTING_READ', 'PERMISSION_SITE_REVENUE_REPORTING_CREATE', 'PERMISSION_SITE_REVENUE_REPORTING_UPDATE', 'PERMISSION_SITE_REVENUE_REPORTING_SOFT_DELETE', 'PERMISSION_SITE_PROCUREMENT_READ', 'PERMISSION_SITE_PROCUREMENT_CREATE', 'PERMISSION_SITE_PROCUREMENT_UPDATE', 'PERMISSION_SITE_PROCUREMENT_SOFT_DELETE', 'PERMISSION_SITE_RATES_MO_READ', 'PERMISSION_SITE_RATES_MO_CREATE', 'PERMISSION_SITE_RATES_MO_UPDATE', 'PERMISSION_SITE_RATES_MO_SOFT_DELETE', 'PERMISSION_SITE_CONSTRUCTION_SITE_CLAIMS_READ', 'PERMISSION_SITE_CONSTRUCTION_SITE_CLAIMS_CREATE', 'PERMISSION_SITE_CONSTRUCTION_SITE_CLAIMS_UPDATE', 'PERMISSION_SITE_CONSTRUCTION_SITE_CLAIMS_SOFT_DELETE', 'PERMISSION_SITE_TEAM_READ', 'PERMISSION_SITE_TEAM_CREATE', 'PERMISSION_SITE_TEAM_UPDATE', 'PERMISSION_SITE_TEAM_SOFT_DELETE', 'PERMISSION_SITE_MATERIAL_READ', 'PERMISSION_SITE_MATERIAL_CREATE', 'PERMISSION_SITE_MATERIAL_UPDATE', 'PERMISSION_SITE_MATERIAL_SOFT_DELETE', 'PERMISSION_SITE_MATERIAL_PLANNING_READ', 'PERMISSION_SITE_MATERIAL_PLANNING_CREATE', 'PERMISSION_SITE_MATERIAL_PLANNING_UPDATE', 'PERMISSION_SITE_MATERIAL_PLANNING_SOFT_DELETE', 'PERMISSION_SITE_FLEET_READ', 'PERMISSION_SITE_FLEET_CREATE', 'PERMISSION_SITE_FLEET_UPDATE', 'PERMISSION_SITE_FLEET_SOFT_DELETE', 'PERMISSION_SITE_FLEET_PLANNING_READ', 'PERMISSION_SITE_FLEET_PLANNING_CREATE', 'PERMISSION_SITE_FLEET_PLANNING_UPDATE', 'PERMISSION_SITE_FLEET_PLANNING_SOFT_DELETE', 'PERMISSION_SITE_CONTRACT_REVIEW_READ', 'PERMISSION_SITE_CONTRACT_REVIEW_CREATE', 'PERMISSION_SITE_CONTRACT_REVIEW_UPDATE', 'PERMISSION_SITE_CONTRACT_REVIEW_SOFT_DELETE', 'PERMISSION_MANAGEMENT_DASHBOARD_READ', 'PERMISSION_MANAGEMENT_DASHBOARD_CREATE', 'PERMISSION_MANAGEMENT_DASHBOARD_UPDATE', 'PERMISSION_MANAGEMENT_DASHBOARD_SOFT_DELETE', 'PERMISSION_RH_DASHBOARD_READ', 'PERMISSION_RH_DASHBOARD_CREATE', 'PERMISSION_RH_DASHBOARD_UPDATE', 'PERMISSION_RH_DASHBOARD_SOFT_DELETE', 'PERMISSION_RH_EMPLOYEE_DIRECTORY_READ', 'PERMISSION_RH_EMPLOYEE_DIRECTORY_CREATE', 'PERMISSION_RH_EMPLOYEE_DIRECTORY_UPDATE', 'PERMISSION_RH_EMPLOYEE_DIRECTORY_SOFT_DELETE', 'PERMISSION_RH_DIRECTORY_OF_CANDIDATES_READ', 'PERMISSION_RH_DIRECTORY_OF_CANDIDATES_CREATE', 'PERMISSION_RH_DIRECTORY_OF_CANDIDATES_UPDATE', 'PERMISSION_RH_DIRECTORY_OF_CANDIDATES_SOFT_DELETE', 'PERMISSION_RH_CV_TECH_READ', 'PERMISSION_RH_CV_TECH_CREATE', 'PERMISSION_RH_CV_TECH_UPDATE', 'PERMISSION_RH_CV_TECH_SOFT_DELETE', 'PERMISSION_RH_HOLIDAY_OR_ABSENCE_READ', 'PERMISSION_RH_HOLIDAY_OR_ABSENCE_CREATE', 'PERMISSION_RH_HOLIDAY_OR_ABSENCE_UPDATE', 'PERMISSION_RH_HOLIDAY_OR_ABSENCE_SOFT_DELETE', 'PERMISSION_RH_TIME_READ', 'PERMISSION_RH_TIME_CREATE', 'PERMISSION_RH_TIME_UPDATE', 'PERMISSION_RH_TIME_SOFT_DELETE', 'PERMISSION_RH_PAYMENT_READ', 'PERMISSION_RH_PAYMENT_CREATE', 'PERMISSION_RH_PAYMENT_UPDATE', 'PERMISSION_RH_PAYMENT_SOFT_DELETE', 'PERMISSION_RH_FORMATION_READ', 'PERMISSION_RH_FORMATION_CREATE', 'PERMISSION_RH_FORMATION_UPDATE', 'PERMISSION_RH_FORMATION_SOFT_DELETE', 'PERMISSION_RH_QUALIFICATION_READ', 'PERMISSION_RH_QUALIFICATION_CREATE', 'PERMISSION_RH_QUALIFICATION_UPDATE', 'PERMISSION_RH_QUALIFICATION_SOFT_DELETE', 'PERMISSION_RH_ONBOARDING_READ', 'PERMISSION_RH_ONBOARDING_CREATE', 'PERMISSION_RH_ONBOARDING_UPDATE', 'PERMISSION_RH_ONBOARDING_SOFT_DELETE', 'PERMISSION_RH_SURVEY_READ', 'PERMISSION_RH_SURVEY_CREATE', 'PERMISSION_RH_SURVEY_UPDATE', 'PERMISSION_RH_SURVEY_SOFT_DELETE', 'PERMISSION_RH_JOB_DESCRIPTION_READ', 'PERMISSION_RH_JOB_DESCRIPTION_CREATE', 'PERMISSION_RH_JOB_DESCRIPTION_UPDATE', 'PERMISSION_RH_JOB_DESCRIPTION_SOFT_DELETE', 'PERMISSION_RH_MEDICAL_VISITS_READ', 'PERMISSION_RH_MEDICAL_VISITS_CREATE', 'PERMISSION_RH_MEDICAL_VISITS_UPDATE', 'PERMISSION_RH_MEDICAL_VISITS_SOFT_DELETE', 'PERMISSION_RH_INTERVIEWS_READ', 'PERMISSION_RH_INTERVIEWS_CREATE', 'PERMISSION_RH_INTERVIEWS_UPDATE', 'PERMISSION_RH_INTERVIEWS_SOFT_DELETE', 'PERMISSION_RH_ATTENDANCE_LOG_READ', 'PERMISSION_RH_ATTENDANCE_LOG_CREATE', 'PERMISSION_RH_ATTENDANCE_LOG_UPDATE', 'PERMISSION_RH_ATTENDANCE_LOG_SOFT_DELETE', 'PERMISSION_RH_BIG_MOVE_READ', 'PERMISSION_RH_BIG_MOVE_CREATE', 'PERMISSION_RH_BIG_MOVE_UPDATE', 'PERMISSION_RH_BIG_MOVE_SOFT_DELETE', 'PERMISSION_PURCHASE_DASHBOARD_READ', 'PERMISSION_PURCHASE_DASHBOARD_CREATE', 'PERMISSION_PURCHASE_DASHBOARD_UPDATE', 'PERMISSION_PURCHASE_DASHBOARD_SOFT_DELETE', 'PERMISSION_PURCHASE_SUPPLIERS_READ', 'PERMISSION_PURCHASE_SUPPLIERS_CREATE', 'PERMISSION_PURCHASE_SUPPLIERS_UPDATE', 'PERMISSION_PURCHASE_SUPPLIERS_SOFT_DELETE', 'PERMISSION_PURCHASE_DIRECTORY_OF_ARTICLES_READ', 'PERMISSION_PURCHASE_DIRECTORY_OF_ARTICLES_CREATE', 'PERMISSION_PURCHASE_DIRECTORY_OF_ARTICLES_UPDATE', 'PERMISSION_PURCHASE_DIRECTORY_OF_ARTICLES_SOFT_DELETE', 'PERMISSION_PURCHASE_PURCHASE_REQUESTS_READ', 'PERMISSION_PURCHASE_PURCHASE_REQUESTS_CREATE', 'PERMISSION_PURCHASE_PURCHASE_REQUESTS_UPDATE', 'PERMISSION_PURCHASE_PURCHASE_REQUESTS_SOFT_DELETE', 'PERMISSION_PURCHASE_ORDERS_READ', 'PERMISSION_PURCHASE_ORDERS_CREATE', 'PERMISSION_PURCHASE_ORDERS_UPDATE', 'PERMISSION_PURCHASE_ORDERS_SOFT_DELETE', 'PERMISSION_PURCHASE_DELIVERY_NOTES_READ', 'PERMISSION_PURCHASE_DELIVERY_NOTES_CREATE', 'PERMISSION_PURCHASE_DELIVERY_NOTES_UPDATE', 'PERMISSION_PURCHASE_DELIVERY_NOTES_SOFT_DELETE', 'PERMISSION_PURCHASE_INVOICES_READ', 'PERMISSION_PURCHASE_INVOICES_CREATE', 'PERMISSION_PURCHASE_INVOICES_UPDATE', 'PERMISSION_PURCHASE_INVOICES_SOFT_DELETE', 'PERMISSION_PURCHASE_SUBCONTRACTING_WORK_READ', 'PERMISSION_PURCHASE_SUBCONTRACTING_WORK_CREATE', 'PERMISSION_PURCHASE_SUBCONTRACTING_WORK_UPDATE', 'PERMISSION_PURCHASE_SUBCONTRACTING_WORK_SOFT_DELETE', 'PERMISSION_PURCHASE_PUNCH_OUT_WORK_READ', 'PERMISSION_PURCHASE_PUNCH_OUT_WORK_CREATE', 'PERMISSION_PURCHASE_PUNCH_OUT_WORK_UPDATE', 'PERMISSION_PURCHASE_PUNCH_OUT_WORK_SOFT_DELETE', 'PERMISSION_PURCHASE_FOLLOW_UP_TABLES_READ', 'PERMISSION_PURCHASE_FOLLOW_UP_TABLES_CREATE', 'PERMISSION_PURCHASE_FOLLOW_UP_TABLES_UPDATE', 'PERMISSION_PURCHASE_FOLLOW_UP_TABLES_SOFT_DELETE', 'PERMISSION_PURCHASE_CATALOGS_READ', 'PERMISSION_PURCHASE_CATALOGS_CREATE', 'PERMISSION_PURCHASE_CATALOGS_UPDATE', 'PERMISSION_PURCHASE_CATALOGS_SOFT_DELETE', 'PERMISSION_BILLING_DASHBOARD_READ', 'PERMISSION_BILLING_DASHBOARD_CREATE', 'PERMISSION_BILLING_DASHBOARD_UPDATE', 'PERMISSION_BILLING_DASHBOARD_SOFT_DELETE', 'PERMISSION_BILLING_CUSTOMER_DIRECTORY_READ', 'PERMISSION_BILLING_CUSTOMER_DIRECTORY_CREATE', 'PERMISSION_BILLING_CUSTOMER_DIRECTORY_UPDATE', 'PERMISSION_BILLING_CUSTOMER_DIRECTORY_SOFT_DELETE', 'PERMISSION_BILLING_QUOTATION_OR_AO_READ', 'PERMISSION_BILLING_QUOTATION_OR_AO_CREATE', 'PERMISSION_BILLING_QUOTATION_OR_AO_UPDATE', 'PERMISSION_BILLING_QUOTATION_OR_AO_SOFT_DELETE', 'PERMISSION_BILLING_ATTACHMENTS_READ', 'PERMISSION_BILLING_ATTACHMENTS_CREATE', 'PERMISSION_BILLING_ATTACHMENTS_UPDATE', 'PERMISSION_BILLING_ATTACHMENTS_SOFT_DELETE', 'PERMISSION_BILLING_ORDERS_READ', 'PERMISSION_BILLING_ORDERS_CREATE', 'PERMISSION_BILLING_ORDERS_UPDATE', 'PERMISSION_BILLING_ORDERS_SOFT_DELETE', 'PERMISSION_BILLING_CUSTOMER_BILLING_READ', 'PERMISSION_BILLING_CUSTOMER_BILLING_CREATE', 'PERMISSION_BILLING_CUSTOMER_BILLING_UPDATE', 'PERMISSION_BILLING_CUSTOMER_BILLING_SOFT_DELETE', 'PERMISSION_BILLING_RECOVERY_OR_DUNNING_READ', 'PERMISSION_BILLING_RECOVERY_OR_DUNNING_CREATE', 'PERMISSION_BILLING_RECOVERY_OR_DUNNING_UPDATE', 'PERMISSION_BILLING_RECOVERY_OR_DUNNING_SOFT_DELETE', 'PERMISSION_BILLING_SUBCONTRACTOR_BILLING_READ', 'PERMISSION_BILLING_SUBCONTRACTOR_BILLING_CREATE', 'PERMISSION_BILLING_SUBCONTRACTOR_BILLING_UPDATE', 'PERMISSION_BILLING_SUBCONTRACTOR_BILLING_SOFT_DELETE', 'PERMISSION_BILLING_DIRECT_PAYMENT_TO_SUBCONTRACTORS_READ', 'PERMISSION_BILLING_DIRECT_PAYMENT_TO_SUBCONTRACTORS_CREATE', 'PERMISSION_BILLING_DIRECT_PAYMENT_TO_SUBCONTRACTORS_UPDATE', 'PERMISSION_BILLING_DIRECT_PAYMENT_TO_SUBCONTRACTORS_SOFT_DELETE', 'PERMISSION_BILLING_CO_CONTRACTOR_INVOICING_READ', 'PERMISSION_BILLING_CO_CONTRACTOR_INVOICING_CREATE', 'PERMISSION_BILLING_CO_CONTRACTOR_INVOICING_UPDATE', 'PERMISSION_BILLING_CO_CONTRACTOR_INVOICING_SOFT_DELETE', 'PERMISSION_BILLING_ACCOUNTING_READ', 'PERMISSION_BILLING_ACCOUNTING_CREATE', 'PERMISSION_BILLING_ACCOUNTING_UPDATE', 'PERMISSION_BILLING_ACCOUNTING_SOFT_DELETE', 'PERMISSION_BILLING_FOLLOW_UP_OF_HOLDBACKS_READ', 'PERMISSION_BILLING_FOLLOW_UP_OF_HOLDBACKS_CREATE', 'PERMISSION_BILLING_FOLLOW_UP_OF_HOLDBACKS_UPDATE', 'PERMISSION_BILLING_FOLLOW_UP_OF_HOLDBACKS_SOFT_DELETE', 'PERMISSION_BILLING_PROGRESS_REPORTS_READ', 'PERMISSION_BILLING_PROGRESS_REPORTS_CREATE', 'PERMISSION_BILLING_PROGRESS_REPORTS_UPDATE', 'PERMISSION_BILLING_PROGRESS_REPORTS_SOFT_DELETE', 'PERMISSION_BILLING_INVOICES_TRANSFERRED_TO_THE_BANK_READ', 'PERMISSION_BILLING_INVOICES_TRANSFERRED_TO_THE_BANK_CREATE', 'PERMISSION_BILLING_INVOICES_TRANSFERRED_TO_THE_BANK_UPDATE', 'PERMISSION_BILLING_INVOICES_TRANSFERRED_TO_THE_BANK_SOFT_DELETE', 'PERMISSION_MATERIAL_PARK_DASHBOARD_READ', 'PERMISSION_MATERIAL_PARK_DASHBOARD_CREATE', 'PERMISSION_MATERIAL_PARK_DASHBOARD_UPDATE', 'PERMISSION_MATERIAL_PARK_DASHBOARD_SOFT_DELETE', 'PERMISSION_MATERIAL_STORE_READ', 'PERMISSION_MATERIAL_STORE_CREATE', 'PERMISSION_MATERIAL_STORE_UPDATE', 'PERMISSION_MATERIAL_STORE_SOFT_DELETE', 'PERMISSION_MATERIAL_SUPPLIERS_READ', 'PERMISSION_MATERIAL_SUPPLIERS_CREATE', 'PERMISSION_MATERIAL_SUPPLIERS_UPDATE', 'PERMISSION_MATERIAL_SUPPLIERS_SOFT_DELETE', 'PERMISSION_MATERIAL_MATERIAL_READ', 'PERMISSION_MATERIAL_MATERIAL_CREATE', 'PERMISSION_MATERIAL_MATERIAL_UPDATE', 'PERMISSION_MATERIAL_MATERIAL_SOFT_DELETE', 'PERMISSION_MATERIAL_FLEET_READ', 'PERMISSION_MATERIAL_FLEET_CREATE', 'PERMISSION_MATERIAL_FLEET_UPDATE', 'PERMISSION_MATERIAL_FLEET_SOFT_DELETE', 'PERMISSION_MATERIAL_MACHINE_READ', 'PERMISSION_MATERIAL_MACHINE_CREATE', 'PERMISSION_MATERIAL_MACHINE_UPDATE', 'PERMISSION_MATERIAL_MACHINE_SOFT_DELETE', 'PERMISSION_MATERIAL_SMALL_EQUIPMENT_READ', 'PERMISSION_MATERIAL_SMALL_EQUIPMENT_CREATE', 'PERMISSION_MATERIAL_SMALL_EQUIPMENT_UPDATE', 'PERMISSION_MATERIAL_SMALL_EQUIPMENT_SOFT_DELETE', 'PERMISSION_MATERIAL_MATERIAL_PLANNING_READ', 'PERMISSION_MATERIAL_MATERIAL_PLANNING_CREATE', 'PERMISSION_MATERIAL_MATERIAL_PLANNING_UPDATE', 'PERMISSION_MATERIAL_MATERIAL_PLANNING_SOFT_DELETE', 'PERMISSION_MATERIAL_MAINTENANCE_READ', 'PERMISSION_MATERIAL_MAINTENANCE_CREATE', 'PERMISSION_MATERIAL_MAINTENANCE_UPDATE', 'PERMISSION_MATERIAL_MAINTENANCE_SOFT_DELETE', 'PERMISSION_MATERIAL_MECHANICAL_PLANNING_READ', 'PERMISSION_MATERIAL_MECHANICAL_PLANNING_CREATE', 'PERMISSION_MATERIAL_MECHANICAL_PLANNING_UPDATE', 'PERMISSION_MATERIAL_MECHANICAL_PLANNING_SOFT_DELETE', 'PERMISSION_MATERIAL_FUEL_READ', 'PERMISSION_MATERIAL_FUEL_CREATE', 'PERMISSION_MATERIAL_FUEL_UPDATE', 'PERMISSION_MATERIAL_FUEL_SOFT_DELETE', 'PERMISSION_MATERIAL_PROCUREMENT_READ', 'PERMISSION_MATERIAL_PROCUREMENT_CREATE', 'PERMISSION_MATERIAL_PROCUREMENT_UPDATE', 'PERMISSION_MATERIAL_PROCUREMENT_SOFT_DELETE', 'PERMISSION_MATERIAL_RENTAL_READ', 'PERMISSION_MATERIAL_RENTAL_CREATE', 'PERMISSION_MATERIAL_RENTAL_UPDATE', 'PERMISSION_MATERIAL_RENTAL_SOFT_DELETE', 'PERMISSION_MATERIAL_CLAIMS_READ', 'PERMISSION_MATERIAL_CLAIMS_CREATE', 'PERMISSION_MATERIAL_CLAIMS_UPDATE', 'PERMISSION_MATERIAL_CLAIMS_SOFT_DELETE', 'PERMISSION_MATERIAL_PENALTY_READ', 'PERMISSION_MATERIAL_PENALTY_CREATE', 'PERMISSION_MATERIAL_PENALTY_UPDATE', 'PERMISSION_MATERIAL_PENALTY_SOFT_DELETE', 'PERMISSION_MATERIAL_RE_BILLING_OF_THE_PARK_READ', 'PERMISSION_MATERIAL_RE_BILLING_OF_THE_PARK_CREATE', 'PERMISSION_MATERIAL_RE_BILLING_OF_THE_PARK_UPDATE', 'PERMISSION_MATERIAL_RE_BILLING_OF_THE_PARK_SOFT_DELETE', 'PERMISSION_MATERIAL_MATERIAL_RATE_READ', 'PERMISSION_MATERIAL_MATERIAL_RATE_CREATE', 'PERMISSION_MATERIAL_MATERIAL_RATE_UPDATE', 'PERMISSION_MATERIAL_MATERIAL_RATE_SOFT_DELETE', 'PERMISSION_QSE_DASHBOARD_READ', 'PERMISSION_QSE_DASHBOARD_CREATE', 'PERMISSION_QSE_DASHBOARD_UPDATE', 'PERMISSION_QSE_DASHBOARD_SOFT_DELETE', 'PERMISSION_QSE_AUDITS_READ', 'PERMISSION_QSE_AUDITS_CREATE', 'PERMISSION_QSE_AUDITS_UPDATE', 'PERMISSION_QSE_AUDITS_SOFT_DELETE', 'PERMISSION_QSE_INFORMATION_FEEDBACK_READ', 'PERMISSION_QSE_INFORMATION_FEEDBACK_CREATE', 'PERMISSION_QSE_INFORMATION_FEEDBACK_UPDATE', 'PERMISSION_QSE_INFORMATION_FEEDBACK_SOFT_DELETE', 'PERMISSION_QSE_CUSTOMER_SATISFACTION_READ', 'PERMISSION_QSE_CUSTOMER_SATISFACTION_CREATE', 'PERMISSION_QSE_CUSTOMER_SATISFACTION_UPDATE', 'PERMISSION_QSE_CUSTOMER_SATISFACTION_SOFT_DELETE', 'PERMISSION_QSE_REGULATORY_CONTROLS_READ', 'PERMISSION_QSE_REGULATORY_CONTROLS_CREATE', 'PERMISSION_QSE_REGULATORY_CONTROLS_UPDATE', 'PERMISSION_QSE_REGULATORY_CONTROLS_SOFT_DELETE', 'PERMISSION_QSE_RISK_ASSESSMENT_READ', 'PERMISSION_QSE_RISK_ASSESSMENT_CREATE', 'PERMISSION_QSE_RISK_ASSESSMENT_UPDATE', 'PERMISSION_QSE_RISK_ASSESSMENT_SOFT_DELETE', 'PERMISSION_QSE_SECURITY_SHIFT_READ', 'PERMISSION_QSE_SECURITY_SHIFT_CREATE', 'PERMISSION_QSE_SECURITY_SHIFT_UPDATE', 'PERMISSION_QSE_SECURITY_SHIFT_SOFT_DELETE', 'PERMISSION_QSE_LIFTING_READ', 'PERMISSION_QSE_LIFTING_CREATE', 'PERMISSION_QSE_LIFTING_UPDATE', 'PERMISSION_QSE_LIFTING_SOFT_DELETE', 'PERMISSION_QSE_HSE_READ', 'PERMISSION_QSE_HSE_CREATE', 'PERMISSION_QSE_HSE_UPDATE', 'PERMISSION_QSE_HSE_SOFT_DELETE', 'PERMISSION_QSE_ACCIDENT_AT_WORK_READ', 'PERMISSION_QSE_ACCIDENT_AT_WORK_CREATE', 'PERMISSION_QSE_ACCIDENT_AT_WORK_UPDATE', 'PERMISSION_QSE_ACCIDENT_AT_WORK_SOFT_DELETE', 'PERMISSION_QSE_TA_ANALYSIS_READ', 'PERMISSION_QSE_TA_ANALYSIS_CREATE', 'PERMISSION_QSE_TA_ANALYSIS_UPDATE', 'PERMISSION_QSE_TA_ANALYSIS_SOFT_DELETE', 'PERMISSION_QSE_QUALITY_BASE_READ', 'PERMISSION_QSE_QUALITY_BASE_CREATE', 'PERMISSION_QSE_QUALITY_BASE_UPDATE', 'PERMISSION_QSE_QUALITY_BASE_SOFT_DELETE', 'PERMISSION_CRM_DASHBOARD_READ', 'PERMISSION_CRM_DASHBOARD_CREATE', 'PERMISSION_CRM_DASHBOARD_UPDATE', 'PERMISSION_CRM_DASHBOARD_SOFT_DELETE', 'PERMISSION_CRM_CUSTOMERS_OR_PROSPECTS_READ', 'PERMISSION_CRM_CUSTOMERS_OR_PROSPECTS_CREATE', 'PERMISSION_CRM_CUSTOMERS_OR_PROSPECTS_UPDATE', 'PERMISSION_CRM_CUSTOMERS_OR_PROSPECTS_SOFT_DELETE', 'PERMISSION_CRM_BUSINESS_READ', 'PERMISSION_CRM_BUSINESS_CREATE', 'PERMISSION_CRM_BUSINESS_UPDATE', 'PERMISSION_CRM_BUSINESS_SOFT_DELETE', 'PERMISSION_CRM_TASKS_TO_DO_READ', 'PERMISSION_CRM_TASKS_TO_DO_CREATE', 'PERMISSION_CRM_TASKS_TO_DO_UPDATE', 'PERMISSION_CRM_TASKS_TO_DO_SOFT_DELETE', 'PERMISSION_CRM_DATE_BOOK_READ', 'PERMISSION_CRM_DATE_BOOK_CREATE', 'PERMISSION_CRM_DATE_BOOK_UPDATE', 'PERMISSION_CRM_DATE_BOOK_SOFT_DELETE', 'PERMISSION_CRM_FOLLOW_UP_TABLE_READ', 'PERMISSION_CRM_FOLLOW_UP_TABLE_CREATE', 'PERMISSION_CRM_FOLLOW_UP_TABLE_UPDATE', 'PERMISSION_CRM_FOLLOW_UP_TABLE_SOFT_DELETE', 'PERMISSION_COSTING_DASHBOARD_READ', 'PERMISSION_COSTING_DASHBOARD_CREATE', 'PERMISSION_COSTING_DASHBOARD_UPDATE', 'PERMISSION_COSTING_DASHBOARD_SOFT_DELETE', 'PERMISSION_COSTING_LIST_OF_COSTINGS_READ', 'PERMISSION_COSTING_LIST_OF_COSTINGS_CREATE', 'PERMISSION_COSTING_LIST_OF_COSTINGS_UPDATE', 'PERMISSION_COSTING_LIST_OF_COSTINGS_SOFT_DELETE', 'PERMISSION_COSTING_QUOTE_READ', 'PERMISSION_COSTING_QUOTE_CREATE', 'PERMISSION_COSTING_QUOTE_UPDATE', 'PERMISSION_COSTING_QUOTE_SOFT_DELETE', 'PERMISSION_COSTING_CALLS_FOR_TENDER_READ', 'PERMISSION_COSTING_CALLS_FOR_TENDER_CREATE', 'PERMISSION_COSTING_CALLS_FOR_TENDER_UPDATE', 'PERMISSION_COSTING_CALLS_FOR_TENDER_SOFT_DELETE', 'PERMISSION_COSTING_BDD_MATERIALS_READ', 'PERMISSION_COSTING_BDD_MATERIALS_CREATE', 'PERMISSION_COSTING_BDD_MATERIALS_UPDATE', 'PERMISSION_COSTING_BDD_MATERIALS_SOFT_DELETE', 'PERMISSION_COSTING_BDD_WORKS_READ', 'PERMISSION_COSTING_BDD_WORKS_CREATE', 'PERMISSION_COSTING_BDD_WORKS_UPDATE', 'PERMISSION_COSTING_BDD_WORKS_SOFT_DELETE', 'PERMISSION_COSTING_MO_READ', 'PERMISSION_COSTING_MO_CREATE', 'PERMISSION_COSTING_MO_UPDATE', 'PERMISSION_COSTING_MO_SOFT_DELETE', 'PERMISSION_COSTING_SUPPLIERS_READ', 'PERMISSION_COSTING_SUPPLIERS_CREATE', 'PERMISSION_COSTING_SUPPLIERS_UPDATE', 'PERMISSION_COSTING_SUPPLIERS_SOFT_DELETE', 'PERMISSION_COSTING_SUBCONTRACTORS_READ', 'PERMISSION_COSTING_SUBCONTRACTORS_CREATE', 'PERMISSION_COSTING_SUBCONTRACTORS_UPDATE', 'PERMISSION_COSTING_SUBCONTRACTORS_SOFT_DELETE', 'PERMISSION_COSTING_TASKS_TO_DO_READ', 'PERMISSION_COSTING_TASKS_TO_DO_CREATE', 'PERMISSION_COSTING_TASKS_TO_DO_UPDATE', 'PERMISSION_COSTING_TASKS_TO_DO_SOFT_DELETE', 'PERMISSION_SABLIERE_DASHBOARD_READ', 'PERMISSION_SABLIERE_DASHBOARD_CREATE', 'PERMISSION_SABLIERE_DASHBOARD_UPDATE', 'PERMISSION_SABLIERE_DASHBOARD_SOFT_DELETE', 'PERMISSION_SABLIERE_CUSTOMER_DIRECTORY_READ', 'PERMISSION_SABLIERE_CUSTOMER_DIRECTORY_CREATE', 'PERMISSION_SABLIERE_CUSTOMER_DIRECTORY_UPDATE', 'PERMISSION_SABLIERE_CUSTOMER_DIRECTORY_SOFT_DELETE', 'PERMISSION_SABLIERE_VEHICLE_DIRECTORY_READ', 'PERMISSION_SABLIERE_VEHICLE_DIRECTORY_CREATE', 'PERMISSION_SABLIERE_VEHICLE_DIRECTORY_UPDATE', 'PERMISSION_SABLIERE_VEHICLE_DIRECTORY_SOFT_DELETE', 'PERMISSION_SABLIERE_PRODUCT_DIRECTORY_READ', 'PERMISSION_SABLIERE_PRODUCT_DIRECTORY_CREATE', 'PERMISSION_SABLIERE_PRODUCT_DIRECTORY_UPDATE', 'PERMISSION_SABLIERE_PRODUCT_DIRECTORY_SOFT_DELETE', 'PERMISSION_SABLIERE_QUOTE_READ', 'PERMISSION_SABLIERE_QUOTE_CREATE', 'PERMISSION_SABLIERE_QUOTE_UPDATE', 'PERMISSION_SABLIERE_QUOTE_SOFT_DELETE', 'PERMISSION_SABLIERE_BL_READ', 'PERMISSION_SABLIERE_BL_CREATE', 'PERMISSION_SABLIERE_BL_UPDATE', 'PERMISSION_SABLIERE_BL_SOFT_DELETE', 'PERMISSION_SABLIERE_WEIGHING_TICKET_READ', 'PERMISSION_SABLIERE_WEIGHING_TICKET_CREATE', 'PERMISSION_SABLIERE_WEIGHING_TICKET_UPDATE', 'PERMISSION_SABLIERE_WEIGHING_TICKET_SOFT_DELETE', 'PERMISSION_SABLIERE_INVOICE_READ', 'PERMISSION_SABLIERE_INVOICE_CREATE', 'PERMISSION_SABLIERE_INVOICE_UPDATE', 'PERMISSION_SABLIERE_INVOICE_SOFT_DELETE', 'PERMISSION_SABLIERE_ACCOUNTING_READ', 'PERMISSION_SABLIERE_ACCOUNTING_CREATE', 'PERMISSION_SABLIERE_ACCOUNTING_UPDATE', 'PERMISSION_SABLIERE_ACCOUNTING_SOFT_DELETE', 'PERMISSION_SABLIERE_ADMISSION_REGISTER_READ', 'PERMISSION_SABLIERE_ADMISSION_REGISTER_CREATE', 'PERMISSION_SABLIERE_ADMISSION_REGISTER_UPDATE', 'PERMISSION_SABLIERE_ADMISSION_REGISTER_SOFT_DELETE', 'PERMISSION_SABLIERE_DAP_READ', 'PERMISSION_SABLIERE_DAP_CREATE', 'PERMISSION_SABLIERE_DAP_UPDATE', 'PERMISSION_SABLIERE_DAP_SOFT_DELETE', 'PERMISSION_SABLIERE_DELIVERY_SCHEDULE_READ', 'PERMISSION_SABLIERE_DELIVERY_SCHEDULE_CREATE', 'PERMISSION_SABLIERE_DELIVERY_SCHEDULE_UPDATE', 'PERMISSION_SABLIERE_DELIVERY_SCHEDULE_SOFT_DELETE', 'PERMISSION_SABLIERE_DAILY_REPORTS_READ', 'PERMISSION_SABLIERE_DAILY_REPORTS_CREATE', 'PERMISSION_SABLIERE_DAILY_REPORTS_UPDATE', 'PERMISSION_SABLIERE_DAILY_REPORTS_SOFT_DELETE', 'PERMISSION_SABLIERE_ECOLOGICAL_MONITORING_REGISTER_READ', 'PERMISSION_SABLIERE_ECOLOGICAL_MONITORING_REGISTER_CREATE', 'PERMISSION_SABLIERE_ECOLOGICAL_MONITORING_REGISTER_UPDATE', 'PERMISSION_SABLIERE_ECOLOGICAL_MONITORING_REGISTER_SOFT_DELETE', 'PERMISSION_SABLIERE_QSE_REGISTER_READ', 'PERMISSION_SABLIERE_QSE_REGISTER_CREATE', 'PERMISSION_SABLIERE_QSE_REGISTER_UPDATE', 'PERMISSION_SABLIERE_QSE_REGISTER_SOFT_DELETE', 'PERMISSION_CGR_DASHBOARD_READ', 'PERMISSION_CGR_DASHBOARD_CREATE', 'PERMISSION_CGR_DASHBOARD_UPDATE', 'PERMISSION_CGR_DASHBOARD_SOFT_DELETE', 'PERMISSION_CGR_CUSTOMER_DIRECTORY_READ', 'PERMISSION_CGR_CUSTOMER_DIRECTORY_CREATE', 'PERMISSION_CGR_CUSTOMER_DIRECTORY_UPDATE', 'PERMISSION_CGR_CUSTOMER_DIRECTORY_SOFT_DELETE', 'PERMISSION_CGR_VEHICLE_DIRECTORY_READ', 'PERMISSION_CGR_VEHICLE_DIRECTORY_CREATE', 'PERMISSION_CGR_VEHICLE_DIRECTORY_UPDATE', 'PERMISSION_CGR_VEHICLE_DIRECTORY_SOFT_DELETE', 'PERMISSION_CGR_PRODUCT_DIRECTORY_READ', 'PERMISSION_CGR_PRODUCT_DIRECTORY_CREATE', 'PERMISSION_CGR_PRODUCT_DIRECTORY_UPDATE', 'PERMISSION_CGR_PRODUCT_DIRECTORY_SOFT_DELETE', 'PERMISSION_CGR_QUOTE_READ', 'PERMISSION_CGR_QUOTE_CREATE', 'PERMISSION_CGR_QUOTE_UPDATE', 'PERMISSION_CGR_QUOTE_SOFT_DELETE', 'PERMISSION_CGR_BL_READ', 'PERMISSION_CGR_BL_CREATE', 'PERMISSION_CGR_BL_UPDATE', 'PERMISSION_CGR_BL_SOFT_DELETE', 'PERMISSION_CGR_WEIGHING_TICKET_READ', 'PERMISSION_CGR_WEIGHING_TICKET_CREATE', 'PERMISSION_CGR_WEIGHING_TICKET_UPDATE', 'PERMISSION_CGR_WEIGHING_TICKET_SOFT_DELETE', 'PERMISSION_CGR_INVOICE_READ', 'PERMISSION_CGR_INVOICE_CREATE', 'PERMISSION_CGR_INVOICE_UPDATE', 'PERMISSION_CGR_INVOICE_SOFT_DELETE', 'PERMISSION_CGR_ACCOUNTING_READ', 'PERMISSION_CGR_ACCOUNTING_CREATE', 'PERMISSION_CGR_ACCOUNTING_UPDATE', 'PERMISSION_CGR_ACCOUNTING_SOFT_DELETE', 'PERMISSION_CGR_ADMISSION_REGISTER_READ', 'PERMISSION_CGR_ADMISSION_REGISTER_CREATE', 'PERMISSION_CGR_ADMISSION_REGISTER_UPDATE', 'PERMISSION_CGR_ADMISSION_REGISTER_SOFT_DELETE', 'PERMISSION_CGR_DAP_READ', 'PERMISSION_CGR_DAP_CREATE', 'PERMISSION_CGR_DAP_UPDATE', 'PERMISSION_CGR_DAP_SOFT_DELETE', 'PERMISSION_CGR_DELIVERY_SCHEDULE_READ', 'PERMISSION_CGR_DELIVERY_SCHEDULE_CREATE', 'PERMISSION_CGR_DELIVERY_SCHEDULE_UPDATE', 'PERMISSION_CGR_DELIVERY_SCHEDULE_SOFT_DELETE', 'PERMISSION_CGR_DAILY_REPORTS_READ', 'PERMISSION_CGR_DAILY_REPORTS_CREATE', 'PERMISSION_CGR_DAILY_REPORTS_UPDATE', 'PERMISSION_CGR_DAILY_REPORTS_SOFT_DELETE', 'PERMISSION_CGR_ECOLOGICAL_MONITORING_REGISTER_READ', 'PERMISSION_CGR_ECOLOGICAL_MONITORING_REGISTER_CREATE', 'PERMISSION_CGR_ECOLOGICAL_MONITORING_REGISTER_UPDATE', 'PERMISSION_CGR_ECOLOGICAL_MONITORING_REGISTER_SOFT_DELETE', 'PERMISSION_CGR_QSE_REGISTER_READ', 'PERMISSION_CGR_QSE_REGISTER_CREATE', 'PERMISSION_CGR_QSE_REGISTER_UPDATE', 'PERMISSION_CGR_QSE_REGISTER_SOFT_DELETE', 'PERMISSION_ADMIN_USER_DIRECTORY_READ', 'PERMISSION_ADMIN_USER_DIRECTORY_CREATE', 'PERMISSION_ADMIN_USER_DIRECTORY_UPDATE', 'PERMISSION_ADMIN_USER_DIRECTORY_SOFT_DELETE', 'PERMISSION_ADMIN_ACCESS_MANAGEMENT_READ', 'PERMISSION_ADMIN_ACCESS_MANAGEMENT_CREATE', 'PERMISSION_ADMIN_ACCESS_MANAGEMENT_UPDATE', 'PERMISSION_ADMIN_ACCESS_MANAGEMENT_SOFT_DELETE', 'PERMISSION_ADMIN_LOG_READ', 'PERMISSION_ADMIN_LOG_CREATE', 'PERMISSION_ADMIN_LOG_UPDATE', 'PERMISSION_ADMIN_LOG_SOFT_DELETE', 'PERMISSION_ADMIN_FORMS_READ', 'PERMISSION_ADMIN_FORMS_CREATE', 'PERMISSION_ADMIN_FORMS_UPDATE', 'PERMISSION_ADMIN_FORMS_SOFT_DELETE', 'PERMISSION_ADMIN_NEWS_READ', 'PERMISSION_ADMIN_NEWS_CREATE', 'PERMISSION_ADMIN_NEWS_UPDATE', 'PERMISSION_ADMIN_NEWS_SOFT_DELETE', 'PERMISSION_ADMIN_SURVEYS_READ', 'PERMISSION_ADMIN_SURVEYS_CREATE', 'PERMISSION_ADMIN_SURVEYS_UPDATE', 'PERMISSION_ADMIN_SURVEYS_SOFT_DELETE', 'PERMISSION_ADMIN_ORGANIZATION_CHART_READ', 'PERMISSION_ADMIN_ORGANIZATION_CHART_CREATE', 'PERMISSION_ADMIN_ORGANIZATION_CHART_UPDATE', 'PERMISSION_ADMIN_ORGANIZATION_CHART_SOFT_DELETE', 'PERMISSION_ADMIN_ROLE_INFORMATION_READ', 'PERMISSION_ADMIN_ROLE_INFORMATION_CREATE', 'PERMISSION_ADMIN_ROLE_INFORMATION_UPDATE', 'PERMISSION_ADMIN_ROLE_INFORMATION_SOFT_DELETE', 'PERMISSION_ADMIN_DOCUMENTS_READ', 'PERMISSION_ADMIN_DOCUMENTS_CREATE', 'PERMISSION_ADMIN_DOCUMENTS_UPDATE', 'PERMISSION_ADMIN_DOCUMENTS_SOFT_DELETE', 'PERMISSION_ADMIN_CATERER_READ', 'PERMISSION_ADMIN_CATERER_CREATE', 'PERMISSION_ADMIN_CATERER_UPDATE', 'PERMISSION_ADMIN_CATERER_SOFT_DELETE', 'PERMISSION_ADMIN_RH_CONTRACT_READ', 'PERMISSION_ADMIN_RH_CONTRACT_CREATE', 'PERMISSION_ADMIN_RH_CONTRACT_UPDATE', 'PERMISSION_ADMIN_RH_CONTRACT_SOFT_DELETE', 'PERMISSION_ADMIN_RH_DOCUMENT_READ', 'PERMISSION_ADMIN_RH_DOCUMENT_CREATE', 'PERMISSION_ADMIN_RH_DOCUMENT_UPDATE', 'PERMISSION_ADMIN_RH_DOCUMENT_SOFT_DELETE', 'PERMISSION_ADMIN_RH_PAYMENT_READ', 'PERMISSION_ADMIN_RH_PAYMENT_CREATE', 'PERMISSION_ADMIN_RH_PAYMENT_UPDATE', 'PERMISSION_ADMIN_RH_PAYMENT_SOFT_DELETE', 'PERMISSION_ADMIN_RH_MATERIAL_READ', 'PERMISSION_ADMIN_RH_MATERIAL_CREATE', 'PERMISSION_ADMIN_RH_MATERIAL_UPDATE', 'PERMISSION_ADMIN_RH_MATERIAL_SOFT_DELETE', 'PERMISSION_ADMIN_RH_SURVEYS_READ', 'PERMISSION_ADMIN_RH_SURVEYS_CREATE', 'PERMISSION_ADMIN_RH_SURVEYS_UPDATE', 'PERMISSION_ADMIN_RH_SURVEYS_SOFT_DELETE', 'PERMISSION_ADMIN_PURCHASE_PUNCH_OUT_READ', 'PERMISSION_ADMIN_PURCHASE_PUNCH_OUT_CREATE', 'PERMISSION_ADMIN_PURCHASE_PUNCH_OUT_UPDATE', 'PERMISSION_ADMIN_PURCHASE_PUNCH_OUT_SOFT_DELETE', 'PERMISSION_ADMIN_JOB_SITE_CARTE_READ', 'PERMISSION_ADMIN_JOB_SITE_CARTE_CREATE', 'PERMISSION_ADMIN_JOB_SITE_CARTE_UPDATE', 'PERMISSION_ADMIN_JOB_SITE_CARTE_SOFT_DELETE', 'PERMISSION_ADMIN_SABLIERE_DAILY_REPORT_READ', 'PERMISSION_ADMIN_SABLIERE_DAILY_REPORT_CREATE', 'PERMISSION_ADMIN_SABLIERE_DAILY_REPORT_UPDATE', 'PERMISSION_ADMIN_SABLIERE_DAILY_REPORT_SOFT_DELETE', 'PERMISSION_ADMIN_CODING_VALIDATION_OF_QUOTATION_READ', 'PERMISSION_ADMIN_CODING_VALIDATION_OF_QUOTATION_CREATE', 'PERMISSION_ADMIN_CODING_VALIDATION_OF_QUOTATION_UPDATE', 'PERMISSION_ADMIN_CODING_VALIDATION_OF_QUOTATION_SOFT_DELETE', 'PERMISSION_ADMIN_CLIENT_DIRECTORY_READ', 'PERMISSION_ADMIN_CLIENT_DIRECTORY_CREATE', 'PERMISSION_ADMIN_CLIENT_DIRECTORY_UPDATE', 'PERMISSION_ADMIN_CLIENT_DIRECTORY_SOFT_DELETE', 'PERMISSION_ADMIN_CUSTOMER_FORMS_READ', 'PERMISSION_ADMIN_CUSTOMER_FORMS_CREATE', 'PERMISSION_ADMIN_CUSTOMER_FORMS_UPDATE', 'PERMISSION_ADMIN_CUSTOMER_FORMS_SOFT_DELETE', 'PERMISSION_ADMIN_CUSTOMER_AREA_INFORMATION_READ', 'PERMISSION_ADMIN_CUSTOMER_AREA_INFORMATION_CREATE', 'PERMISSION_ADMIN_CUSTOMER_AREA_INFORMATION_UPDATE', 'PERMISSION_ADMIN_CUSTOMER_AREA_INFORMATION_SOFT_DELETE')`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_permission" ("id" SERIAL NOT NULL, "name" "tellos"."tellos_permission_name_enum" NOT NULL, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), CONSTRAINT "UQ_58f5ceed3daf35c68710a059277" UNIQUE ("name", "deleted_at"), CONSTRAINT "PK_0a5ecfbbb06e359d4f5e6a47a84" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_role" ("id" SERIAL NOT NULL, "label" character varying, "name" character varying(255) NOT NULL, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), CONSTRAINT "UQ_5e508b438ff870a61119478febc" UNIQUE ("name", "deleted_at"), CONSTRAINT "PK_d50455fa6a46885a4c0d9d52364" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_notification_type" ("id" SERIAL NOT NULL, "title" character varying, "icon" character varying, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), CONSTRAINT "UQ_b4d6af91e4d849e0bffe4ca3fff" UNIQUE ("title", "deleted_at"), CONSTRAINT "PK_2ddff7f5e6331da7d6b0eb4a811" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_notification_category_enum" AS ENUM('NOTIFICATION_DOCUMENT_REQUIRE', 'NOTIFICATION_DOCUMENT_ADDED', 'NOTIFICATION_DOCUMENT_REQUIRE_SIGN', 'NOTIFICATION_DOCUMENT_SIGNED')`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_notification" ("id" SERIAL NOT NULL, "category" "tellos"."tellos_notification_category_enum", "data" json, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), "type_id" integer, "info_id" integer, CONSTRAINT "REL_af920d50520fad71fa1509ec07" UNIQUE ("info_id"), CONSTRAINT "PK_4514ac4d00a40e170ad0349923a" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_notification_login" ("id" SERIAL NOT NULL, "is_read" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), "login_id" integer, "notification_id" integer, CONSTRAINT "REL_fb38e2612b87171bef1a35bcb0" UNIQUE ("notification_id"), CONSTRAINT "PK_ec502eca8676094471459cec9ca" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_customer_contact" ("id" SERIAL NOT NULL, "lastname" character varying(255), "firstname" character varying(255), "company" character varying(255), "department" character varying(255), "position" character varying(255), "email" character varying(255), "phone" character varying(255), "phone_fix" character varying(255), "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), "picture_id" integer, "customer_id" integer, CONSTRAINT "PK_c9e3726a0c9b1376eb36f75282f" PRIMARY KEY ("id")); COMMENT ON COLUMN "tellos_customer_contact"."lastname" IS 'Encryption value for field lastname'; COMMENT ON COLUMN "tellos_customer_contact"."firstname" IS 'Encryption value for field firstname'; COMMENT ON COLUMN "tellos_customer_contact"."company" IS 'Encryption value for field company'; COMMENT ON COLUMN "tellos_customer_contact"."department" IS 'Encryption value for field department'; COMMENT ON COLUMN "tellos_customer_contact"."position" IS 'Encryption value for field position'; COMMENT ON COLUMN "tellos_customer_contact"."email" IS 'Encryption value for field email'; COMMENT ON COLUMN "tellos_customer_contact"."phone" IS 'Encryption value for field phone'; COMMENT ON COLUMN "tellos_customer_contact"."phone_fix" IS 'Encryption value for field phoneFix'`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_customer_document" ("id" SERIAL NOT NULL, "title" character varying, "description" text, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), "customer_id" integer, "login_id" integer, "file_id" integer, CONSTRAINT "PK_8c4c6033d116243c3d2b79a6709" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_customer_timeline_type_enum" AS ENUM('NOTE', 'PHONE', 'MEETING', 'EMAIL', 'RESTAURANT')`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_customer_timeline" ("id" SERIAL NOT NULL, "title" character varying, "type" "tellos"."tellos_customer_timeline_type_enum", "comment" text, "date_from" TIMESTAMP, "date_to" TIMESTAMP, "is_todo" boolean NOT NULL DEFAULT false, "done_at" TIMESTAMP, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), "customer_id" integer, "login_id" integer, "file_id" integer, CONSTRAINT "PK_7e9ce285b61a7f67cab161a0e89" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_customer_familly_enum" AS ENUM('PRIVATE_PROMOTERS', 'PRIVATE_INDIVIDUALS', 'PRIVATE_COMMERCIAL', 'PUBLIC_POLITY', 'PUBLIC_LOCAL_AUTHORITIES', 'PUBLIC_LARGE_OPERATORS', 'PUBLIC_HLM_SOCIAL_HOUSING', 'INTRAGROUP')`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_customer_typology_enum" AS ENUM('CUSTOMER', 'PROSPECT')`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_customer_language_enum" AS ENUM('FRENCH', 'ENGLISH', 'GERMAN')`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_customer_taxe_code_enum" AS ENUM('SUBJECT_TO_VAT')`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_customer_regulation_code_enum" AS ENUM('CHEQUE_OR_BANK_TRANSFER_ON_RECEIPT_WITHOUT_DISCOUNT', 'CHEQUE_OR_TRANSFER_1_DISCOUNT', 'CHEQUE_OR_TRANSFER_2_DISCOUNT', 'CHEQUE_OR_TRANSFER_3_DISCOUNT', 'CHEQUE_OR_TRANSFER_4_DISCOUNT', 'DIRECT_DEBIT', 'ON_RECEIPT_NET_AND_WITHOUT_DISCOUNT', 'IMMEDIATE_CASH_BY_CHEQUE', 'UPON_RECEIPT_2_DISCOUNT', 'CASH_OR_CREDIT_CARD_PAYMENT_REQUIRED', 'MILKING_60_ON_THE_10', '50_DAYS', 'CHECK_OR_BANK_TRANSFER_AT_21_DAYS', '30_DAY_CHECK_FDM_ON_THE_10', '60_DAY_CHECK_FDM', 'CHEQUE_AT_60_DAYS_FDM_ON_THE_10', 'CHEQUE_PAYABLE_45_DAYS_FDM_DELIVERY_DATE', '30_DEPOSIT_ON_ORDER_BALANCE_ON_RECEIPT', '90_DAY_CHEQUE_ON_THE_20', 'TRANSFER_AT_60_DAYS_ON_THE_15', '30_DAYS_MILKING_FDM', 'CHEQUE_OR_TRANSFER_AT_45_DAYS_FDM', '30_DAYS_FM_ON_25', 'CHECK_ON_ORDER_CASHABLE_60_DAYS_DELIVERY_DATE', 'BANK_TRANSFER_CHECK_30_DAYS', 'CHEQUE_OR_TRANSFER_AT_45_DAYS', 'AT_60_DAYS_FROM_THE_INVOICE_DATE_BY_BANK_TRANSFER1', 'AT_90_DAYS_DATE_OF_INVOICE_BY_BANK_TRANSFER', 'AT_30_DAYS_END_OF_MONTH_BY_CHEQUE', 'AT_30_DAYS_END_OF_MONTH_BY_BANK_TRANSFER', 'AT_30_DAYS_FROM_THE_INVOICE_DATE_BY_BANK_TRANSFER', 'AT_45_DAYS_FROM_THE_INVOICE_DATE_BY_BANK_TRANSFER', 'AT_60_DAYS_FROM_THE_INVOICE_DATE_BY_BANK_TRANSFER2', 'AT_90_DAYS_FROM_THE_INVOICE_DATE_BY_BANK_TRANSFER', 'COMPENSATION', 'BO_AT_60_DAYS_FDM_ON_THE_15', 'AT_30_DAYS_DATE_OF_INVOICE_BY_DRAFT', 'AT_45_DAYS_DATE_OF_INVOICE_PER_DRAFT', 'AT_60_DAYS_DATE_OF_INVOICE_BY_DRAFT', 'CHEQUE_AT_15_DAYS', 'MILKING_AT_60_DAYS_FDM', '10_DAYS_DIRECT_DEBIT', '15_DAYS_DIRECT_DEBIT', '20_DAYS_DIRECT_DEBIT', '30_DAYS_DIRECT_DEBIT', '45_DAYS_DIRECT_DEBIT', 'TRANSFER_AT_60_DAYS_ON_THE_10', '60_DAYS_DIRECT_DEBIT', '90_FDM_ON_THE_10_DATE_OF_RECEIPT_OF_INVOICE', 'PROFORMA_CHEQUE', '30_DAYS_TRANSFER', '40_DAYS_FROM_DATE_OF_RECEIPT_OF_INVOICE', 'LCR_65_DAYS', 'PROFORMA_TRANSFER', 'CASH_PAYMENT', 'AT_45_DAYS_END_OF_MONTH_ON_THE_10', 'PAYMENT_BLOCKED')`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_customer_currency_enum" AS ENUM('EUROS')`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_customer" ("id" SERIAL NOT NULL, "name" character varying(255), "email" character varying(255), "code" character varying(255), "address" character varying(255), "address_bis" character varying(255), "zip_code" character varying(255), "city" character varying(255), "country" character varying(255), "familly" "tellos"."tellos_customer_familly_enum", "typology" "tellos"."tellos_customer_typology_enum", "language" "tellos"."tellos_customer_language_enum", "phone" character varying(255), "fax" character varying(255), "siret" character varying(255), "ape" character varying(255), "tva_number" character varying(255), "taxe_code" "tellos"."tellos_customer_taxe_code_enum", "regulation_code" "tellos"."tellos_customer_regulation_code_enum", "currency" "tellos"."tellos_customer_currency_enum", "rib" character varying(255), "domiciliation" character varying(255), "iban" character varying(255), "bic" character varying(255), "invoice_copy_number" integer, "discount_rate" double precision, "invoice_email" character varying(255), "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), "picture_id" integer, CONSTRAINT "UQ_b845d126c2963e8693dab5f3ccb" UNIQUE ("invoice_email", "deleted_at"), CONSTRAINT "UQ_cff1cef0084e4f4c18db07baa2e" UNIQUE ("bic", "deleted_at"), CONSTRAINT "UQ_c7e7f17eaa37a461b5bdd97e2a8" UNIQUE ("iban", "deleted_at"), CONSTRAINT "UQ_06260ca8306bce1ea4b39de2306" UNIQUE ("rib", "deleted_at"), CONSTRAINT "UQ_911186afbec854d243f963fda42" UNIQUE ("tva_number", "deleted_at"), CONSTRAINT "UQ_b1dcf3b1875b69125a40d3e07f8" UNIQUE ("ape", "deleted_at"), CONSTRAINT "UQ_decf4e663d08a477227f35256dd" UNIQUE ("siret", "deleted_at"), CONSTRAINT "UQ_73f9c4f9875bda06532fb503f39" UNIQUE ("code", "deleted_at"), CONSTRAINT "UQ_4ccacd4b18e2797042d3adb4f8f" UNIQUE ("email", "deleted_at"), CONSTRAINT "UQ_1b41c9612341e858afa26397171" UNIQUE ("name", "deleted_at"), CONSTRAINT "PK_52ecef43481bffe2aebd199452a" PRIMARY KEY ("id")); COMMENT ON COLUMN "tellos_customer"."name" IS 'Encryption value for field name'; COMMENT ON COLUMN "tellos_customer"."email" IS 'Encryption value for field email'; COMMENT ON COLUMN "tellos_customer"."code" IS 'Encryption value for field code'; COMMENT ON COLUMN "tellos_customer"."address" IS 'Encryption value for field address'; COMMENT ON COLUMN "tellos_customer"."address_bis" IS 'Encryption value for field addressBis'; COMMENT ON COLUMN "tellos_customer"."zip_code" IS 'Encryption value for field zipCode'; COMMENT ON COLUMN "tellos_customer"."city" IS 'Encryption value for field city'; COMMENT ON COLUMN "tellos_customer"."country" IS 'Encryption value for field country'; COMMENT ON COLUMN "tellos_customer"."phone" IS 'Encryption value for field phone'; COMMENT ON COLUMN "tellos_customer"."fax" IS 'Encryption value for field fax'; COMMENT ON COLUMN "tellos_customer"."siret" IS 'Encryption value for field siret'; COMMENT ON COLUMN "tellos_customer"."ape" IS 'Encryption value for field ape'; COMMENT ON COLUMN "tellos_customer"."tva_number" IS 'Encryption value for field tvaNumber'; COMMENT ON COLUMN "tellos_customer"."rib" IS 'Encryption value for field rib'; COMMENT ON COLUMN "tellos_customer"."domiciliation" IS 'Encryption value for field domiciliation'; COMMENT ON COLUMN "tellos_customer"."iban" IS 'Encryption value for field iban'; COMMENT ON COLUMN "tellos_customer"."bic" IS 'Encryption value for field bic'; COMMENT ON COLUMN "tellos_customer"."invoice_email" IS 'Encryption value for field invoiceEmail'`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_customer_note" ("id" SERIAL NOT NULL, "comment" text, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), "customer_id" integer, "login_id" integer, CONSTRAINT "PK_3d529bff6fc63a0e10b8585afc5" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_login" ("id" SERIAL NOT NULL, "email" character varying(255), "username" character varying(255), "active" boolean NOT NULL DEFAULT false, "password" character varying(255), "confirmed_at" TIMESTAMP, "last_login" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), "employee_id" integer, CONSTRAINT "UQ_6df18c08d3ea4471996ff21b55d" UNIQUE ("password"), CONSTRAINT "UQ_9a278f12cd8ec8f32343b322420" UNIQUE ("username", "deleted_at"), CONSTRAINT "UQ_ed0d2ce6036258db86221a6909f" UNIQUE ("email", "deleted_at"), CONSTRAINT "REL_f7f56864fafa89b614c3ea29cd" UNIQUE ("employee_id"), CONSTRAINT "PK_3b560360f9d3ece5e3177a330f3" PRIMARY KEY ("id")); COMMENT ON COLUMN "tellos_login"."email" IS 'Encryption value for field email'; COMMENT ON COLUMN "tellos_login"."username" IS 'Encryption value for field username'`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_quick_access" ("id" SERIAL NOT NULL, "label" character varying(255), "link" character varying(255), "color" character varying(100), "icon" character varying(100), "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), "employee_id" integer, CONSTRAINT "PK_40eda5bed23f640eba1338bdbf0" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_career_path_icon_enum" AS ENUM('INTERVIEW', 'CONTRACT', 'QUALIFICATION', 'TRAINING', 'DISCIPLINARY')`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_career_path" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "icon" "tellos"."tellos_career_path_icon_enum" NOT NULL, "start_date" TIMESTAMP WITH TIME ZONE, "end_date" TIMESTAMP WITH TIME ZONE, "comment" text, "editable" boolean NOT NULL DEFAULT false, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), "file_id" integer, "employee_id" integer, CONSTRAINT "PK_bd0fe9252ba40f161b65f278106" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_document_category" ("id" SERIAL NOT NULL, "title" character varying, "icon" character varying, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), CONSTRAINT "UQ_a836c0cf9c44fac9d33fe3ecc67" UNIQUE ("title", "deleted_at"), CONSTRAINT "PK_ed5066022447deecffa373ae801" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_document_type" ("id" SERIAL NOT NULL, "title" character varying, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), "category_id" integer, CONSTRAINT "UQ_91e59a6b1b7737a03102e051dfc" UNIQUE ("title", "deleted_at"), CONSTRAINT "PK_80fd8d7e69e56c019011294b43f" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_employee_document_status_enum" AS ENUM('STATUS_WAITING_FILE', 'STATUS_WAITING_SIGNATURE', 'STATUS_SIGNED', 'STATUS_NOT_SIGNED', 'STATUS_REFUSED', 'STATUS_ACCEPTED', 'STATUS_TRANSMITTED', 'STATUS_SIGNATURE_IN_PROGRESS')`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_employee_document" ("id" SERIAL NOT NULL, "validate_date" date, "dunning_date" date, "signed_date" date, "status" "tellos"."tellos_employee_document_status_enum" NOT NULL DEFAULT 'STATUS_WAITING_FILE', "require_employee_signature" boolean DEFAULT false, "require_employee_upload" boolean DEFAULT false, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), "type_id" integer, "file_id" integer, "employee_id" integer, CONSTRAINT "PK_f29484abb141ff4b76ef997f267" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_employe_contract_type_entry" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), CONSTRAINT "PK_0dc6c8672d0c060e6d205c583f4" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_employe_contract_apprentice" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), CONSTRAINT "PK_bb26b5597e351bac0ede4e7d9f2" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_employe_contract_section" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), CONSTRAINT "PK_3d8b091fc2330c33035cd4017b3" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_employe_contract_level" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), CONSTRAINT "PK_00aba348258a6f92f62e4fe9a01" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_employee_contract_renewal_enum" AS ENUM('YES', 'NO')`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_employee_contract_type_contract_enum" AS ENUM('CDI', 'CDD', 'Interim', 'Contrat pro', 'Stage', 'Alternant', 'Renew')`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_employee_contract_leaving_raison_enum" AS ENUM('MUTUAL_AGREEMENT')`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_employee_contract_category_enum" AS ENUM('FRAME')`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_employee_contract_age_category_enum" AS ENUM('MINOR', 'MAJOR')`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_employee_contract_payment_type_enum" AS ENUM('MONTHLY')`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_employee_contract_job_description_enum" AS ENUM('PROJECT_MANAGER')`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_employee_contract" ("id" SERIAL NOT NULL, "entry_date" date, "seniority_date" date, "sage_pay_code" character varying, "end_trial_period" date, "renewal" "tellos"."tellos_employee_contract_renewal_enum", "end_renewal" date, "type_contract" "tellos"."tellos_employee_contract_type_contract_enum", "end_contract_cdd" date, "amendment_cdd" date, "departure_date" date, "leaving_raison" "tellos"."tellos_employee_contract_leaving_raison_enum", "job" text, "category" "tellos"."tellos_employee_contract_category_enum", "code" character varying, "position" character varying, "coefficient" character varying, "large_rate_dep" character varying, "age_category" "tellos"."tellos_employee_contract_age_category_enum", "payment_type" "tellos"."tellos_employee_contract_payment_type_enum", "job_description" "tellos"."tellos_employee_contract_job_description_enum", "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), "type_entry_id" integer, "apprentice_id" integer, "section_id" integer, "level_id" integer, "employee_id" integer, CONSTRAINT "REL_df3ca893fb77fbdf5143c67fbd" UNIQUE ("employee_id"), CONSTRAINT "PK_51fdfabd735a18b96704e55d5a3" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_contract_preview_status_enum" AS ENUM('GREEN', 'RED', 'GRAY')`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_contract_preview_type_contract_enum" AS ENUM('CDI', 'CDD', 'Interim', 'Contrat pro', 'Stage', 'Alternant', 'Renew')`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_contract_preview" ("id" SERIAL NOT NULL, "text" text, "status" "tellos"."tellos_contract_preview_status_enum", "type_contract" "tellos"."tellos_contract_preview_type_contract_enum", "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), "employee_id" integer, "file_id" integer, CONSTRAINT "PK_620d28a98df6e71b03aae23c31a" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_import_contract" ("id" SERIAL NOT NULL, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), "file_id" integer, "employee_id" integer, CONSTRAINT "PK_95c52f6fa96a5971412e5a0fdfa" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_employee_diplome_enum" AS ENUM('CAP', 'BEP', 'BACCALAUREAT', 'DEUG', 'BTS', 'DUT', 'DEUST', 'LICENSE', 'LICENSE_PRO', 'BUT', 'MASTERY', 'MASTER', 'DOCTORAT')`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_employee_gender_enum" AS ENUM('MALE', 'FEMALE')`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_employee_family_status_enum" AS ENUM('SINGLE', 'PACS', 'MARRIED', 'DIVORCED', 'WIDOWER', 'FREE_UNION')`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_employee_title_enum" AS ENUM('SIR', 'MRS')`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_employee" ("id" SERIAL NOT NULL, "number" character varying, "diplome" "tellos"."tellos_employee_diplome_enum", "gender" "tellos"."tellos_employee_gender_enum", "number_of_children" integer, "nationality" character varying, "bank" character varying, "position" character varying, "rib" character varying, "family_status" "tellos"."tellos_employee_family_status_enum", "country_birth" character varying, "title" "tellos"."tellos_employee_title_enum", "secure_number" character varying, "residence_permit" character varying, "rp_delivery_by" character varying, "rp_expiration_date" date, "email_pro" character varying(255), "phone_pro" character varying, "phone_fix_pro" character varying, "email_perso" character varying(255), "phone_perso" character varying, "phone_fix_perso" character varying, "phone_shortcut" character varying, "internal_number" character varying, "handicap" boolean NOT NULL DEFAULT false, "lastname" character varying(255), "lastname_bis" character varying(255), "firstname" character varying(255), "birthday" date, "city_birth" character varying, "address" character varying, "postcode" character varying, "city" character varying, "country" character varying, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), "login_id" integer, "entity_id" integer, "company_departure_id" integer, "picture_id" integer, "department_id" integer, "superior_id" integer, "boss_id" integer, "employee_contract_id" integer, CONSTRAINT "UQ_0b00701534142a8ba05c0ddb9e1" UNIQUE ("rib", "deleted_at"), CONSTRAINT "UQ_ed28e13fb8cde3c3513b7b65cb3" UNIQUE ("residence_permit", "deleted_at"), CONSTRAINT "UQ_9085801a32fba6e9c46098c3e10" UNIQUE ("secure_number", "deleted_at"), CONSTRAINT "UQ_ad6691bd45ad4f60f3b39b2cb26" UNIQUE ("internal_number", "deleted_at"), CONSTRAINT "UQ_0a2ce7d53d6577a448585d9b8b1" UNIQUE ("phone_shortcut", "deleted_at"), CONSTRAINT "UQ_dc40f2c354a66fe7e39c9bc63f2" UNIQUE ("phone_fix_perso", "deleted_at"), CONSTRAINT "UQ_35c8c44c94d458dafea7bd3e745" UNIQUE ("phone_perso", "deleted_at"), CONSTRAINT "UQ_41814b51e1868286e4b9dfef945" UNIQUE ("email_perso", "deleted_at"), CONSTRAINT "UQ_743fbfa78cbb1e04b47a7f3c3d0" UNIQUE ("phone_fix_pro", "deleted_at"), CONSTRAINT "UQ_10aa58bd3b728e5f61ffec324b1" UNIQUE ("phone_pro", "deleted_at"), CONSTRAINT "UQ_c6adeb4363792bf052fdc453604" UNIQUE ("email_pro", "deleted_at"), CONSTRAINT "UQ_4af1ab257c00a4b6311156eb4e6" UNIQUE ("number", "deleted_at"), CONSTRAINT "REL_3113b720a06016a34ce3b4df60" UNIQUE ("login_id"), CONSTRAINT "REL_45f0d3363a6ee7dd856184a957" UNIQUE ("employee_contract_id"), CONSTRAINT "PK_136a3d280aa4e1286a40caadfcb" PRIMARY KEY ("id")); COMMENT ON COLUMN "tellos_employee"."email_pro" IS 'Encryption value for field emailPro'; COMMENT ON COLUMN "tellos_employee"."email_perso" IS 'Encryption value for field emailPerso'; COMMENT ON COLUMN "tellos_employee"."lastname" IS 'Encryption value for field lastname'; COMMENT ON COLUMN "tellos_employee"."lastname_bis" IS 'Encryption value for field lastnameBis'; COMMENT ON COLUMN "tellos_employee"."firstname" IS 'Encryption value for field firstname'`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_comment_contract" ("id" SERIAL NOT NULL, "comment" text, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), "employee_id" integer, "contract_preview_id" integer, CONSTRAINT "PK_707675e5bd9379dc0f79f7abc32" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "tellos"."tellos_paragraph_frame_category_enum" AS ENUM('CDI', 'CDD', 'Interim', 'Contrat pro', 'Stage', 'Alternant', 'Renew')`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_paragraph_frame" ("id" SERIAL NOT NULL, "category" "tellos"."tellos_paragraph_frame_category_enum", "title" character varying, "content" text, "active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(255), "updated_by" character varying(255), CONSTRAINT "PK_77488dcb9a171f35592d425935c" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_role_permission" ("role_id" integer NOT NULL, "permission_id" integer NOT NULL, CONSTRAINT "PK_d81d6a06d8e11bca8d1dec652a2" PRIMARY KEY ("role_id", "permission_id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_31f7981b7912144538b23d3894" ON "tellos_role_permission" ("role_id") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_be85fb0376b0f49522dc9b0a98" ON "tellos_role_permission" ("permission_id") `,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_customer_note_documents_upload" ("customer_note_id" integer NOT NULL, "upload_id" integer NOT NULL, CONSTRAINT "PK_7ce48d16dcf091d36b05ba31d0a" PRIMARY KEY ("customer_note_id", "upload_id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_f62eb25740c343d5701c3d72c7" ON "tellos_customer_note_documents_upload" ("customer_note_id") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_fa2b57b9285ad8c9493446c6ca" ON "tellos_customer_note_documents_upload" ("upload_id") `,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_login_role" ("login_id" integer NOT NULL, "role_id" integer NOT NULL, CONSTRAINT "PK_4f55be6b3398f67a65ef3739047" PRIMARY KEY ("login_id", "role_id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_ebbbc982356fefb9335ad2a97b" ON "tellos_login_role" ("login_id") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_8d886f5cdeb765d0c7f4a7c184" ON "tellos_login_role" ("role_id") `,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_login_token" ("login_id" integer NOT NULL, "token_id" integer NOT NULL, CONSTRAINT "PK_39719e3cb1bed6bf27528d4062c" PRIMARY KEY ("login_id", "token_id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_6ba2fa0b06abbe3e6c4f19e347" ON "tellos_login_token" ("login_id") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_e2cbb6f28bc69a48752ad81921" ON "tellos_login_token" ("token_id") `,
    );
    await queryRunner.query(
      `CREATE TABLE "tellos_employee_role" ("employee_id" integer NOT NULL, "role_id" integer NOT NULL, CONSTRAINT "PK_de994ea95481120e4daf78456d3" PRIMARY KEY ("employee_id", "role_id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_79592d5901ad7d8ead5844b346" ON "tellos_employee_role" ("employee_id") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_da776937a91ec065709f29ec2b" ON "tellos_employee_role" ("role_id") `,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_entity" ADD CONSTRAINT "FK_8731f3c17a5d3045976df2511b6" FOREIGN KEY ("logo_id") REFERENCES "tellos_upload"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_entity" ADD CONSTRAINT "FK_e2f6939bcfc471e3c2702befb4b" FOREIGN KEY ("organigramme_id") REFERENCES "tellos_upload"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_qualification" ADD CONSTRAINT "FK_993c5983c9e86311af44152ac70" FOREIGN KEY ("entity_id") REFERENCES "tellos_entity"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_qualification" ADD CONSTRAINT "FK_d29d7dc566af606747fef0ec80e" FOREIGN KEY ("department_id") REFERENCES "tellos_department"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_qualification" ADD CONSTRAINT "FK_26829fdd4c9ea57918e99c7b622" FOREIGN KEY ("employee_id") REFERENCES "tellos_employee"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_qualification" ADD CONSTRAINT "FK_9be9da28c7984d6fc0e68ca74b3" FOREIGN KEY ("type_id") REFERENCES "tellos_qualification_type"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_qualification" ADD CONSTRAINT "FK_0ea2909bccfb2b9f669862dd7e0" FOREIGN KEY ("name_id") REFERENCES "tellos_qualification_name"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_qualification" ADD CONSTRAINT "FK_be6181fe77ced1df9cfe7aaf92d" FOREIGN KEY ("document_id") REFERENCES "tellos_upload"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_leave" ADD CONSTRAINT "FK_c83d726155c2d29c7ddc3425f8c" FOREIGN KEY ("employee_id") REFERENCES "tellos_employee"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_leave" ADD CONSTRAINT "FK_807ff2592571916aa7c8d9a1f2e" FOREIGN KEY ("service_id") REFERENCES "tellos_department"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_leave" ADD CONSTRAINT "FK_f2340f410e5fbf50a5a72d9e5d4" FOREIGN KEY ("decision_maker_id") REFERENCES "tellos_employee"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_notification" ADD CONSTRAINT "FK_2ddff7f5e6331da7d6b0eb4a811" FOREIGN KEY ("type_id") REFERENCES "tellos_notification_type"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_notification" ADD CONSTRAINT "FK_af920d50520fad71fa1509ec07a" FOREIGN KEY ("info_id") REFERENCES "tellos_notification_login"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_notification_login" ADD CONSTRAINT "FK_0b207d29516798c850548c4008a" FOREIGN KEY ("login_id") REFERENCES "tellos_login"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_notification_login" ADD CONSTRAINT "FK_fb38e2612b87171bef1a35bcb0a" FOREIGN KEY ("notification_id") REFERENCES "tellos_notification"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_contact" ADD CONSTRAINT "FK_f629eeb0f9028eaaf0861fd4239" FOREIGN KEY ("picture_id") REFERENCES "tellos_upload"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_contact" ADD CONSTRAINT "FK_87f90d01c2e7c2101d679486a9d" FOREIGN KEY ("customer_id") REFERENCES "tellos_customer"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_document" ADD CONSTRAINT "FK_6752d886cc4fb050114beb610f2" FOREIGN KEY ("customer_id") REFERENCES "tellos_customer"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_document" ADD CONSTRAINT "FK_e6c7c5794545bd060e0fb6fed62" FOREIGN KEY ("login_id") REFERENCES "tellos_login"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_document" ADD CONSTRAINT "FK_bf542021df4bc5425a75ed837e8" FOREIGN KEY ("file_id") REFERENCES "tellos_upload"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_timeline" ADD CONSTRAINT "FK_62f0d6e42c8e4fdc166aea7e890" FOREIGN KEY ("customer_id") REFERENCES "tellos_customer"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_timeline" ADD CONSTRAINT "FK_758a65e1241b7044de3fed2e583" FOREIGN KEY ("login_id") REFERENCES "tellos_login"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_timeline" ADD CONSTRAINT "FK_c79f30e1c202c75f1a777554c5a" FOREIGN KEY ("file_id") REFERENCES "tellos_upload"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer" ADD CONSTRAINT "FK_ffdd3df93e91028c885954aee6c" FOREIGN KEY ("picture_id") REFERENCES "tellos_upload"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_note" ADD CONSTRAINT "FK_3c57aa6e6227a7cd865c4aceedb" FOREIGN KEY ("customer_id") REFERENCES "tellos_customer"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_note" ADD CONSTRAINT "FK_621b281c243cff6a036f507f2da" FOREIGN KEY ("login_id") REFERENCES "tellos_login"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_login" ADD CONSTRAINT "FK_f7f56864fafa89b614c3ea29cdb" FOREIGN KEY ("employee_id") REFERENCES "tellos_employee"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_quick_access" ADD CONSTRAINT "FK_8cecc30136eb59c325781243e58" FOREIGN KEY ("employee_id") REFERENCES "tellos_employee"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_career_path" ADD CONSTRAINT "FK_356508f2024c59f954296834339" FOREIGN KEY ("file_id") REFERENCES "tellos_upload"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_career_path" ADD CONSTRAINT "FK_902ab24a91012f96dd2b8204283" FOREIGN KEY ("employee_id") REFERENCES "tellos_employee"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_document_type" ADD CONSTRAINT "FK_5efb362606a4e49975b4453a5bb" FOREIGN KEY ("category_id") REFERENCES "tellos_document_category"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee_document" ADD CONSTRAINT "FK_f00aa123ace66178203bdf032ea" FOREIGN KEY ("type_id") REFERENCES "tellos_document_type"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee_document" ADD CONSTRAINT "FK_4a538540261b014179c4e881125" FOREIGN KEY ("file_id") REFERENCES "tellos_upload"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee_document" ADD CONSTRAINT "FK_0591ac82977ccbc42eb263fd574" FOREIGN KEY ("employee_id") REFERENCES "tellos_employee"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee_contract" ADD CONSTRAINT "FK_aee6b22930b0dc90a231bef24e1" FOREIGN KEY ("type_entry_id") REFERENCES "tellos_employe_contract_type_entry"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee_contract" ADD CONSTRAINT "FK_baa1892678a8abacfcdbe4284aa" FOREIGN KEY ("apprentice_id") REFERENCES "tellos_employe_contract_apprentice"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee_contract" ADD CONSTRAINT "FK_71289660bfd918d9baeae22d965" FOREIGN KEY ("section_id") REFERENCES "tellos_employe_contract_section"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee_contract" ADD CONSTRAINT "FK_5ad1618759390232db93bff3f3d" FOREIGN KEY ("level_id") REFERENCES "tellos_employe_contract_level"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee_contract" ADD CONSTRAINT "FK_df3ca893fb77fbdf5143c67fbda" FOREIGN KEY ("employee_id") REFERENCES "tellos_employee"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_contract_preview" ADD CONSTRAINT "FK_b4f4ff114b5395866f2fef78a04" FOREIGN KEY ("employee_id") REFERENCES "tellos_employee"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_contract_preview" ADD CONSTRAINT "FK_e099aec098ea0434be25f78c88e" FOREIGN KEY ("file_id") REFERENCES "tellos_upload"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_import_contract" ADD CONSTRAINT "FK_aeb8ec1e7c770daaa9eb7d6b45e" FOREIGN KEY ("file_id") REFERENCES "tellos_upload"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_import_contract" ADD CONSTRAINT "FK_59b2148d651b98722967b56d8d6" FOREIGN KEY ("employee_id") REFERENCES "tellos_employee"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee" ADD CONSTRAINT "FK_3113b720a06016a34ce3b4df600" FOREIGN KEY ("login_id") REFERENCES "tellos_login"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee" ADD CONSTRAINT "FK_4c5b322de8c772ecb289c8cda57" FOREIGN KEY ("entity_id") REFERENCES "tellos_entity"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee" ADD CONSTRAINT "FK_238f57d952c29882811ec7cc3d5" FOREIGN KEY ("company_departure_id") REFERENCES "tellos_entity"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee" ADD CONSTRAINT "FK_e3d9c6b69e1313cb5c2fd4a18d3" FOREIGN KEY ("picture_id") REFERENCES "tellos_upload"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee" ADD CONSTRAINT "FK_0edfd5f5d9af71fa920fd5cf800" FOREIGN KEY ("department_id") REFERENCES "tellos_department"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee" ADD CONSTRAINT "FK_0d09a76c8e9ba1a87748988cfea" FOREIGN KEY ("superior_id") REFERENCES "tellos_employee"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee" ADD CONSTRAINT "FK_85a8c54ac375ffb2b1ebf170f68" FOREIGN KEY ("boss_id") REFERENCES "tellos_employee"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee" ADD CONSTRAINT "FK_45f0d3363a6ee7dd856184a9574" FOREIGN KEY ("employee_contract_id") REFERENCES "tellos_employee_contract"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_comment_contract" ADD CONSTRAINT "FK_1d4b4539a7f73e0b30ff449478c" FOREIGN KEY ("employee_id") REFERENCES "tellos_employee"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_comment_contract" ADD CONSTRAINT "FK_e6b160058fd8cceafad8a327d5d" FOREIGN KEY ("contract_preview_id") REFERENCES "tellos_contract_preview"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_role_permission" ADD CONSTRAINT "FK_31f7981b7912144538b23d3894c" FOREIGN KEY ("role_id") REFERENCES "tellos_role"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_role_permission" ADD CONSTRAINT "FK_be85fb0376b0f49522dc9b0a98a" FOREIGN KEY ("permission_id") REFERENCES "tellos_permission"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_note_documents_upload" ADD CONSTRAINT "FK_f62eb25740c343d5701c3d72c72" FOREIGN KEY ("customer_note_id") REFERENCES "tellos_customer_note"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_note_documents_upload" ADD CONSTRAINT "FK_fa2b57b9285ad8c9493446c6ca1" FOREIGN KEY ("upload_id") REFERENCES "tellos_upload"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_login_role" ADD CONSTRAINT "FK_ebbbc982356fefb9335ad2a97bb" FOREIGN KEY ("login_id") REFERENCES "tellos_login"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_login_role" ADD CONSTRAINT "FK_8d886f5cdeb765d0c7f4a7c184b" FOREIGN KEY ("role_id") REFERENCES "tellos_role"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_login_token" ADD CONSTRAINT "FK_6ba2fa0b06abbe3e6c4f19e347e" FOREIGN KEY ("login_id") REFERENCES "tellos_login"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_login_token" ADD CONSTRAINT "FK_e2cbb6f28bc69a48752ad81921e" FOREIGN KEY ("token_id") REFERENCES "tellos_token"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee_role" ADD CONSTRAINT "FK_79592d5901ad7d8ead5844b346d" FOREIGN KEY ("employee_id") REFERENCES "tellos_employee"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee_role" ADD CONSTRAINT "FK_da776937a91ec065709f29ec2b0" FOREIGN KEY ("role_id") REFERENCES "tellos_role"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "tellos_employee_role" DROP CONSTRAINT "FK_da776937a91ec065709f29ec2b0"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee_role" DROP CONSTRAINT "FK_79592d5901ad7d8ead5844b346d"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_login_token" DROP CONSTRAINT "FK_e2cbb6f28bc69a48752ad81921e"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_login_token" DROP CONSTRAINT "FK_6ba2fa0b06abbe3e6c4f19e347e"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_login_role" DROP CONSTRAINT "FK_8d886f5cdeb765d0c7f4a7c184b"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_login_role" DROP CONSTRAINT "FK_ebbbc982356fefb9335ad2a97bb"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_note_documents_upload" DROP CONSTRAINT "FK_fa2b57b9285ad8c9493446c6ca1"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_note_documents_upload" DROP CONSTRAINT "FK_f62eb25740c343d5701c3d72c72"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_role_permission" DROP CONSTRAINT "FK_be85fb0376b0f49522dc9b0a98a"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_role_permission" DROP CONSTRAINT "FK_31f7981b7912144538b23d3894c"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_comment_contract" DROP CONSTRAINT "FK_e6b160058fd8cceafad8a327d5d"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_comment_contract" DROP CONSTRAINT "FK_1d4b4539a7f73e0b30ff449478c"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee" DROP CONSTRAINT "FK_45f0d3363a6ee7dd856184a9574"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee" DROP CONSTRAINT "FK_85a8c54ac375ffb2b1ebf170f68"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee" DROP CONSTRAINT "FK_0d09a76c8e9ba1a87748988cfea"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee" DROP CONSTRAINT "FK_0edfd5f5d9af71fa920fd5cf800"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee" DROP CONSTRAINT "FK_e3d9c6b69e1313cb5c2fd4a18d3"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee" DROP CONSTRAINT "FK_238f57d952c29882811ec7cc3d5"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee" DROP CONSTRAINT "FK_4c5b322de8c772ecb289c8cda57"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee" DROP CONSTRAINT "FK_3113b720a06016a34ce3b4df600"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_import_contract" DROP CONSTRAINT "FK_59b2148d651b98722967b56d8d6"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_import_contract" DROP CONSTRAINT "FK_aeb8ec1e7c770daaa9eb7d6b45e"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_contract_preview" DROP CONSTRAINT "FK_e099aec098ea0434be25f78c88e"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_contract_preview" DROP CONSTRAINT "FK_b4f4ff114b5395866f2fef78a04"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee_contract" DROP CONSTRAINT "FK_df3ca893fb77fbdf5143c67fbda"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee_contract" DROP CONSTRAINT "FK_5ad1618759390232db93bff3f3d"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee_contract" DROP CONSTRAINT "FK_71289660bfd918d9baeae22d965"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee_contract" DROP CONSTRAINT "FK_baa1892678a8abacfcdbe4284aa"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee_contract" DROP CONSTRAINT "FK_aee6b22930b0dc90a231bef24e1"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee_document" DROP CONSTRAINT "FK_0591ac82977ccbc42eb263fd574"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee_document" DROP CONSTRAINT "FK_4a538540261b014179c4e881125"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_employee_document" DROP CONSTRAINT "FK_f00aa123ace66178203bdf032ea"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_document_type" DROP CONSTRAINT "FK_5efb362606a4e49975b4453a5bb"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_career_path" DROP CONSTRAINT "FK_902ab24a91012f96dd2b8204283"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_career_path" DROP CONSTRAINT "FK_356508f2024c59f954296834339"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_quick_access" DROP CONSTRAINT "FK_8cecc30136eb59c325781243e58"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_login" DROP CONSTRAINT "FK_f7f56864fafa89b614c3ea29cdb"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_note" DROP CONSTRAINT "FK_621b281c243cff6a036f507f2da"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_note" DROP CONSTRAINT "FK_3c57aa6e6227a7cd865c4aceedb"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer" DROP CONSTRAINT "FK_ffdd3df93e91028c885954aee6c"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_timeline" DROP CONSTRAINT "FK_c79f30e1c202c75f1a777554c5a"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_timeline" DROP CONSTRAINT "FK_758a65e1241b7044de3fed2e583"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_timeline" DROP CONSTRAINT "FK_62f0d6e42c8e4fdc166aea7e890"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_document" DROP CONSTRAINT "FK_bf542021df4bc5425a75ed837e8"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_document" DROP CONSTRAINT "FK_e6c7c5794545bd060e0fb6fed62"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_document" DROP CONSTRAINT "FK_6752d886cc4fb050114beb610f2"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_contact" DROP CONSTRAINT "FK_87f90d01c2e7c2101d679486a9d"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_customer_contact" DROP CONSTRAINT "FK_f629eeb0f9028eaaf0861fd4239"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_notification_login" DROP CONSTRAINT "FK_fb38e2612b87171bef1a35bcb0a"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_notification_login" DROP CONSTRAINT "FK_0b207d29516798c850548c4008a"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_notification" DROP CONSTRAINT "FK_af920d50520fad71fa1509ec07a"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_notification" DROP CONSTRAINT "FK_2ddff7f5e6331da7d6b0eb4a811"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_leave" DROP CONSTRAINT "FK_f2340f410e5fbf50a5a72d9e5d4"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_leave" DROP CONSTRAINT "FK_807ff2592571916aa7c8d9a1f2e"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_leave" DROP CONSTRAINT "FK_c83d726155c2d29c7ddc3425f8c"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_qualification" DROP CONSTRAINT "FK_be6181fe77ced1df9cfe7aaf92d"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_qualification" DROP CONSTRAINT "FK_0ea2909bccfb2b9f669862dd7e0"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_qualification" DROP CONSTRAINT "FK_9be9da28c7984d6fc0e68ca74b3"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_qualification" DROP CONSTRAINT "FK_26829fdd4c9ea57918e99c7b622"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_qualification" DROP CONSTRAINT "FK_d29d7dc566af606747fef0ec80e"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_qualification" DROP CONSTRAINT "FK_993c5983c9e86311af44152ac70"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_entity" DROP CONSTRAINT "FK_e2f6939bcfc471e3c2702befb4b"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tellos_entity" DROP CONSTRAINT "FK_8731f3c17a5d3045976df2511b6"`,
    );
    await queryRunner.query(
      `DROP INDEX "tellos"."IDX_da776937a91ec065709f29ec2b"`,
    );
    await queryRunner.query(
      `DROP INDEX "tellos"."IDX_79592d5901ad7d8ead5844b346"`,
    );
    await queryRunner.query(`DROP TABLE "tellos_employee_role"`);
    await queryRunner.query(
      `DROP INDEX "tellos"."IDX_e2cbb6f28bc69a48752ad81921"`,
    );
    await queryRunner.query(
      `DROP INDEX "tellos"."IDX_6ba2fa0b06abbe3e6c4f19e347"`,
    );
    await queryRunner.query(`DROP TABLE "tellos_login_token"`);
    await queryRunner.query(
      `DROP INDEX "tellos"."IDX_8d886f5cdeb765d0c7f4a7c184"`,
    );
    await queryRunner.query(
      `DROP INDEX "tellos"."IDX_ebbbc982356fefb9335ad2a97b"`,
    );
    await queryRunner.query(`DROP TABLE "tellos_login_role"`);
    await queryRunner.query(
      `DROP INDEX "tellos"."IDX_fa2b57b9285ad8c9493446c6ca"`,
    );
    await queryRunner.query(
      `DROP INDEX "tellos"."IDX_f62eb25740c343d5701c3d72c7"`,
    );
    await queryRunner.query(
      `DROP TABLE "tellos_customer_note_documents_upload"`,
    );
    await queryRunner.query(
      `DROP INDEX "tellos"."IDX_be85fb0376b0f49522dc9b0a98"`,
    );
    await queryRunner.query(
      `DROP INDEX "tellos"."IDX_31f7981b7912144538b23d3894"`,
    );
    await queryRunner.query(`DROP TABLE "tellos_role_permission"`);
    await queryRunner.query(`DROP TABLE "tellos_paragraph_frame"`);
    await queryRunner.query(
      `DROP TYPE "tellos"."tellos_paragraph_frame_category_enum"`,
    );
    await queryRunner.query(`DROP TABLE "tellos_comment_contract"`);
    await queryRunner.query(`DROP TABLE "tellos_employee"`);
    await queryRunner.query(`DROP TYPE "tellos"."tellos_employee_title_enum"`);
    await queryRunner.query(
      `DROP TYPE "tellos"."tellos_employee_family_status_enum"`,
    );
    await queryRunner.query(`DROP TYPE "tellos"."tellos_employee_gender_enum"`);
    await queryRunner.query(
      `DROP TYPE "tellos"."tellos_employee_diplome_enum"`,
    );
    await queryRunner.query(`DROP TABLE "tellos_import_contract"`);
    await queryRunner.query(`DROP TABLE "tellos_contract_preview"`);
    await queryRunner.query(
      `DROP TYPE "tellos"."tellos_contract_preview_type_contract_enum"`,
    );
    await queryRunner.query(
      `DROP TYPE "tellos"."tellos_contract_preview_status_enum"`,
    );
    await queryRunner.query(`DROP TABLE "tellos_employee_contract"`);
    await queryRunner.query(
      `DROP TYPE "tellos"."tellos_employee_contract_job_description_enum"`,
    );
    await queryRunner.query(
      `DROP TYPE "tellos"."tellos_employee_contract_payment_type_enum"`,
    );
    await queryRunner.query(
      `DROP TYPE "tellos"."tellos_employee_contract_age_category_enum"`,
    );
    await queryRunner.query(
      `DROP TYPE "tellos"."tellos_employee_contract_category_enum"`,
    );
    await queryRunner.query(
      `DROP TYPE "tellos"."tellos_employee_contract_leaving_raison_enum"`,
    );
    await queryRunner.query(
      `DROP TYPE "tellos"."tellos_employee_contract_type_contract_enum"`,
    );
    await queryRunner.query(
      `DROP TYPE "tellos"."tellos_employee_contract_renewal_enum"`,
    );
    await queryRunner.query(`DROP TABLE "tellos_employe_contract_level"`);
    await queryRunner.query(`DROP TABLE "tellos_employe_contract_section"`);
    await queryRunner.query(`DROP TABLE "tellos_employe_contract_apprentice"`);
    await queryRunner.query(`DROP TABLE "tellos_employe_contract_type_entry"`);
    await queryRunner.query(`DROP TABLE "tellos_employee_document"`);
    await queryRunner.query(
      `DROP TYPE "tellos"."tellos_employee_document_status_enum"`,
    );
    await queryRunner.query(`DROP TABLE "tellos_document_type"`);
    await queryRunner.query(`DROP TABLE "tellos_document_category"`);
    await queryRunner.query(`DROP TABLE "tellos_career_path"`);
    await queryRunner.query(
      `DROP TYPE "tellos"."tellos_career_path_icon_enum"`,
    );
    await queryRunner.query(`DROP TABLE "tellos_quick_access"`);
    await queryRunner.query(`DROP TABLE "tellos_login"`);
    await queryRunner.query(`DROP TABLE "tellos_customer_note"`);
    await queryRunner.query(`DROP TABLE "tellos_customer"`);
    await queryRunner.query(
      `DROP TYPE "tellos"."tellos_customer_currency_enum"`,
    );
    await queryRunner.query(
      `DROP TYPE "tellos"."tellos_customer_regulation_code_enum"`,
    );
    await queryRunner.query(
      `DROP TYPE "tellos"."tellos_customer_taxe_code_enum"`,
    );
    await queryRunner.query(
      `DROP TYPE "tellos"."tellos_customer_language_enum"`,
    );
    await queryRunner.query(
      `DROP TYPE "tellos"."tellos_customer_typology_enum"`,
    );
    await queryRunner.query(
      `DROP TYPE "tellos"."tellos_customer_familly_enum"`,
    );
    await queryRunner.query(`DROP TABLE "tellos_customer_timeline"`);
    await queryRunner.query(
      `DROP TYPE "tellos"."tellos_customer_timeline_type_enum"`,
    );
    await queryRunner.query(`DROP TABLE "tellos_customer_document"`);
    await queryRunner.query(`DROP TABLE "tellos_customer_contact"`);
    await queryRunner.query(`DROP TABLE "tellos_notification_login"`);
    await queryRunner.query(`DROP TABLE "tellos_notification"`);
    await queryRunner.query(
      `DROP TYPE "tellos"."tellos_notification_category_enum"`,
    );
    await queryRunner.query(`DROP TABLE "tellos_notification_type"`);
    await queryRunner.query(`DROP TABLE "tellos_role"`);
    await queryRunner.query(`DROP TABLE "tellos_permission"`);
    await queryRunner.query(`DROP TYPE "tellos"."tellos_permission_name_enum"`);
    await queryRunner.query(`DROP TABLE "tellos_token"`);
    await queryRunner.query(`DROP TYPE "tellos"."tellos_token_name_enum"`);
    await queryRunner.query(`DROP TABLE "tellos_department"`);
    await queryRunner.query(`DROP TABLE "tellos_leave"`);
    await queryRunner.query(`DROP TYPE "tellos"."tellos_leave_gender_enum"`);
    await queryRunner.query(`DROP TYPE "tellos"."tellos_leave_decision_enum"`);
    await queryRunner.query(`DROP TYPE "tellos"."tellos_leave_contract_enum"`);
    await queryRunner.query(`DROP TYPE "tellos"."tellos_leave_entity_enum"`);
    await queryRunner.query(`DROP TYPE "tellos"."tellos_leave_type_enum"`);
    await queryRunner.query(`DROP TABLE "tellos_qualification"`);
    await queryRunner.query(`DROP TABLE "tellos_qualification_type"`);
    await queryRunner.query(`DROP TABLE "tellos_qualification_name"`);
    await queryRunner.query(`DROP TABLE "tellos_entity"`);
    await queryRunner.query(`DROP TABLE "tellos_upload"`);
  }
}
