/**
 * The actions type enum
 */
export enum ACTION_LOG_TYPES {
    // Actions for equipment theorical hour
    SUPPLIER_BILLING_READ = 'SUPPLIER_BILLING_READ',
    SUPPLIER_BILLING_CREATE = 'SUPPLIER_BILLING_CREATE',
    SUPPLIER_BILLING_UPDATE = 'SUPPLIER_BILLING_UPDATE',
    SUPPLIER_BILLING_DELETE = 'SUPPLIER_BILLING_DELETE',
    SUPPLIER_BILLING_SOFT_DELETE = 'SUPPLIER_BILLING_SOFT_DELETE',
    // Actions for Role
    ROLE_READ = 'ACTION_ROLE_READ',
    ROLE_CREATE = 'ACTION_ROLE_CREATE',
    ROLE_UPDATE = 'ACTION_ROLE_UPDATE',
    ROLE_DELETE = 'ACTION_ROLE_DELETE',
    ROLE_SOFT_DELETE = 'ACTION_ROLE_SOFT_DELETE',

    // Actions for Login
    LOGIN_READ = 'ACTION_LOGIN_READ',
    LOGIN_CREATE = 'ACTION_LOGIN_CREATE',
    LOGIN_UPDATE = 'ACTION_LOGIN_UPDATE',
    LOGIN_DELETE = 'ACTION_LOGIN_DELETE',
    LOGIN_SOFT_DELETE = 'ACTION_LOGIN_SOFT_DELETE',
    LOGIN_RECOVER_PASSWORD = 'ACTION_LOGIN_RECOVER_PASSWORD',
    LOGIN_RESET_PASSWORD = 'ACTION_LOGIN_RESET_PASSWORD',
    LOGIN_LOGIN = 'ACTION_LOGIN_LOGIN',

    // Actions for Quick Access
    QUICK_ACCESS_READ = 'ACTION_QUICK_ACCESS_READ',
    QUICK_ACCESS_CREATE = 'ACTION_QUICK_ACCESS_CREATE',
    QUICK_ACCESS_UPDATE = 'ACTION_QUICK_ACCESS_UPDATE',
    QUICK_ACCESS_DELETE = 'ACTION_QUICK_ACCESS_DELETE',
    QUICK_ACCESS_SOFT_DELETE = 'ACTION_QUICK_ACCESS_SOFT_DELETE',

    // Actions for Entity
    ENTITY_READ = 'ACTION_ENTITY_READ',
    ENTITY_CREATE = 'ACTION_ENTITY_CREATE',
    ENTITY_UPDATE = 'ACTION_ENTITY_UPDATE',
    ENTITY_DELETE = 'ACTION_ENTITY_DELETE',
    ENTITY_SOFT_DELETE = 'ACTION_ENTITY_SOFT_DELETE',

    // Actions for Document Category
    DOCUMENT_CATEGORY_READ = 'ACTION_DOCUMENT_CATEGORY_READ',
    DOCUMENT_CATEGORY_CREATE = 'ACTION_DOCUMENT_CATEGORY_CREATE',
    DOCUMENT_CATEGORY_UPDATE = 'ACTION_DOCUMENT_CATEGORY_UPDATE',
    DOCUMENT_CATEGORY_DELETE = 'ACTION_DOCUMENT_CATEGORY_DELETE',
    DOCUMENT_CATEGORY_SOFT_DELETE = 'ACTION_DOCUMENT_CATEGORY_SOFT_DELETE',

    // Actions for Document Type
    DOCUMENT_TYPE_READ = 'ACTION_DOCUMENT_TYPE_READ',
    DOCUMENT_TYPE_CREATE = 'ACTION_DOCUMENT_TYPE_CREATE',
    DOCUMENT_TYPE_UPDATE = 'ACTION_DOCUMENT_TYPE_UPDATE',
    DOCUMENT_TYPE_DELETE = 'ACTION_DOCUMENT_TYPE_DELETE',
    DOCUMENT_TYPE_SOFT_DELETE = 'ACTION_DOCUMENT_TYPE_SOFT_DELETE',

    // Actions for Employee
    EMPLOYEE_READ = 'ACTION_EMPLOYEE_READ',
    EMPLOYEE_CREATE = 'ACTION_EMPLOYEE_CREATE',
    EMPLOYEE_UPDATE = 'ACTION_EMPLOYEE_UPDATE',
    EMPLOYEE_DELETE = 'ACTION_EMPLOYEE_DELETE',
    EMPLOYEE_SOFT_DELETE = 'ACTION_EMPLOYEE_SOFT_DELETE',

    // Actions for Department
    DEPARTMENT_READ = 'ACTION_DEPARTMENT_READ',
    DEPARTMENT_CREATE = 'ACTION_DEPARTMENT_CREATE',
    DEPARTMENT_UPDATE = 'ACTION_DEPARTMENT_UPDATE',
    DEPARTMENT_DELETE = 'ACTION_DEPARTMENT_DELETE',
    DEPARTMENT_SOFT_DELETE = 'ACTION_DEPARTMENT_SOFT_DELETE',

    // Actions for Qualification
    QUALIFICATION_READ = 'ACTION_QUALIFICATION_READ',
    QUALIFICATION_CREATE = 'ACTION_QUALIFICATION_CREATE',
    QUALIFICATION_UPDATE = 'ACTION_QUALIFICATION_UPDATE',
    QUALIFICATION_DELETE = 'ACTION_QUALIFICATION_DELETE',
    QUALIFICATION_SOFT_DELETE = 'ACTION_QUALIFICATION_SOFT_DELETE',

    // Actions for Qualification name
    QUALIFICATION_NAME_READ = 'ACTION_QUALIFICATION_NAME_READ',
    QUALIFICATION_NAME_CREATE = 'ACTION_QUALIFICATION_NAME_CREATE',
    QUALIFICATION_NAME_UPDATE = 'ACTION_QUALIFICATION_NAME_UPDATE',
    QUALIFICATION_NAME_DELETE = 'ACTION_QUALIFICATION_NAME_DELETE',
    QUALIFICATION_NAME_SOFT_DELETE = 'ACTION_QUALIFICATION_NAME_SOFT_DELETE',

    // Actions for Qualification type
    QUALIFICATION_TYPE_READ = 'ACTION_QUALIFICATION_TYPE_READ',
    QUALIFICATION_TYPE_CREATE = 'ACTION_QUALIFICATION_TYPE_CREATE',
    QUALIFICATION_TYPE_UPDATE = 'ACTION_QUALIFICATION_TYPE_UPDATE',
    QUALIFICATION_TYPE_DELETE = 'ACTION_QUALIFICATION_TYPE_DELETE',
    QUALIFICATION_TYPE_SOFT_DELETE = 'ACTION_QUALIFICATION_TYPE_SOFT_DELETE',

    // Actions for Paragraph frame
    PARAGRAPH_FRAME_READ = 'ACTION_PARAGRAPH_FRAME_READ',
    PARAGRAPH_FRAME_CREATE = 'ACTION_PARAGRAPH_FRAME_CREATE',
    PARAGRAPH_FRAME_UPDATE = 'ACTION_PARAGRAPH_FRAME_UPDATE',
    PARAGRAPH_FRAME_DELETE = 'ACTION_PARAGRAPH_FRAME_DELETE',
    PARAGRAPH_FRAME_SOFT_DELETE = 'ACTION_PARAGRAPH_FRAME_SOFT_DELETE',

    // Actions for Career Path
    CAREER_PATH_READ = 'ACTION_CAREER_PATH_READ',
    CAREER_PATH_CREATE = 'ACTION_CAREER_PATH_CREATE',
    CAREER_PATH_UPDATE = 'ACTION_CAREER_PATH_UPDATE',
    CAREER_PATH_DELETE = 'ACTION_CAREER_PATH_DELETE',
    CAREER_PATH_SOFT_DELETE = 'ACTION_CAREER_PATH_SOFT_DELETE',

    // Actions for Employee Document
    EMPLOYEE_DOCUMENT_READ = 'ACTION_EMPLOYEE_DOCUMENT_READ',
    EMPLOYEE_DOCUMENT_CREATE = 'ACTION_EMPLOYEE_DOCUMENT_CREATE',
    EMPLOYEE_DOCUMENT_UPDATE = 'ACTION_EMPLOYEE_DOCUMENT_UPDATE',
    EMPLOYEE_DOCUMENT_DELETE = 'ACTION_EMPLOYEE_DOCUMENT_DELETE',
    EMPLOYEE_DOCUMENT_SOFT_DELETE = 'ACTION_EMPLOYEE_DOCUMENT_SOFT_DELETE',

    // Actions for Leave
    LEAVE_READ = 'ACTION_LEAVE_READ',
    LEAVE_CREATE = 'ACTION_LEAVE_CREATE',
    LEAVE_UPDATE = 'ACTION_LEAVE_UPDATE',
    LEAVE_DELETE = 'ACTION_LEAVE_DELETE',
    LEAVE_SOFT_DELETE = 'ACTION_LEAVE_SOFT_DELETE',

    // Actions for Employeee Contract
    CONTRACT_READ = 'ACTION_CONTRACT_READ',
    CONTRACT_CREATE = 'ACTION_CONTRACT_CREATE',
    CONTRACT_UPDATE = 'ACTION_CONTRACT_UPDATE',
    CONTRACT_DELETE = 'ACTION_CONTRACT_DELETE',
    CONTRACT_SOFT_DELETE = 'ACTION_CONTRACT_SOFT_DELETE',

    // Actions for Employeee Contract
    CONTRACT_INFO_READ = 'ACTION_CONTRACT_INFO_READ',
    CONTRACT_INFO_CREATE = 'ACTION_CONTRACT_INFO_CREATE',
    CONTRACT_INFO_UPDATE = 'ACTION_CONTRACT_INFO_UPDATE',
    CONTRACT_INFO_DELETE = 'ACTION_CONTRACT_INFO_DELETE',
    CONTRACT_INFO_SOFT_DELETE = 'ACTION_CONTRACT_INFO_SOFT_DELETE',

    // Actions for Employeee Contract Type Entry
    CONTRACT_TYPE_ENTRY_READ = 'ACTION_CONTRACT_TYPE_ENTRY_READ',
    CONTRACT_TYPE_ENTRY_CREATE = 'ACTION_CONTRACT_TYPE_ENTRY_CREATE',
    CONTRACT_TYPE_ENTRY_UPDATE = 'ACTION_CONTRACT_TYPE_ENTRY_UPDATE',
    CONTRACT_TYPE_ENTRY_DELETE = 'ACTION_CONTRACT_TYPE_ENTRY_DELETE',
    CONTRACT_TYPE_ENTRY_SOFT_DELETE = 'ACTION_CONTRACT_TYPE_ENTRY_SOFT_DELETE',

    // Actions for Employeee Contract Section
    CONTRACT_SECTION_READ = 'ACTION_CONTRACT_SECTION_READ',
    CONTRACT_SECTION_CREATE = 'ACTION_CONTRACT_SECTION_CREATE',
    CONTRACT_SECTION_UPDATE = 'ACTION_CONTRACT_SECTION_UPDATE',
    CONTRACT_SECTION_DELETE = 'ACTION_CONTRACT_SECTION_DELETE',
    CONTRACT_SECTION_SOFT_DELETE = 'ACTION_CONTRACT_SECTION_SOFT_DELETE',

    // Actions for Employeee Contract Level
    CONTRACT_LEVEL_READ = 'ACTION_CONTRACT_LEVEL_READ',
    CONTRACT_LEVEL_CREATE = 'ACTION_CONTRACT_LEVEL_CREATE',
    CONTRACT_LEVEL_UPDATE = 'ACTION_CONTRACT_LEVEL_UPDATE',
    CONTRACT_LEVEL_DELETE = 'ACTION_CONTRACT_LEVEL_DELETE',
    CONTRACT_LEVEL_SOFT_DELETE = 'ACTION_CONTRACT_LEVEL_SOFT_DELETE',

    // Actions for Employeee Contract Apprentice
    CONTRACT_APPRENTICE_READ = 'ACTION_CONTRACT_APPRENTICE_READ',
    CONTRACT_APPRENTICE_CREATE = 'ACTION_CONTRACT_APPRENTICE_CREATE',
    CONTRACT_APPRENTICE_UPDATE = 'ACTION_CONTRACT_APPRENTICE_UPDATE',
    CONTRACT_APPRENTICE_DELETE = 'ACTION_CONTRACT_APPRENTICE_DELETE',
    CONTRACT_APPRENTICE_SOFT_DELETE = 'ACTION_CONTRACT_APPRENTICE_SOFT_DELETE',

    // Actions for notification type
    NOTIFICATION_TYPE_READ = 'ACTION_NOTIFICATION_TYPE_READ',
    NOTIFICATION_TYPE_CREATE = 'ACTION_NOTIFICATION_TYPE_CREATE',
    NOTIFICATION_TYPE_UPDATE = 'ACTION_NOTIFICATION_TYPE_UPDATE',
    NOTIFICATION_TYPE_DELETE = 'ACTION_NOTIFICATION_TYPE_DELETE',
    NOTIFICATION_TYPE_SOFT_DELETE = 'ACTION_NOTIFICATION_TYPE_SOFT_DELETE',

    // Actions for notification
    NOTIFICATION_READ = 'ACTION_NOTIFICATION_TYPE_READ',
    NOTIFICATION_CREATE = 'ACTION_NOTIFICATION_TYPE_CREATE',
    NOTIFICATION_UPDATE = 'ACTION_NOTIFICATION_TYPE_UPDATE',
    NOTIFICATION_DELETE = 'ACTION_NOTIFICATION_TYPE_DELETE',
    NOTIFICATION_SOFT_DELETE = 'ACTION_NOTIFICATION_SOFT_DELETE',

    // Actions for comment contract
    CONTRACT_COMMENT_READ = 'ACTION_CONTRACT_COMMENT_READ',
    CONTRACT_COMMENT_CREATE = 'ACTION_CONTRACT_COMMENT_CREATE',
    CONTRACT_COMMENT_UPDATE = 'ACTION_CONTRACT_COMMENT_UPDATE',
    CONTRACT_COMMENT_DELETE = 'ACTION_CONTRACT_COMMENT_DELETE',
    CONTRACT_COMMENT_SOFT_DELETE = 'ACTION_CONTRACT_COMMENT_SOFT_DELETE',

    // Actions for leave distribution
    LEAVE_DISTRIBUTION_READ = 'ACTION_LEAVE_DISTRIBUTION_READ',
    LEAVE_DISTRIBUTION_CREATE = 'ACTION_LEAVE_DISTRIBUTION_CREATE',
    LEAVE_DISTRIBUTION_UPDATE = 'ACTION_LEAVE_DISTRIBUTION_UPDATE',
    LEAVE_DISTRIBUTION_DELETE = 'ACTION_LEAVE_DISTRIBUTION_DELETE',
    LEAVE_DISTRIBUTION_SOFT_DELETE = 'ACTION_LEAVE_DISTRIBUTION_SOFT_DELETE',

    // Actions for Customer
    CUSTOMER_READ = 'ACTION_CUSTOMER_READ',
    CUSTOMER_CREATE = 'ACTION_CUSTOMER_CREATE',
    CUSTOMER_UPDATE = 'ACTION_CUSTOMER_UPDATE',
    CUSTOMER_DELETE = 'ACTION_CUSTOMER_DELETE',
    CUSTOMER_SOFT_DELETE = 'ACTION_CUSTOMER_SOFT_DELETE',

    // Actions for Customer Contact
    CUSTOMER_CONTACT_READ = 'ACTION_CUSTOMER_CONTACT_READ',
    CUSTOMER_CONTACT_CREATE = 'ACTION_CUSTOMER_CONTACT_CREATE',
    CUSTOMER_CONTACT_UPDATE = 'ACTION_CUSTOMER_CONTACT_UPDATE',
    CUSTOMER_CONTACT_DELETE = 'ACTION_CUSTOMER_CONTACT_DELETE',
    CUSTOMER_CONTACT_SOFT_DELETE = 'ACTION_CUSTOMER_CONTACT_SOFT_DELETE',

    // Actions for Customer Note
    CUSTOMER_NOTE_READ = 'ACTION_CUSTOMER_NOTE_READ',
    CUSTOMER_NOTE_CREATE = 'ACTION_CUSTOMER_NOTE_CREATE',
    CUSTOMER_NOTE_UPDATE = 'ACTION_CUSTOMER_NOTE_UPDATE',
    CUSTOMER_NOTE_DELETE = 'ACTION_CUSTOMER_NOTE_DELETE',
    CUSTOMER_NOTE_SOFT_DELETE = 'ACTION_CUSTOMER_NOTE_SOFT_DELETE',

    // Actions for Customer Document
    CUSTOMER_DOCUMENT_READ = 'ACTION_CUSTOMER_DOCUMENT_READ',
    CUSTOMER_DOCUMENT_CREATE = 'ACTION_CUSTOMER_DOCUMENT_CREATE',
    CUSTOMER_DOCUMENT_UPDATE = 'ACTION_CUSTOMER_DOCUMENT_UPDATE',
    CUSTOMER_DOCUMENT_DELETE = 'ACTION_CUSTOMER_DOCUMENT_DELETE',
    CUSTOMER_DOCUMENT_SOFT_DELETE = 'ACTION_CUSTOMER_DOCUMENT_SOFT_DELETE',

    // Actions for Customer timeline
    CUSTOMER_TIMELINE_READ = 'ACTION_CUSTOMER_TIMELINE_READ',
    CUSTOMER_TIMELINE_CREATE = 'ACTION_CUSTOMER_TIMELINE_CREATE',
    CUSTOMER_TIMELINE_UPDATE = 'ACTION_CUSTOMER_TIMELINE_UPDATE',
    CUSTOMER_TIMELINE_DELETE = 'ACTION_CUSTOMER_TIMELINE_DELETE',
    CUSTOMER_TIMELINE_SOFT_DELETE = 'ACTION_CUSTOMER_TIMELINE_SOFT_DELETE',
    // Actions for notification type
    JOB_DESCRIPTION_READ = 'ACTION_JOB_DESCRIPTION_READ',
    JOB_DESCRIPTION_CREATE = 'ACTION_JOB_DESCRIPTION_CREATE',
    JOB_DESCRIPTION_UPDATE = 'ACTION_JOB_DESCRIPTION_UPDATE',
    JOB_DESCRIPTION_DELETE = 'ACTION_JOB_DESCRIPTION_DELETE',
    JOB_DESCRIPTION_SOFT_DELETE = 'ACTION_JOB_DESCRIPTION_SOFT_DELETE',

    // Actions for BUSINESS MARKET TYPE
    BUSINESS_MARKET_TYPE_READ = 'ACTION_BUSINESS_MARKET_TYPE_READ',
    BUSINESS_MARKET_TYPE_CREATE = 'ACTION_BUSINESS_MARKET_TYPE_CREATE',
    BUSINESS_MARKET_TYPE_UPDATE = 'ACTION_BUSINESS_MARKET_TYPE_UPDATE',
    BUSINESS_MARKET_TYPE_DELETE = 'ACTION_BUSINESS_MARKET_TYPE_DELETE',
    BUSINESS_MARKET_TYPE_SOFT_DELETE = 'ACTION_BUSINESS_MARKET_TYPE_SOFT_DELETE',

    // Actions for BUSINESS PAYMENT MODE
    BUSINESS_PAYMENT_MODE_READ = 'ACTION_BUSINESS_PAYMENT_MODE_READ',
    BUSINESS_PAYMENT_MODE_CREATE = 'ACTION_BUSINESS_PAYMENT_MODE_CREATE',
    BUSINESS_PAYMENT_MODE_UPDATE = 'ACTION_BUSINESS_PAYMENT_MODE_UPDATE',
    BUSINESS_PAYMENT_MODE_DELETE = 'ACTION_BUSINESS_PAYMENT_MODE_DELETE',
    BUSINESS_PAYMENT_MODE_SOFT_DELETE = 'ACTION_BUSINESS_PAYMENT_MODE_SOFT_DELETE',

    // Actions for BUSINESS PAYMENT TYPE
    BUSINESS_PAYMENT_TYPE_READ = 'ACTION_BUSINESS_PAYMENT_TYPE_READ',
    BUSINESS_PAYMENT_TYPE_CREATE = 'ACTION_BUSINESS_PAYMENT_TYPE_CREATE',
    BUSINESS_PAYMENT_TYPE_UPDATE = 'ACTION_BUSINESS_PAYMENT_TYPE_UPDATE',
    BUSINESS_PAYMENT_TYPE_DELETE = 'ACTION_BUSINESS_PAYMENT_TYPE_DELETE',
    BUSINESS_PAYMENT_TYPE_SOFT_DELETE = 'ACTION_BUSINESS_PAYMENT_TYPE_SOFT_DELETE',

    // Actions for BUSINESS TENDER TYPE
    BUSINESS_TENDER_TYPE_READ = 'ACTION_BUSINESS_TENDER_TYPE_READ',
    BUSINESS_TENDER_TYPE_CREATE = 'ACTION_BUSINESS_TENDER_TYPE_CREATE',
    BUSINESS_TENDER_TYPE_UPDATE = 'ACTION_BUSINESS_TENDER_TYPE_UPDATE',
    BUSINESS_TENDER_TYPE_DELETE = 'ACTION_BUSINESS_TENDER_TYPE_DELETE',
    BUSINESS_TENDER_TYPE_SOFT_DELETE = 'ACTION_BUSINESS_TENDER_TYPE_SOFT_DELETE',

    // Actions for BUSINESS DOCUMENT TYPE
    BUSINESS_DOCUMENT_TYPE_READ = 'ACTION_BUSINESS_DOCUMENT_TYPE_READ',
    BUSINESS_DOCUMENT_TYPE_CREATE = 'ACTION_BUSINESS_DOCUMENT_TYPE_CREATE',
    BUSINESS_DOCUMENT_TYPE_UPDATE = 'ACTION_BUSINESS_DOCUMENT_TYPE_UPDATE',
    BUSINESS_DOCUMENT_TYPE_DELETE = 'ACTION_BUSINESS_DOCUMENT_TYPE_DELETE',
    BUSINESS_DOCUMENT_TYPE_SOFT_DELETE = 'ACTION_BUSINESS_DOCUMENT_TYPE_SOFT_DELETE',

    // Actions for BUSINESS DOCUMENT CLASSIFICATION
    BUSINESS_DOCUMENT_CLASSIFICATION_READ = 'ACTION_BUSINESS_DOCUMENT_CLASSIFICATION_READ',
    BUSINESS_DOCUMENT_CLASSIFICATION_CREATE = 'ACTION_BUSINESS_DOCUMENT_CLASSIFICATION_CREATE',
    BUSINESS_DOCUMENT_CLASSIFICATION_UPDATE = 'ACTION_BUSINESS_DOCUMENT_CLASSIFICATION_UPDATE',
    BUSINESS_DOCUMENT_CLASSIFICATION_DELETE = 'ACTION_BUSINESS_DOCUMENT_CLASSIFICATION_DELETE',
    BUSINESS_DOCUMENT_CLASSIFICATION_SOFT_DELETE = 'ACTION_BUSINESS_DOCUMENT_CLASSIFICATION_SOFT_DELETE',

    // Actions for BUSINESS BATCH STATUS
    BUSINESS_BATCH_STATUS_READ = 'ACTION_BUSINESS_BATCH_STATUS_READ',
    BUSINESS_BATCH_STATUS_CREATE = 'ACTION_BUSINESS_BATCH_STATUS_CREATE',
    BUSINESS_BATCH_STATUS_UPDATE = 'ACTION_BUSINESS_BATCH_STATUS_UPDATE',
    BUSINESS_BATCH_STATUS_DELETE = 'ACTION_BUSINESS_BATCH_STATUS_DELETE',
    BUSINESS_BATCH_STATUS_SOFT_DELETE = 'ACTION_BUSINESS_BATCH_STATUS_SOFT_DELETE',

    // Actions for BUSINESS
    BUSINESS_READ = 'ACTION_BUSINESS_READ',
    BUSINESS_CREATE = 'ACTION_BUSINESS_CREATE',
    BUSINESS_UPDATE = 'ACTION_BUSINESS_UPDATE',
    BUSINESS_DELETE = 'ACTION_BUSINESS_DELETE',
    BUSINESS_SOFT_DELETE = 'ACTION_BUSINESS_SOFT_DELETE',

    // Actions for Employeee Contract Payment Type
    CONTRACT_TYPE_PAYMENT_READ = 'ACTION_CONTRACT_TYPE_PAYMENT_READ',
    CONTRACT_TYPE_PAYMENT_CREATE = 'ACTION_CONTRACT_TYPE_PAYMENT_CREATE',
    CONTRACT_TYPE_PAYMENT_UPDATE = 'ACTION_CONTRACT_TYPE_PAYMENT_UPDATE',
    CONTRACT_TYPE_PAYMENT_DELETE = 'ACTION_CONTRACT_TYPE_PAYMENT_DELETE',
    CONTRACT_TYPE_PAYMENT_SOFT_DELETE = 'ACTION_CONTRACT_TYPE_PAYMENT_SOFT_DELETE',

    // Actions for Medical visit
    MEDICAL_VISIT_READ = 'ACTION_MEDICAL_VISIT_READ',
    MEDICAL_VISIT_CREATE = 'ACTION_MEDICAL_VISIT_CREATE',
    MEDICAL_VISIT_UPDATE = 'ACTION_MEDICAL_VISIT_UPDATE',
    MEDICAL_VISIT_DELETE = 'ACTION_MEDICAL_VISIT_DELETE',
    MEDICAL_VISIT_SOFT_DELETE = 'ACTION_MEDICAL_VISIT_SOFT_DELETE',

    // Actions for Employee Disciplinary
    EMPLOYEE_DISCIPLINARY_READ = 'ACTION_EMPLOYEE_DISCIPLINARY_READ',
    EMPLOYEE_DISCIPLINARY_CREATE = 'ACTION_EMPLOYEE_DISCIPLINARY_CREATE',
    EMPLOYEE_DISCIPLINARY_UPDATE = 'ACTION_EMPLOYEE_DISCIPLINARY_UPDATE',
    EMPLOYEE_DISCIPLINARY_DELETE = 'ACTION_EMPLOYEE_DISCIPLINARY_DELETE',
    EMPLOYEE_DISCIPLINARY_SOFT_DELETE = 'ACTION_EMPLOYEE_DISCIPLINARY_SOFT_DELETE',

    // Actions for business batch
    BUSINESS_BATCH_READ = 'ACTION_BUSINESS_BATCH_READ',
    BUSINESS_BATCH_CREATE = 'ACTION_BUSINESS_BATCH_CREATE',
    BUSINESS_BATCH_UPDATE = 'ACTION_BUSINESS_BATCH_UPDATE',
    BUSINESS_BATCH_DELETE = 'ACTION_BUSINESS_BATCH_DELETE',
    BUSINESS_BATCH_SOFT_DELETE = 'ACTION_BUSINESS_BATCH_SOFT_DELETE',

    // Actions for business batch
    BUSINESS_DOCUMENT_READ = 'ACTION_BUSINESS_DOCUMENT_READ',
    BUSINESS_DOCUMENT_CREATE = 'ACTION_BUSINESS_DOCUMENT_CREATE',
    BUSINESS_DOCUMENT_UPDATE = 'ACTION_BUSINESS_DOCUMENT_UPDATE',
    BUSINESS_DOCUMENT_DELETE = 'ACTION_BUSINESS_DOCUMENT_DELETE',
    BUSINESS_DOCUMENT_SOFT_DELETE = 'ACTION_BUSINESS_DOCUMENT_SOFT_DELETE',

    // Actions for business batch
    REGULATION_CODE_READ = 'ACTION_REGULATION_CODE_READ',
    REGULATION_CODE_CREATE = 'ACTION_REGULATION_CODE_CREATE',
    REGULATION_CODE_UPDATE = 'ACTION_REGULATION_CODE_UPDATE',
    REGULATION_CODE_DELETE = 'ACTION_REGULATION_CODE_DELETE',
    REGULATION_CODE_SOFT_DELETE = 'ACTION_REGULATION_CODE_SOFT_DELETE',

    // Actions for business batch
    ADMIN_DOCUMENT_READ = 'ACTION_ADMIN_DOCUMENT_READ',
    ADMIN_DOCUMENT_CREATE = 'ACTION_ADMIN_DOCUMENT_CREATE',
    ADMIN_DOCUMENT_UPDATE = 'ACTION_ADMIN_DOCUMENT_UPDATE',
    ADMIN_DOCUMENT_DELETE = 'ACTION_ADMIN_DOCUMENT_DELETE',
    ADMIN_DOCUMENT_SOFT_DELETE = 'ACTION_ADMIN_DOCUMENT_SOFT_DELETE',

    // Actions for business batch
    LOGIN_PERMISSION_READ = 'ACTION_LOGIN_PERMISSION_READ',
    LOGIN_PERMISSION_CREATE = 'ACTION_LOGIN_PERMISSION_CREATE',
    LOGIN_PERMISSION_UPDATE = 'ACTION_LOGIN_PERMISSION_UPDATE',
    LOGIN_PERMISSION_DELETE = 'ACTION_LOGIN_PERMISSION_DELETE',
    LOGIN_PERMISSION_SOFT_DELETE = 'ACTION_LOGIN_PERMISSION_SOFT_DELETE',
    // Actions for expense post
    EXPENSE_POST_READ = 'ACTION_EXPENSE_POST_READ',
    EXPENSE_POST_CREATE = 'ACTION_EXPENSE_POST_CREATE',
    EXPENSE_POST_UPDATE = 'ACTION_EXPENSE_POST_UPDATE',
    EXPENSE_POST_DELETE = 'ACTION_EXPENSE_POST_DELETE',
    EXPENSE_POST_SOFT_DELETE = 'ACTION_EXPENSE_POST_SOFT_DELETE',

    // Actions for expense post
    SECTION_CODE_READ = 'ACTION_SECTION_CODE_READ',
    SECTION_CODE_CREATE = 'ACTION_SECTION_CODE_CREATE',
    SECTION_CODE_UPDATE = 'ACTION_SECTION_CODE_UPDATE',
    SECTION_CODE_DELETE = 'ACTION_SECTION_CODE_DELETE',
    SECTION_CODE_SOFT_DELETE = 'ACTION_SECTION_CODE_SOFT_DELETE',

    // Actions for purchase account
    PURCHASE_ACCOUNT_READ = 'ACTION_PURCHASE_ACCOUNT_READ',
    PURCHASE_ACCOUNT_CREATE = 'ACTION_PURCHASE_ACCOUNT_CREATE',
    PURCHASE_ACCOUNT_UPDATE = 'ACTION_PURCHASE_ACCOUNT_UPDATE',
    PURCHASE_ACCOUNT_DELETE = 'ACTION_PURCHASE_ACCOUNT_DELETE',
    PURCHASE_ACCOUNT_SOFT_DELETE = 'ACTION_PURCHASE_ACCOUNT_SOFT_DELETE',

    // Actions for medium sized centre
    MEDIUM_SIZED_CENTRE_READ = 'ACTION_MEDIUM_SIZED_CENTRE_READ',
    MEDIUM_SIZED_CENTRE_CREATE = 'ACTION_MEDIUM_SIZED_CENTRE_CREATE',
    MEDIUM_SIZED_CENTRE_UPDATE = 'ACTION_MEDIUM_SIZED_CENTRE_UPDATE',
    MEDIUM_SIZED_CENTRE_DELETE = 'ACTION_MEDIUM_SIZED_CENTRE_DELETE',
    MEDIUM_SIZED_CENTRE_SOFT_DELETE = 'ACTION_MEDIUM_SIZED_CENTRE_SOFT_DELETE',

    // Actions for category equipment
    CATEGORY_EQUIPMENT_READ = 'ACTION_CATEGORY_EQUIPMENT_READ',
    CATEGORY_EQUIPMENT_CREATE = 'ACTION_CATEGORY_EQUIPMENT_CREATE',
    CATEGORY_EQUIPMENT_UPDATE = 'ACTION_CATEGORY_EQUIPMENT_UPDATE',
    CATEGORY_EQUIPMENT_DELETE = 'ACTION_CATEGORY_EQUIPMENT_DELETE',
    CATEGORY_EQUIPMENT_SOFT_DELETE = 'ACTION_CATEGORY_EQUIPMENT_SOFT_DELETE',

    // Actions for earned leave
    LEAVE_PERIOD_READ = 'ACTION_LEAVE_PERIOD_READ',
    LEAVE_PERIOD_CREATE = 'ACTION_LEAVE_PERIOD_CREATE',
    LEAVE_PERIOD_UPDATE = 'ACTION_LEAVE_PERIOD_UPDATE',
    LEAVE_PERIOD_DELETE = 'ACTION_LEAVE_PERIOD_DELETE',
    LEAVE_PERIOD_SOFT_DELETE = 'ACTION_LEAVE_PERIOD_SOFT_DELETE',

    // Actions for work unit
    WORK_UNIT_READ = 'ACTION_WORK_UNIT_READ',
    WORK_UNIT_CREATE = 'ACTION_WORK_UNIT_CREATE',
    WORK_UNIT_UPDATE = 'ACTION_WORK_UNIT_UPDATE',
    WORK_UNIT_DELETE = 'ACTION_WORK_UNIT_DELETE',
    WORK_UNIT_SOFT_DELETE = 'ACTION_WORK_UNIT_SOFT_DELETE',

    // Actions for equipment
    EQUIPMENT_READ = 'ACTION_EQUIPMENT_READ',
    EQUIPMENT_CREATE = 'ACTION_EQUIPMENT_CREATE',
    EQUIPMENT_UPDATE = 'ACTION_EQUIPMENT_UPDATE',
    EQUIPMENT_DELETE = 'ACTION_EQUIPMENT_DELETE',
    EQUIPMENT_SOFT_DELETE = 'ACTION_EQUIPMENT_SOFT_DELETE',

    // Actions for work unit
    ADMINISTRATIVE_MATERIAL_READ = 'ACTION_ADMINISTRATIVE_MATERIAL_READ',
    ADMINISTRATIVE_MATERIAL_CREATE = 'ACTION_ADMINISTRATIVE_MATERIAL_CREATE',
    ADMINISTRATIVE_MATERIAL_UPDATE = 'ACTION_ADMINISTRATIVE_MATERIAL_UPDATE',
    ADMINISTRATIVE_MATERIAL_DELETE = 'ACTION_ADMINISTRATIVE_MATERIAL_DELETE',
    ADMINISTRATIVE_MATERIAL_SOFT_DELETE = 'ACTION_ADMINISTRATIVE_MATERIAL_SOFT_DELETE',

    // Actions for equipment document
    EQUIPMENT_DOCUMENT_READ = 'ACTION_EQUIPMENT_DOCUMENT_READ',
    EQUIPMENT_DOCUMENT_CREATE = 'ACTION_EQUIPMENT_DOCUMENT_CREATE',
    EQUIPMENT_DOCUMENT_UPDATE = 'ACTION_EQUIPMENT_DOCUMENT_UPDATE',
    EQUIPMENT_DOCUMENT_DELETE = 'ACTION_EQUIPMENT_DOCUMENT_DELETE',
    EQUIPMENT_DOCUMENT_SOFT_DELETE = 'ACTION_EQUIPMENT_DOCUMENT_SOFT_DELETE',

    // Actions for Article Family
    ARTICLE_FAMILY_READ = 'ACTION_ROLE_READ',
    ARTICLE_FAMILY_CREATE = 'ACTION_ROLE_CREATE',
    ARTICLE_FAMILY_UPDATE = 'ACTION_ROLE_UPDATE',
    ARTICLE_FAMILY_DELETE = 'ACTION_ROLE_DELETE',
    ARTICLE_FAMILY_SOFT_DELETE = 'ACTION_ROLE_SOFT_DELETE',

    // Actions for equipment park unit
    EQUIPMENT_PARK_UNIT_READ = 'ACTION_EQUIPMENT_PARK_UNIT_READ',
    EQUIPMENT_PARK_UNIT_CREATE = 'ACTION_EQUIPMENT_PARK_UNIT_CREATE',
    EQUIPMENT_PARK_UNIT_UPDATE = 'ACTION_EQUIPMENT_PARK_UNIT_UPDATE',
    EQUIPMENT_PARK_UNIT_DELETE = 'ACTION_EQUIPMENT_PARK_UNIT_DELETE',
    EQUIPMENT_PARK_UNIT_SOFT_DELETE = 'ACTION_EQUIPMENT_PARK_UNIT_SOFT_DELETE',

    // Actions for good
    GOOD_READ = 'ACTION_GOOD_READ',
    GOOD_CREATE = 'ACTION_GOOD_CREATE',
    GOOD_UPDATE = 'ACTION_GOOD_UPDATE',
    GOOD_DELETE = 'ACTION_GOOD_DELETE',
    GOOD_SOFT_DELETE = 'ACTION_GOOD_SOFT_DELETE',

    // Actions for insee code
    INSEE_CODE_READ = 'ACTION_INSEE_CODE_READ',
    INSEE_CODE_CREATE = 'ACTION_INSEE_CODE_CREATE',
    INSEE_CODE_UPDATE = 'ACTION_INSEE_CODE_UPDATE',
    INSEE_CODE_DELETE = 'ACTION_INSEE_CODE_DELETE',
    INSEE_CODE_SOFT_DELETE = 'ACTION_INSEE_CODE_SOFT_DELETE',

    // Actions for zone
    ZONE_READ = 'ACTION_ZONE_READ',
    ZONE_CREATE = 'ACTION_ZONE_CREATE',
    ZONE_UPDATE = 'ACTION_ZONE_UPDATE',
    ZONE_DELETE = 'ACTION_ZONE_DELETE',
    ZONE_SOFT_DELETE = 'ACTION_ZONE_SOFT_DELETE',

    // Actions for activity
    ACTIVITY_READ = 'ACTION_ACTIVITY_READ',
    ACTIVITY_CREATE = 'ACTION_ACTIVITY_CREATE',
    ACTIVITY_UPDATE = 'ACTION_ACTIVITY_UPDATE',
    ACTIVITY_DELETE = 'ACTION_ACTIVITY_DELETE',
    ACTIVITY_SOFT_DELETE = 'ACTION_ACTIVITY_SOFT_DELETE',

    // Actions for good reference price
    GOOD_REFERENCE_PRICE_READ = 'ACTION_GOOD_REFERENCE_PRICE_READ',
    GOOD_REFERENCE_PRICE_CREATE = 'ACTION_GOOD_REFERENCE_PRICE_CREATE',
    GOOD_REFERENCE_PRICE_UPDATE = 'ACTION_GOOD_REFERENCE_PRICE_UPDATE',
    GOOD_REFERENCE_PRICE_DELETE = 'ACTION_GOOD_REFERENCE_PRICE_DELETE',
    GOOD_REFERENCE_PRICE_SOFT_DELETE = 'ACTION_GOOD_REFERENCE_PRICE_SOFT_DELETE',

    // Actions for workforce rate
    WORKFORCE_RATE_READ = 'ACTION_WORKFORCE_RATE_READ',
    WORKFORCE_RATE_CREATE = 'ACTION_WORKFORCE_RATE_CREATE',
    WORKFORCE_RATE_UPDATE = 'ACTION_WORKFORCE_RATE_UPDATE',
    WORKFORCE_RATE_DELETE = 'ACTION_WORKFORCE_RATE_DELETE',
    WORKFORCE_RATE_SOFT_DELETE = 'ACTION_WORKFORCE_RATE_SOFT_DELETE',

    // Actions for workforce rate
    EQUIPMENT_RATE_READ = 'ACTION_EQUIPMENT_RATE_READ',
    EQUIPMENT_RATE_CREATE = 'ACTION_EQUIPMENT_RATE_CREATE',
    EQUIPMENT_RATE_UPDATE = 'ACTION_EQUIPMENT_RATE_UPDATE',
    EQUIPMENT_RATE_DELETE = 'ACTION_EQUIPMENT_RATE_DELETE',
    EQUIPMENT_RATE_SOFT_DELETE = 'ACTION_EQUIPMENT_RATE_SOFT_DELETE',

    // Actions for workforce rate
    SUPPLIER_CATEGORY_READ = 'ACTION_SUPPLIER_CATEGORY_READ',
    SUPPLIER_CATEGORY_CREATE = 'ACTION_SUPPLIER_CATEGORY_CREATE',
    SUPPLIER_CATEGORY_UPDATE = 'ACTION_SUPPLIER_CATEGORY_UPDATE',
    SUPPLIER_CATEGORY_DELETE = 'ACTION_SUPPLIER_CATEGORY_DELETE',
    SUPPLIER_CATEGORY_SOFT_DELETE = 'ACTION_SUPPLIER_CATEGORY_SOFT_DELETE',

    // Actions for equipment funding
    EQUIPMENT_FUNDING_READ = 'ACTION_EQUIPMENT_FUNDING_READ',
    EQUIPMENT_FUNDING_CREATE = 'ACTION_EQUIPMENT_FUNDING_CREATE',
    EQUIPMENT_FUNDING_UPDATE = 'ACTION_EQUIPMENT_FUNDING_UPDATE',
    EQUIPMENT_FUNDING_DELETE = 'ACTION_EQUIPMENT_FUNDING_DELETE',
    EQUIPMENT_FUNDING_SOFT_DELETE = 'ACTION_EQUIPMENT_FUNDING_SOFT_DELETE',

    // Actions for owner entity
    OWNER_ENTITY_READ = 'ACTION_OWNER_ENTITY_READ',
    OWNER_ENTITY_CREATE = 'ACTION_OWNER_ENTITY_CREATE',
    OWNER_ENTITY_UPDATE = 'ACTION_OWNER_ENTITY_UPDATE',
    OWNER_ENTITY_DELETE = 'ACTION_OWNER_ENTITY_DELETE',
    OWNER_ENTITY_SOFT_DELETE = 'ACTION_OWNER_ENTITY_SOFT_DELETE',

    // Actions for equipment technical thumbnail
    EQUIPMENT_TECHNICAL_THUMBNAIL_READ = 'ACTION_EQUIPMENT_TECHNICAL_THUMBNAIL_READ',
    EQUIPMENT_TECHNICAL_THUMBNAIL_CREATE = 'ACTION_EQUIPMENT_TECHNICAL_THUMBNAIL_CREATE',
    EQUIPMENT_TECHNICAL_THUMBNAIL_UPDATE = 'ACTION_EQUIPMENT_TECHNICAL_THUMBNAIL_UPDATE',
    EQUIPMENT_TECHNICAL_THUMBNAIL_DELETE = 'ACTION_EQUIPMENT_TECHNICAL_THUMBNAIL_DELETE',
    EQUIPMENT_TECHNICAL_THUMBNAIL_SOFT_DELETE = 'ACTION_EQUIPMENT_TECHNICAL_THUMBNAIL_SOFT_DELETE',

    // Actions for equipment technical genre
    EQUIPMENT_TECHNICAL_GENRE_READ = 'ACTION_EQUIPMENT_TECHNICAL_GENRE_READ',
    EQUIPMENT_TECHNICAL_GENRE_CREATE = 'ACTION_EQUIPMENT_TECHNICAL_GENRE_CREATE',
    EQUIPMENT_TECHNICAL_GENRE_UPDATE = 'ACTION_EQUIPMENT_TECHNICAL_GENRE_UPDATE',
    EQUIPMENT_TECHNICAL_GENRE_DELETE = 'ACTION_EQUIPMENT_TECHNICAL_GENRE_DELETE',
    EQUIPMENT_TECHNICAL_GENRE_SOFT_DELETE = 'ACTION_EQUIPMENT_TECHNICAL_GENRE_SOFT_DELETE',

    // Actions for equipment theorical hour
    EQUIPMENT_THEORICAL_HOUR_READ = 'ACTION_EQUIPMENT_THEORICAL_HOUR_READ',
    EQUIPMENT_THEORICAL_HOUR_CREATE = 'ACTION_EQUIPMENT_THEORICAL_HOUR_CREATE',
    EQUIPMENT_THEORICAL_HOUR_UPDATE = 'ACTION_EQUIPMENT_THEORICAL_HOUR_UPDATE',
    EQUIPMENT_THEORICAL_HOUR_DELETE = 'ACTION_EQUIPMENT_THEORICAL_HOUR_DELETE',
    EQUIPMENT_THEORICAL_HOUR_SOFT_DELETE = 'ACTION_EQUIPMENT_THEORICAL_HOUR_SOFT_DELETE',

    // Actions for equipment theorical hour
    SUPPLIER_NOTE_READ = 'SUPPLIER_NOTE_READ',
    SUPPLIER_NOTE_CREATE = 'SUPPLIER_NOTE_CREATE',
    SUPPLIER_NOTE_UPDATE = 'SUPPLIER_NOTE_UPDATE',
    SUPPLIER_NOTE_DELETE = 'SUPPLIER_NOTE_DELETE',
    SUPPLIER_NOTE_SOFT_DELETE = 'SUPPLIER_NOTE_SOFT_DELETE',

    // Actions for equipment theorical hour
    SUPPLIER_EVALUATION_READ = 'SUPPLIER_EVALUATION_READ',
    SUPPLIER_EVALUATION_CREATE = 'SUPPLIER_EVALUATION_CREATE',
    SUPPLIER_EVALUATION_UPDATE = 'SUPPLIER_EVALUATION_UPDATE',
    SUPPLIER_EVALUATION_DELETE = 'SUPPLIER_EVALUATION_DELETE',
    SUPPLIER_EVALUATION_SOFT_DELETE = 'SUPPLIER_EVALUATION_SOFT_DELETE',

    // Actions for equipment theorical hour
    SUPPLIER_AGENCY_READ = 'SUPPLIER_AGENCY_READ',
    SUPPLIER_AGENCY_CREATE = 'SUPPLIER_AGENCY_CREATE',
    SUPPLIER_AGENCY_UPDATE = 'SUPPLIER_AGENCY_UPDATE',
    SUPPLIER_AGENCY_DELETE = 'SUPPLIER_AGENCY_DELETE',
    SUPPLIER_AGENCY_SOFT_DELETE = 'SUPPLIER_AGENCY_SOFT_DELETE',

    // Actions for equipment theorical hour
    EQUIPMENT_PARK_DOCUMENT_READ = 'SUPPLIER_AGENCY_READ',
    EQUIPMENT_PARK_DOCUMENT_CREATE = 'SUPPLIER_AGENCY_CREATE',
    EQUIPMENT_PARK_DOCUMENT_UPDATE = 'SUPPLIER_AGENCY_UPDATE',
    EQUIPMENT_PARK_DOCUMENT_DELETE = 'SUPPLIER_AGENCY_DELETE',
    EQUIPMENT_PARK_DOCUMENT_SOFT_DELETE = 'SUPPLIER_AGENCY_SOFT_DELETE',

    // Actions for STOCK PILE
    STOCK_PILE_READ = 'ACTION_STOCK_PILE_READ',
    STOCK_PILE_CREATE = 'ACTION_STOCK_PILE_CREATE',
    STOCK_PILE_UPDATE = 'ACTION_STOCK_PILE_UPDATE',
    STOCK_PILE_DELETE = 'ACTION_STOCK_PILE_DELETE',
    STOCK_PILE_SOFT_DELETE = 'ACTION_STOCK_PILE_SOFT_DELETE',

    // Actions for workforce rate
    SUPPLIER_READ = 'ACTION_SUPPLIER_READ',
    SUPPLIER_CREATE = 'ACTION_SUPPLIER_CREATE',
    SUPPLIER_UPDATE = 'ACTION_SUPPLIER_UPDATE',
    SUPPLIER_DELETE = 'ACTION_SUPPLIER_DELETE',
    SUPPLIER_SOFT_DELETE = 'ACTION_SUPPLIER_SOFT_DELETE',

    // Actions for construction site
    CONSTRUCTION_SITE_READ = 'ACTION_CONSTRUCTION_SITE_READ',
    CONSTRUCTION_SITE_CREATE = 'ACTION_CONSTRUCTION_SITE_CREATE',
    CONSTRUCTION_SITE_UPDATE = 'ACTION_CONSTRUCTION_SITE_UPDATE',
    CONSTRUCTION_SITE_DELETE = 'ACTION_CONSTRUCTION_SITE_DELETE',
    CONSTRUCTION_SITE_SOFT_DELETE = 'ACTION_CONSTRUCTION_SITE_SOFT_DELETE',
}
