import { DEFAULT_NOTIFICATION_TYPES } from "./default.notification.type.enum";

export const DEFAULT_NOTIFICATION_TYPE_ICONS = new Map([
    [DEFAULT_NOTIFICATION_TYPES.TIME, 'icon-clock-plus'],
    [DEFAULT_NOTIFICATION_TYPES.LEAVE, 'icon-calendar-check-01'],
    [DEFAULT_NOTIFICATION_TYPES.FORM, 'icon-file-check-02'],
    [DEFAULT_NOTIFICATION_TYPES.FIGURES, 'icon-file-05'],
    [DEFAULT_NOTIFICATION_TYPES.EXPENSE_REPORT, 'icon-file-05'],
    [DEFAULT_NOTIFICATION_TYPES.DA, 'icon-file-05'],
    [DEFAULT_NOTIFICATION_TYPES.ORDERS, 'icon-file-05'],
    [DEFAULT_NOTIFICATION_TYPES.INVOICE, 'icon-file-05'],
    [DEFAULT_NOTIFICATION_TYPES.CLAIM, 'icon-file-05'],
    [DEFAULT_NOTIFICATION_TYPES.DOCUMENT, 'icon-file-05'],
    [DEFAULT_NOTIFICATION_TYPES.BONUS, 'icon-file-05'],
]);