import { ACTION_LOG_TYPES } from "src/modules/action-log/dto/types/actions.types.enum";

export const actionLabelMap = new Map<string, string>([
    //login
    [ACTION_LOG_TYPES.LOGIN_CREATE, "create"],
    [ACTION_LOG_TYPES.LOGIN_UPDATE, "edit"],
    [ACTION_LOG_TYPES.LOGIN_DELETE, "delete"],
    [ACTION_LOG_TYPES.LOGIN_SOFT_DELETE, "delete"],
    [ACTION_LOG_TYPES.LOGIN_LOGIN, "login"],

    //employee
    [ACTION_LOG_TYPES.EMPLOYEE_CREATE, "create"],
    // [ACTION_LOG_TYPES.EMPLOYEE_LOGIN, "read"],
    [ACTION_LOG_TYPES.EMPLOYEE_UPDATE, "edit"],
    [ACTION_LOG_TYPES.EMPLOYEE_DELETE, "delete"],
    [ACTION_LOG_TYPES.EMPLOYEE_SOFT_DELETE, "delete"],
    // [ACTION_LOG_TYPES.EMPLOYEE_RECOVER_PASSWORD, "edit"],
    // [ACTION_LOG_TYPES.EMPLOYEE_RESET_PASSWORD, "edit"],

    //quick_Access
    [ACTION_LOG_TYPES.QUICK_ACCESS_CREATE, "create"],
    [ACTION_LOG_TYPES.QUICK_ACCESS_UPDATE, "edit"],
    [ACTION_LOG_TYPES.QUICK_ACCESS_DELETE, "delete"],
    [ACTION_LOG_TYPES.QUICK_ACCESS_SOFT_DELETE, "delete"],

    //entity
    [ACTION_LOG_TYPES.ENTITY_CREATE, "create"],
    [ACTION_LOG_TYPES.ENTITY_UPDATE, "edit"],
    [ACTION_LOG_TYPES.ENTITY_DELETE, "delete"],
    [ACTION_LOG_TYPES.ENTITY_READ, "read"],
    [ACTION_LOG_TYPES.ENTITY_SOFT_DELETE, "delete"],

    //document tag
    [ACTION_LOG_TYPES.DOCUMENT_TYPE_READ, "read"],
    [ACTION_LOG_TYPES.DOCUMENT_TYPE_CREATE, "create"],
    [ACTION_LOG_TYPES.DOCUMENT_TYPE_UPDATE, "update"],
    [ACTION_LOG_TYPES.DOCUMENT_TYPE_DELETE, "delete"],
    [ACTION_LOG_TYPES.DOCUMENT_TYPE_SOFT_DELETE, "delete"],

    //department
    [ACTION_LOG_TYPES.DEPARTMENT_SOFT_DELETE, "delete"],
    [ACTION_LOG_TYPES.DEPARTMENT_CREATE, "create"],
    [ACTION_LOG_TYPES.DEPARTMENT_UPDATE, "edit"],
    [ACTION_LOG_TYPES.DEPARTMENT_DELETE, "delete"],

    //qualification name
    [ACTION_LOG_TYPES.QUALIFICATION_NAME_CREATE, "create"],
    [ACTION_LOG_TYPES.QUALIFICATION_NAME_UPDATE, "edit"],
    [ACTION_LOG_TYPES.QUALIFICATION_NAME_SOFT_DELETE, "delete"],
    [ACTION_LOG_TYPES.QUALIFICATION_NAME_DELETE, "delete"],
    [ACTION_LOG_TYPES.QUALIFICATION_NAME_READ, "read"],

    //qualification type
    [ACTION_LOG_TYPES.QUALIFICATION_TYPE_CREATE, "create"],
    [ACTION_LOG_TYPES.QUALIFICATION_TYPE_UPDATE, "edit"],
    [ACTION_LOG_TYPES.QUALIFICATION_TYPE_SOFT_DELETE, "delete"],
    [ACTION_LOG_TYPES.QUALIFICATION_TYPE_DELETE, "delete"],
    [ACTION_LOG_TYPES.QUALIFICATION_TYPE_READ, "read"],

    //qualification
    [ACTION_LOG_TYPES.QUALIFICATION_CREATE, "create"],
    [ACTION_LOG_TYPES.QUALIFICATION_UPDATE, "edit"],
    [ACTION_LOG_TYPES.QUALIFICATION_SOFT_DELETE, "delete"],
    [ACTION_LOG_TYPES.QUALIFICATION_DELETE, "delete"],
    [ACTION_LOG_TYPES.QUALIFICATION_READ, "read"],


    //Roles
    [ACTION_LOG_TYPES.ROLE_CREATE, "create"],
    [ACTION_LOG_TYPES.ROLE_UPDATE, "edit"],
    [ACTION_LOG_TYPES.ROLE_DELETE, "delete"],
    [ACTION_LOG_TYPES.ROLE_SOFT_DELETE, "delete"],
    [ACTION_LOG_TYPES.ROLE_READ, "create"],

    //document category
    [ACTION_LOG_TYPES.DOCUMENT_CATEGORY_READ, "read"],
    [ACTION_LOG_TYPES.DOCUMENT_CATEGORY_CREATE, "create"],
    [ACTION_LOG_TYPES.DOCUMENT_CATEGORY_UPDATE, "update"],
    [ACTION_LOG_TYPES.DOCUMENT_CATEGORY_DELETE, "delete"],
    [ACTION_LOG_TYPES.DOCUMENT_CATEGORY_SOFT_DELETE, "delete"],

    //document type
    [ACTION_LOG_TYPES.DOCUMENT_TYPE_READ, "read"],
    [ACTION_LOG_TYPES.DOCUMENT_TYPE_CREATE, "create"],
    [ACTION_LOG_TYPES.DOCUMENT_TYPE_UPDATE, "update"],
    [ACTION_LOG_TYPES.DOCUMENT_TYPE_DELETE, "delete"],
    [ACTION_LOG_TYPES.DOCUMENT_TYPE_SOFT_DELETE, "delete"],

    //paragraph frame
    [ACTION_LOG_TYPES.PARAGRAPH_FRAME_READ, "read"],
    [ACTION_LOG_TYPES.PARAGRAPH_FRAME_CREATE, "create"],
    [ACTION_LOG_TYPES.PARAGRAPH_FRAME_UPDATE, "update"],
    [ACTION_LOG_TYPES.PARAGRAPH_FRAME_DELETE, "delete"],
    [ACTION_LOG_TYPES.PARAGRAPH_FRAME_SOFT_DELETE, "delete"],

    // Career Path
    [ACTION_LOG_TYPES.CAREER_PATH_READ, "read"],
    [ACTION_LOG_TYPES.CAREER_PATH_CREATE, "create"],
    [ACTION_LOG_TYPES.CAREER_PATH_UPDATE, "update"],
    [ACTION_LOG_TYPES.CAREER_PATH_DELETE, "delete"],
    [ACTION_LOG_TYPES.CAREER_PATH_SOFT_DELETE, "delete"],

    //Employee Document
    [ACTION_LOG_TYPES.EMPLOYEE_DOCUMENT_READ, "read"],
    [ACTION_LOG_TYPES.EMPLOYEE_DOCUMENT_CREATE, "create"],
    [ACTION_LOG_TYPES.EMPLOYEE_DOCUMENT_UPDATE, "update"],
    [ACTION_LOG_TYPES.EMPLOYEE_DOCUMENT_DELETE, "delete"],
    [ACTION_LOG_TYPES.EMPLOYEE_DOCUMENT_SOFT_DELETE, "delete"],

    // Leave
    [ACTION_LOG_TYPES.LEAVE_READ, "read"],
    [ACTION_LOG_TYPES.LEAVE_CREATE, "create"],
    [ACTION_LOG_TYPES.LEAVE_UPDATE, "update"],
    [ACTION_LOG_TYPES.LEAVE_DELETE, "delete"],
    [ACTION_LOG_TYPES.LEAVE_SOFT_DELETE, "delete"],

    // Leave
    [ACTION_LOG_TYPES.EMPLOYEE_DOCUMENT_READ, "read"],
    [ACTION_LOG_TYPES.EMPLOYEE_DOCUMENT_CREATE, "create"],
    [ACTION_LOG_TYPES.EMPLOYEE_DOCUMENT_UPDATE, "update"],
    [ACTION_LOG_TYPES.EMPLOYEE_DOCUMENT_DELETE, "delete"],
    [ACTION_LOG_TYPES.EMPLOYEE_DOCUMENT_SOFT_DELETE, "delete"],

]);