export enum CustomerTypeEnum {
    PRIVATE_PROMOTERS = "PRIVATE_PROMOTERS",
    PRIVATE_INDIVIDUALS = "PRIVATE_INDIVIDUALS",
    PRIVATE_COMMERCIAL = "PRIVATE_COMMERCIAL",
    PUBLIC_POLITY = "PUBLIC_POLITY",
    PUBLIC_LOCAL_AUTHORITIES = "PUBLIC_LOCAL_AUTHORITIES",
    PUBLIC_LARGE_OPERATORS = "PUBLIC_LARGE_OPERATORS",
    PUBLIC_HLM_SOCIAL_HOUSING = "PUBLIC_HLM_SOCIAL_HOUSING",
    INTRAGROUP = "INTRAGROUP",
}