import { enumToArray } from "../utils/utils";
import { ValueOf } from "./default.types";

/**
 * Permissions Users
 */
export const PERMISSIONS_NAMES = {
    // :::::::::::::::::::::::::::::::::::::::::: All of Dashboard ::::::::::::::::::::::::::::::::::::::::::
    // Dashboard
    DASHBOARD_DASHBOARD_READ: "PERMISSION_DASHBOARD_DASHBOARD_READ",
    DASHBOARD_DASHBOARD_CREATE: "PERMISSION_DASHBOARD_DASHBOARD_CREATE",
    DASHBOARD_DASHBOARD_UPDATE: "PERMISSION_DASHBOARD_DASHBOARD_UPDATE",
    DASHBOARD_DASHBOARD_SOFT_DELETE: "PERMISSION_DASHBOARD_DASHBOARD_SOFT_DELETE",
    // Onboarding
    DASHBOARD_ONBOARDING_READ: "PERMISSION_DASHBOARD_ONBOARDING_READ",
    DASHBOARD_ONBOARDING_CREATE: "PERMISSION_DASHBOARD_ONBOARDING_CREATE",
    DASHBOARD_ONBOARDING_UPDATE: "PERMISSION_DASHBOARD_ONBOARDING_UPDATE",
    DASHBOARD_ONBOARDING_SOFT_DELETE: "PERMISSION_DASHBOARD_ONBOARDING_SOFT_DELETE",
    // Validations en attente
    DASHBOARD_PENDING_APPROVALS_READ: "PERMISSION_DASHBOARD_PENDING_APPROVALS_READ",
    DASHBOARD_PENDING_APPROVALS_CREATE: "PERMISSION_DASHBOARD_PENDING_APPROVALS_CREATE",
    DASHBOARD_PENDING_APPROVALS_UPDATE: "PERMISSION_DASHBOARD_PENDING_APPROVALS_UPDATE",
    DASHBOARD_PENDING_APPROVALS_SOFT_DELETE: "PERMISSION_DASHBOARD_PENDING_APPROVALS_SOFT_DELETE",
    // Annuaire 
    DASHBOARD_ADDRESS_LIST_READ: "PERMISSION_DASHBOARD_ADDRESS_LIST_READ",
    DASHBOARD_ADDRESS_LIST_CREATE: "PERMISSION_DASHBOARD_ADDRESS_LIST_CREATE",
    DASHBOARD_ADDRESS_LIST_UPDATE: "PERMISSION_DASHBOARD_ADDRESS_LIST_UPDATE",
    DASHBOARD_ADDRESS_LIST_SOFT_DELETE: "PERMISSION_DASHBOARD_ADDRESS_LIST_SOFT_DELETE",
    // Organigramme 
    DASHBOARD_ORGANIZATION_CHART_READ: "PERMISSION_DASHBOARD_ORGANIZATION_CHART_READ",
    DASHBOARD_ORGANIZATION_CHART_CREATE: "PERMISSION_DASHBOARD_ORGANIZATION_CHART_CREATE",
    DASHBOARD_ORGANIZATION_CHART_UPDATE: "PERMISSION_DASHBOARD_ORGANIZATION_CHART_UPDATE",
    DASHBOARD_ORGANIZATION_CHART_SOFT_DELETE: "PERMISSION_DASHBOARD_ORGANIZATION_CHART_SOFT_DELETE",
    // Rapports 
    DASHBOARD_REPORT_READ: "PERMISSION_DASHBOARD_REPORT_READ",
    DASHBOARD_REPORT_CREATE: "PERMISSION_DASHBOARD_REPORT_CREATE",
    DASHBOARD_REPORT_UPDATE: "PERMISSION_DASHBOARD_REPORT_UPDATE",
    DASHBOARD_REPORT_SOFT_DELETE: "PERMISSION_DASHBOARD_REPORT_SOFT_DELETE",
    // Statistiques 
    DASHBOARD_STATISTICS_READ: "PERMISSION_DASHBOARD_STATISTICS_READ",
    DASHBOARD_STATISTICS_CREATE: "PERMISSION_DASHBOARD_STATISTICS_CREATE",
    DASHBOARD_STATISTICS_UPDATE: "PERMISSION_DASHBOARD_STATISTICS_UPDATE",
    DASHBOARD_STATISTICS_SOFT_DELETE: "PERMISSION_DASHBOARD_STATISTICS_SOFT_DELETE",
    // Planning chantiers 
    DASHBOARD_SITE_PLANNING_READ: "PERMISSION_DASHBOARD_SITE_PLANNING_READ",
    DASHBOARD_SITE_PLANNING_CREATE: "PERMISSION_DASHBOARD_SITE_PLANNING_CREATE",
    DASHBOARD_SITE_PLANNING_UPDATE: "PERMISSION_DASHBOARD_SITE_PLANNING_UPDATE",
    DASHBOARD_SITE_PLANNING_SOFT_DELETE: "PERMISSION_DASHBOARD_SITE_PLANNING_SOFT_DELETE",
    // Planning équipes
    DASHBOARD_TEAM_PLANNING_READ: "PERMISSION_DASHBOARD_TEAM_PLANNING_READ",
    DASHBOARD_TEAM_PLANNING_CREATE: "PERMISSION_DASHBOARD_TEAM_PLANNING_CREATE",
    DASHBOARD_TEAM_PLANNING_UPDATE: "PERMISSION_DASHBOARD_TEAM_PLANNING_UPDATE",
    DASHBOARD_TEAM_PLANNING_SOFT_DELETE: "PERMISSION_DASHBOARD_TEAM_PLANNING_SOFT_DELETE",
    // Planning congés
    DASHBOARD_HOLIDAY_PLANNING_READ: "PERMISSION_DASHBOARD_HOLIDAY_PLANNING_READ",
    DASHBOARD_HOLIDAY_PLANNING_CREATE: "PERMISSION_DASHBOARD_HOLIDAY_PLANNING_CREATE",
    DASHBOARD_HOLIDAY_PLANNING_UPDATE: "PERMISSION_DASHBOARD_HOLIDAY_PLANNING_UPDATE",
    DASHBOARD_HOLIDAY_PLANNING_SOFT_DELETE: "PERMISSION_DASHBOARD_HOLIDAY_PLANNING_SOFT_DELETE",
    // Planning flotte 
    DASHBOARD_FLEET_PLANNING_READ: "PERMISSION_DASHBOARD_FLEET_PLANNING_READ",
    DASHBOARD_FLEET_PLANNING_CREATE: "PERMISSION_DASHBOARD_FLEET_PLANNING_CREATE",
    DASHBOARD_FLEET_PLANNING_UPDATE: "PERMISSION_DASHBOARD_FLEET_PLANNING_UPDATE",
    DASHBOARD_FLEET_PLANNING_SOFT_DELETE: "PERMISSION_DASHBOARD_FLEET_PLANNING_SOFT_DELETE",
    // Planning déplacement 
    DASHBOARD_TRAVEL_PLANNING_READ: "PERMISSION_DASHBOARD_TRAVEL_PLANNING_READ",
    DASHBOARD_TRAVEL_PLANNING_CREATE: "PERMISSION_DASHBOARD_TRAVEL_PLANNING_CREATE",
    DASHBOARD_TRAVEL_PLANNING_UPDATE: "PERMISSION_DASHBOARD_TRAVEL_PLANNING_UPDATE",
    DASHBOARD_TRAVEL_PLANNING_SOFT_DELETE: "PERMISSION_DASHBOARD_TRAVEL_PLANNING_SOFT_DELETE",
    // Déclaration des temps CA 
    DASHBOARD_CA_TIME_STATEMENT_READ: "PERMISSION_DASHBOARD_CA_TIME_STATEMENT_READ",
    DASHBOARD_CA_TIME_STATEMENT_CREATE: "PERMISSION_DASHBOARD_CA_TIME_STATEMENT_CREATE",
    DASHBOARD_CA_TIME_STATEMENT_UPDATE: "PERMISSION_DASHBOARD_CA_TIME_STATEMENT_UPDATE",
    DASHBOARD_CA_TIME_STATEMENT_SOFT_DELETE: "PERMISSION_DASHBOARD_CA_TIME_STATEMENT_SOFT_DELETE",
    // Actualités 
    DASHBOARD_NEWS_READ: "PERMISSION_DASHBOARD_NEWS_READ",
    DASHBOARD_NEWS_CREATE: "PERMISSION_DASHBOARD_NEWS_CREATE",
    DASHBOARD_NEWS_UPDATE: "PERMISSION_DASHBOARD_NEWS_UPDATE",
    DASHBOARD_NEWS_SOFT_DELETE: "PERMISSION_DASHBOARD_NEWS_SOFT_DELETE",
    // Traiteur 
    DASHBOARD_CATERER_READ: "PERMISSION_DASHBOARD_CATERER_READ",
    DASHBOARD_CATERER_CREATE: "PERMISSION_DASHBOARD_CATERER_CREATE",
    DASHBOARD_CATERER_UPDATE: "PERMISSION_DASHBOARD_CATERER_UPDATE",
    DASHBOARD_CATERER_SOFT_DELETE: "PERMISSION_DASHBOARD_CATERER_SOFT_DELETE",
    // Prime
    DASHBOARD_BONUS_READ: "PERMISSION_DASHBOARD_BONUS_READ",
    DASHBOARD_BONUS_CREATE: "PERMISSION_DASHBOARD_BONUS_CREATE",
    DASHBOARD_BONUS_UPDATE: "PERMISSION_DASHBOARD_BONUS_UPDATE",
    DASHBOARD_BONUS_SOFT_DELETE: "PERMISSION_DASHBOARD_BONUS_SOFT_DELETE",

    // :::::::::::::::::::::::::::::::::::::::::: All of Site ::::::::::::::::::::::::::::::::::::::::::
    // Dashboard
    SITE_DASHBOARD_READ: "PERMISSION_SITE_DASHBOARD_READ",
    SITE_DASHBOARD_CREATE: "PERMISSION_SITE_DASHBOARD_CREATE",
    SITE_DASHBOARD_UPDATE: "PERMISSION_SITE_DASHBOARD_UPDATE",
    SITE_DASHBOARD_SOFT_DELETE: "PERMISSION_SITE_DASHBOARD_SOFT_DELETE",
    // Répertoire des projets 
    SITE_DIRECTORY_OF_PROJECTS_READ: "PERMISSION_SITE_DIRECTORY_OF_PROJECTS_READ",
    SITE_DIRECTORY_OF_PROJECTS_CREATE: "PERMISSION_SITE_DIRECTORY_OF_PROJECTS_CREATE",
    SITE_DIRECTORY_OF_PROJECTS_UPDATE: "PERMISSION_SITE_DIRECTORY_OF_PROJECTS_UPDATE",
    SITE_DIRECTORY_OF_PROJECTS_SOFT_DELETE: "PERMISSION_SITE_DIRECTORY_OF_PROJECTS_SOFT_DELETE",
    // Répertoire des chantiers 
    SITE_DIRECTORY_OF_WORK_SITES_READ: "PERMISSION_SITE_DIRECTORY_OF_WORK_SITES_READ",
    SITE_DIRECTORY_OF_WORK_SITES_CREATE: "PERMISSION_SITE_DIRECTORY_OF_WORK_SITES_CREATE",
    SITE_DIRECTORY_OF_WORK_SITES_UPDATE: "PERMISSION_SITE_DIRECTORY_OF_WORK_SITES_UPDATE",
    SITE_DIRECTORY_OF_WORK_SITES_SOFT_DELETE: "PERMISSION_SITE_DIRECTORY_OF_WORK_SITES_SOFT_DELETE",
    // Planning des chantiers 
    SITE_PLANNING_OF_THE_SITES_READ: "PERMISSION_SITE_PLANNING_OF_THE_SITES_READ",
    SITE_PLANNING_OF_THE_SITES_CREATE: "PERMISSION_SITE_PLANNING_OF_THE_SITES_CREATE",
    SITE_PLANNING_OF_THE_SITES_UPDATE: "PERMISSION_SITE_PLANNING_OF_THE_SITES_UPDATE",
    SITE_PLANNING_OF_THE_SITES_SOFT_DELETE: "PERMISSION_SITE_PLANNING_OF_THE_SITES_SOFT_DELETE",
    // Carte des chantiers 
    SITE_MAP_OF_WORK_SITES_READ: "PERMISSION_SITE_MAP_OF_WORK_SITES_READ",
    SITE_MAP_OF_WORK_SITES_CREATE: "PERMISSION_SITE_MAP_OF_WORK_SITES_CREATE",
    SITE_MAP_OF_WORK_SITES_UPDATE: "PERMISSION_SITE_MAP_OF_WORK_SITES_UPDATE",
    SITE_MAP_OF_WORK_SITES_SOFT_DELETE: "PERMISSION_SITE_MAP_OF_WORK_SITES_SOFT_DELETE",
    // Programme des équipes 
    SITE_TEAM_PROGRAM_READ: "PERMISSION_SITE_TEAM_PROGRAM_READ",
    SITE_TEAM_PROGRAM_CREATE: "PERMISSION_SITE_TEAM_PROGRAM_CREATE",
    SITE_TEAM_PROGRAM_UPDATE: "PERMISSION_SITE_TEAM_PROGRAM_UPDATE",
    SITE_TEAM_PROGRAM_SOFT_DELETE: "PERMISSION_SITE_TEAM_PROGRAM_SOFT_DELETE",
    // Besoins en intérimaires 
    SITE_TEMPORARY_STAFFING_NEEDS_READ: "PERMISSION_SITE_TEMPORARY_STAFFING_NEEDS_READ",
    SITE_TEMPORARY_STAFFING_NEEDS_CREATE: "PERMISSION_SITE_TEMPORARY_STAFFING_NEEDS_CREATE",
    SITE_TEMPORARY_STAFFING_NEEDS_UPDATE: "PERMISSION_SITE_TEMPORARY_STAFFING_NEEDS_UPDATE",
    SITE_TEMPORARY_STAFFING_NEEDS_SOFT_DELETE: "PERMISSION_SITE_TEMPORARY_STAFFING_NEEDS_SOFT_DELETE",
    // Déclaration des recettes 
    SITE_REVENUE_REPORTING_READ: "PERMISSION_SITE_REVENUE_REPORTING_READ",
    SITE_REVENUE_REPORTING_CREATE: "PERMISSION_SITE_REVENUE_REPORTING_CREATE",
    SITE_REVENUE_REPORTING_UPDATE: "PERMISSION_SITE_REVENUE_REPORTING_UPDATE",
    SITE_REVENUE_REPORTING_SOFT_DELETE: "PERMISSION_SITE_REVENUE_REPORTING_SOFT_DELETE",
    // Approvisionnement 
    SITE_PROCUREMENT_READ: "PERMISSION_SITE_PROCUREMENT_READ",
    SITE_PROCUREMENT_CREATE: "PERMISSION_SITE_PROCUREMENT_CREATE",
    SITE_PROCUREMENT_UPDATE: "PERMISSION_SITE_PROCUREMENT_UPDATE",
    SITE_PROCUREMENT_SOFT_DELETE: "PERMISSION_SITE_PROCUREMENT_SOFT_DELETE",
    // Taux M.O
    SITE_RATES_MO_READ: "PERMISSION_SITE_RATES_MO_READ",
    SITE_RATES_MO_CREATE: "PERMISSION_SITE_RATES_MO_CREATE",
    SITE_RATES_MO_UPDATE: "PERMISSION_SITE_RATES_MO_UPDATE",
    SITE_RATES_MO_SOFT_DELETE: "PERMISSION_SITE_RATES_MO_SOFT_DELETE",
    // Sinistres chantier 
    SITE_CONSTRUCTION_SITE_CLAIMS_READ: "PERMISSION_SITE_CONSTRUCTION_SITE_CLAIMS_READ",
    SITE_CONSTRUCTION_SITE_CLAIMS_CREATE: "PERMISSION_SITE_CONSTRUCTION_SITE_CLAIMS_CREATE",
    SITE_CONSTRUCTION_SITE_CLAIMS_UPDATE: "PERMISSION_SITE_CONSTRUCTION_SITE_CLAIMS_UPDATE",
    SITE_CONSTRUCTION_SITE_CLAIMS_SOFT_DELETE: "PERMISSION_SITE_CONSTRUCTION_SITE_CLAIMS_SOFT_DELETE",
    // Equipe
    SITE_TEAM_READ: "PERMISSION_SITE_TEAM_READ",
    SITE_TEAM_CREATE: "PERMISSION_SITE_TEAM_CREATE",
    SITE_TEAM_UPDATE: "PERMISSION_SITE_TEAM_UPDATE",
    SITE_TEAM_SOFT_DELETE: "PERMISSION_SITE_TEAM_SOFT_DELETE",
    // Matériel 
    SITE_MATERIAL_READ: "PERMISSION_SITE_MATERIAL_READ",
    SITE_MATERIAL_CREATE: "PERMISSION_SITE_MATERIAL_CREATE",
    SITE_MATERIAL_UPDATE: "PERMISSION_SITE_MATERIAL_UPDATE",
    SITE_MATERIAL_SOFT_DELETE: "PERMISSION_SITE_MATERIAL_SOFT_DELETE",
    // Planning matériel 
    SITE_MATERIAL_PLANNING_READ: "PERMISSION_SITE_MATERIAL_PLANNING_READ",
    SITE_MATERIAL_PLANNING_CREATE: "PERMISSION_SITE_MATERIAL_PLANNING_CREATE",
    SITE_MATERIAL_PLANNING_UPDATE: "PERMISSION_SITE_MATERIAL_PLANNING_UPDATE",
    SITE_MATERIAL_PLANNING_SOFT_DELETE: "PERMISSION_SITE_MATERIAL_PLANNING_SOFT_DELETE",
    // Flotte 
    SITE_FLEET_READ: "PERMISSION_SITE_FLEET_READ",
    SITE_FLEET_CREATE: "PERMISSION_SITE_FLEET_CREATE",
    SITE_FLEET_UPDATE: "PERMISSION_SITE_FLEET_UPDATE",
    SITE_FLEET_SOFT_DELETE: "PERMISSION_SITE_FLEET_SOFT_DELETE",
    // Planning flotte 
    SITE_FLEET_PLANNING_READ: "PERMISSION_SITE_FLEET_PLANNING_READ",
    SITE_FLEET_PLANNING_CREATE: "PERMISSION_SITE_FLEET_PLANNING_CREATE",
    SITE_FLEET_PLANNING_UPDATE: "PERMISSION_SITE_FLEET_PLANNING_UPDATE",
    SITE_FLEET_PLANNING_SOFT_DELETE: "PERMISSION_SITE_FLEET_PLANNING_SOFT_DELETE",
    // Revue de contrat 
    SITE_CONTRACT_REVIEW_READ: "PERMISSION_SITE_CONTRACT_REVIEW_READ",
    SITE_CONTRACT_REVIEW_CREATE: "PERMISSION_SITE_CONTRACT_REVIEW_CREATE",
    SITE_CONTRACT_REVIEW_UPDATE: "PERMISSION_SITE_CONTRACT_REVIEW_UPDATE",
    SITE_CONTRACT_REVIEW_SOFT_DELETE: "PERMISSION_SITE_CONTRACT_REVIEW_SOFT_DELETE",

    // :::::::::::::::::::::::::::::::::::::::::: All of Gestion ::::::::::::::::::::::::::::::::::::::::::
    // Dashboard 
    MANAGEMENT_DASHBOARD_READ: "PERMISSION_MANAGEMENT_DASHBOARD_READ",
    MANAGEMENT_DASHBOARD_CREATE: "PERMISSION_MANAGEMENT_DASHBOARD_CREATE",
    MANAGEMENT_DASHBOARD_UPDATE: "PERMISSION_MANAGEMENT_DASHBOARD_UPDATE",
    MANAGEMENT_DASHBOARD_SOFT_DELETE: "PERMISSION_MANAGEMENT_DASHBOARD_SOFT_DELETE",

    // :::::::::::::::::::::::::::::::::::::::::: All of RH ::::::::::::::::::::::::::::::::::::::::::
    // Dashboard
    RH_DASHBOARD_READ: "PERMISSION_RH_DASHBOARD_READ",
    RH_DASHBOARD_CREATE: "PERMISSION_RH_DASHBOARD_CREATE",
    RH_DASHBOARD_UPDATE: "PERMISSION_RH_DASHBOARD_UPDATE",
    RH_DASHBOARD_SOFT_DELETE: "PERMISSION_RH_DASHBOARD_SOFT_DELETE",
    // Répertoire des employés 
    RH_EMPLOYEE_DIRECTORY_READ: "PERMISSION_RH_EMPLOYEE_DIRECTORY_READ",
    RH_EMPLOYEE_DIRECTORY_CREATE: "PERMISSION_RH_EMPLOYEE_DIRECTORY_CREATE",
    RH_EMPLOYEE_DIRECTORY_UPDATE: "PERMISSION_RH_EMPLOYEE_DIRECTORY_UPDATE",
    RH_EMPLOYEE_DIRECTORY_SOFT_DELETE: "PERMISSION_RH_EMPLOYEE_DIRECTORY_SOFT_DELETE",
    // Répertoire des candidats 
    RH_DIRECTORY_OF_CANDIDATES_READ: "PERMISSION_RH_DIRECTORY_OF_CANDIDATES_READ",
    RH_DIRECTORY_OF_CANDIDATES_CREATE: "PERMISSION_RH_DIRECTORY_OF_CANDIDATES_CREATE",
    RH_DIRECTORY_OF_CANDIDATES_UPDATE: "PERMISSION_RH_DIRECTORY_OF_CANDIDATES_UPDATE",
    RH_DIRECTORY_OF_CANDIDATES_SOFT_DELETE: "PERMISSION_RH_DIRECTORY_OF_CANDIDATES_SOFT_DELETE",
    // CVthèque
    RH_CV_TECH_READ: "PERMISSION_RH_CV_TECH_READ",
    RH_CV_TECH_CREATE: "PERMISSION_RH_CV_TECH_CREATE",
    RH_CV_TECH_UPDATE: "PERMISSION_RH_CV_TECH_UPDATE",
    RH_CV_TECH_SOFT_DELETE: "PERMISSION_RH_CV_TECH_SOFT_DELETE",
    // Congés / absences 
    RH_HOLIDAY_OR_ABSENCE_READ: "PERMISSION_RH_HOLIDAY_OR_ABSENCE_READ",
    RH_HOLIDAY_OR_ABSENCE_CREATE: "PERMISSION_RH_HOLIDAY_OR_ABSENCE_CREATE",
    RH_HOLIDAY_OR_ABSENCE_UPDATE: "PERMISSION_RH_HOLIDAY_OR_ABSENCE_UPDATE",
    RH_HOLIDAY_OR_ABSENCE_SOFT_DELETE: "PERMISSION_RH_HOLIDAY_OR_ABSENCE_SOFT_DELETE",
    // Temps
    RH_TIME_READ: "PERMISSION_RH_TIME_READ",
    RH_TIME_CREATE: "PERMISSION_RH_TIME_CREATE",
    RH_TIME_UPDATE: "PERMISSION_RH_TIME_UPDATE",
    RH_TIME_SOFT_DELETE: "PERMISSION_RH_TIME_SOFT_DELETE",
    // Paie 
    RH_PAYMENT_READ: "PERMISSION_RH_PAYMENT_READ",
    RH_PAYMENT_CREATE: "PERMISSION_RH_PAYMENT_CREATE",
    RH_PAYMENT_UPDATE: "PERMISSION_RH_PAYMENT_UPDATE",
    RH_PAYMENT_SOFT_DELETE: "PERMISSION_RH_PAYMENT_SOFT_DELETE",
    // Formation 
    RH_FORMATION_READ: "PERMISSION_RH_FORMATION_READ",
    RH_FORMATION_CREATE: "PERMISSION_RH_FORMATION_CREATE",
    RH_FORMATION_UPDATE: "PERMISSION_RH_FORMATION_UPDATE",
    RH_FORMATION_SOFT_DELETE: "PERMISSION_RH_FORMATION_SOFT_DELETE",
    // Qualification 
    RH_QUALIFICATION_READ: "PERMISSION_RH_QUALIFICATION_READ",
    RH_QUALIFICATION_CREATE: "PERMISSION_RH_QUALIFICATION_CREATE",
    RH_QUALIFICATION_UPDATE: "PERMISSION_RH_QUALIFICATION_UPDATE",
    RH_QUALIFICATION_SOFT_DELETE: "PERMISSION_RH_QUALIFICATION_SOFT_DELETE",
    // Onboarding 
    RH_ONBOARDING_READ: "PERMISSION_RH_ONBOARDING_READ",
    RH_ONBOARDING_CREATE: "PERMISSION_RH_ONBOARDING_CREATE",
    RH_ONBOARDING_UPDATE: "PERMISSION_RH_ONBOARDING_UPDATE",
    RH_ONBOARDING_SOFT_DELETE: "PERMISSION_RH_ONBOARDING_SOFT_DELETE",
    // Enquête 
    RH_SURVEY_READ: "PERMISSION_RH_SURVEY_READ",
    RH_SURVEY_CREATE: "PERMISSION_RH_SURVEY_CREATE",
    RH_SURVEY_UPDATE: "PERMISSION_RH_SURVEY_UPDATE",
    RH_SURVEY_SOFT_DELETE: "PERMISSION_RH_SURVEY_SOFT_DELETE",
    // Fiche de poste 
    RH_JOB_DESCRIPTION_READ: "PERMISSION_RH_JOB_DESCRIPTION_READ",
    RH_JOB_DESCRIPTION_CREATE: "PERMISSION_RH_JOB_DESCRIPTION_CREATE",
    RH_JOB_DESCRIPTION_UPDATE: "PERMISSION_RH_JOB_DESCRIPTION_UPDATE",
    RH_JOB_DESCRIPTION_SOFT_DELETE: "PERMISSION_RH_JOB_DESCRIPTION_SOFT_DELETE",
    // Visites médicales 
    RH_MEDICAL_VISITS_READ: "PERMISSION_RH_MEDICAL_VISITS_READ",
    RH_MEDICAL_VISITS_CREATE: "PERMISSION_RH_MEDICAL_VISITS_CREATE",
    RH_MEDICAL_VISITS_UPDATE: "PERMISSION_RH_MEDICAL_VISITS_UPDATE",
    RH_MEDICAL_VISITS_SOFT_DELETE: "PERMISSION_RH_MEDICAL_VISITS_SOFT_DELETE",
    // Entretiens 
    RH_INTERVIEWS_READ: "PERMISSION_RH_INTERVIEWS_READ",
    RH_INTERVIEWS_CREATE: "PERMISSION_RH_INTERVIEWS_CREATE",
    RH_INTERVIEWS_UPDATE: "PERMISSION_RH_INTERVIEWS_UPDATE",
    RH_INTERVIEWS_SOFT_DELETE: "PERMISSION_RH_INTERVIEWS_SOFT_DELETE",
    // Journal de présence 
    RH_ATTENDANCE_LOG_READ: "PERMISSION_RH_ATTENDANCE_LOG_READ",
    RH_ATTENDANCE_LOG_CREATE: "PERMISSION_RH_ATTENDANCE_LOG_CREATE",
    RH_ATTENDANCE_LOG_UPDATE: "PERMISSION_RH_ATTENDANCE_LOG_UPDATE",
    RH_ATTENDANCE_LOG_SOFT_DELETE: "PERMISSION_RH_ATTENDANCE_LOG_SOFT_DELETE",
    // Grand déplacement 
    RH_BIG_MOVE_READ: "PERMISSION_RH_BIG_MOVE_READ",
    RH_BIG_MOVE_CREATE: "PERMISSION_RH_BIG_MOVE_CREATE",
    RH_BIG_MOVE_UPDATE: "PERMISSION_RH_BIG_MOVE_UPDATE",
    RH_BIG_MOVE_SOFT_DELETE: "PERMISSION_RH_BIG_MOVE_SOFT_DELETE",

    // :::::::::::::::::::::::::::::::::::::::::: All of Achat ::::::::::::::::::::::::::::::::::::::::::
    // Dashboard 
    PURCHASE_DASHBOARD_READ: "PERMISSION_PURCHASE_DASHBOARD_READ",
    PURCHASE_DASHBOARD_CREATE: "PERMISSION_PURCHASE_DASHBOARD_CREATE",
    PURCHASE_DASHBOARD_UPDATE: "PERMISSION_PURCHASE_DASHBOARD_UPDATE",
    PURCHASE_DASHBOARD_SOFT_DELETE: "PERMISSION_PURCHASE_DASHBOARD_SOFT_DELETE",
    // Fournisseurs 
    PURCHASE_SUPPLIERS_READ: "PERMISSION_PURCHASE_SUPPLIERS_READ",
    PURCHASE_SUPPLIERS_CREATE: "PERMISSION_PURCHASE_SUPPLIERS_CREATE",
    PURCHASE_SUPPLIERS_UPDATE: "PERMISSION_PURCHASE_SUPPLIERS_UPDATE",
    PURCHASE_SUPPLIERS_SOFT_DELETE: "PERMISSION_PURCHASE_SUPPLIERS_SOFT_DELETE",
    // Répertoire des articles 
    PURCHASE_DIRECTORY_OF_ARTICLES_READ: "PERMISSION_PURCHASE_DIRECTORY_OF_ARTICLES_READ",
    PURCHASE_DIRECTORY_OF_ARTICLES_CREATE: "PERMISSION_PURCHASE_DIRECTORY_OF_ARTICLES_CREATE",
    PURCHASE_DIRECTORY_OF_ARTICLES_UPDATE: "PERMISSION_PURCHASE_DIRECTORY_OF_ARTICLES_UPDATE",
    PURCHASE_DIRECTORY_OF_ARTICLES_SOFT_DELETE: "PERMISSION_PURCHASE_DIRECTORY_OF_ARTICLES_SOFT_DELETE",
    // Demandes d'achat 
    PURCHASE_PURCHASE_REQUESTS_READ: "PERMISSION_PURCHASE_PURCHASE_REQUESTS_READ",
    PURCHASE_PURCHASE_REQUESTS_CREATE: "PERMISSION_PURCHASE_PURCHASE_REQUESTS_CREATE",
    PURCHASE_PURCHASE_REQUESTS_UPDATE: "PERMISSION_PURCHASE_PURCHASE_REQUESTS_UPDATE",
    PURCHASE_PURCHASE_REQUESTS_SOFT_DELETE: "PERMISSION_PURCHASE_PURCHASE_REQUESTS_SOFT_DELETE",
    // Commandes 
    PURCHASE_ORDERS_READ: "PERMISSION_PURCHASE_ORDERS_READ",
    PURCHASE_ORDERS_CREATE: "PERMISSION_PURCHASE_ORDERS_CREATE",
    PURCHASE_ORDERS_UPDATE: "PERMISSION_PURCHASE_ORDERS_UPDATE",
    PURCHASE_ORDERS_SOFT_DELETE: "PERMISSION_PURCHASE_ORDERS_SOFT_DELETE",
    // Bons de livraison 
    PURCHASE_DELIVERY_NOTES_READ: "PERMISSION_PURCHASE_DELIVERY_NOTES_READ",
    PURCHASE_DELIVERY_NOTES_CREATE: "PERMISSION_PURCHASE_DELIVERY_NOTES_CREATE",
    PURCHASE_DELIVERY_NOTES_UPDATE: "PERMISSION_PURCHASE_DELIVERY_NOTES_UPDATE",
    PURCHASE_DELIVERY_NOTES_SOFT_DELETE: "PERMISSION_PURCHASE_DELIVERY_NOTES_SOFT_DELETE",
    // Factures 
    PURCHASE_INVOICES_READ: "PERMISSION_PURCHASE_INVOICES_READ",
    PURCHASE_INVOICES_CREATE: "PERMISSION_PURCHASE_INVOICES_CREATE",
    PURCHASE_INVOICES_UPDATE: "PERMISSION_PURCHASE_INVOICES_UPDATE",
    PURCHASE_INVOICES_SOFT_DELETE: "PERMISSION_PURCHASE_INVOICES_SOFT_DELETE",
    // Travaux sous-traitance 
    PURCHASE_SUBCONTRACTING_WORK_READ: "PERMISSION_PURCHASE_SUBCONTRACTING_WORK_READ",
    PURCHASE_SUBCONTRACTING_WORK_CREATE: "PERMISSION_PURCHASE_SUBCONTRACTING_WORK_CREATE",
    PURCHASE_SUBCONTRACTING_WORK_UPDATE: "PERMISSION_PURCHASE_SUBCONTRACTING_WORK_UPDATE",
    PURCHASE_SUBCONTRACTING_WORK_SOFT_DELETE: "PERMISSION_PURCHASE_SUBCONTRACTING_WORK_SOFT_DELETE",
    // Punch out 
    PURCHASE_PUNCH_OUT_WORK_READ: "PERMISSION_PURCHASE_PUNCH_OUT_WORK_READ",
    PURCHASE_PUNCH_OUT_WORK_CREATE: "PERMISSION_PURCHASE_PUNCH_OUT_WORK_CREATE",
    PURCHASE_PUNCH_OUT_WORK_UPDATE: "PERMISSION_PURCHASE_PUNCH_OUT_WORK_UPDATE",
    PURCHASE_PUNCH_OUT_WORK_SOFT_DELETE: "PERMISSION_PURCHASE_PUNCH_OUT_WORK_SOFT_DELETE",
    // Tableaux de suivi 
    PURCHASE_FOLLOW_UP_TABLES_READ: "PERMISSION_PURCHASE_FOLLOW_UP_TABLES_READ",
    PURCHASE_FOLLOW_UP_TABLES_CREATE: "PERMISSION_PURCHASE_FOLLOW_UP_TABLES_CREATE",
    PURCHASE_FOLLOW_UP_TABLES_UPDATE: "PERMISSION_PURCHASE_FOLLOW_UP_TABLES_UPDATE",
    PURCHASE_FOLLOW_UP_TABLES_SOFT_DELETE: "PERMISSION_PURCHASE_FOLLOW_UP_TABLES_SOFT_DELETE",
    // Catalogues 
    PURCHASE_CATALOGS_READ: "PERMISSION_PURCHASE_CATALOGS_READ",
    PURCHASE_CATALOGS_CREATE: "PERMISSION_PURCHASE_CATALOGS_CREATE",
    PURCHASE_CATALOGS_UPDATE: "PERMISSION_PURCHASE_CATALOGS_UPDATE",
    PURCHASE_CATALOGS_SOFT_DELETE: "PERMISSION_PURCHASE_CATALOGS_SOFT_DELETE",

    // :::::::::::::::::::::::::::::::::::::::::: All of Facturation ::::::::::::::::::::::::::::::::::::::::::
    // Dashboard 
    BILLING_DASHBOARD_READ: "PERMISSION_BILLING_DASHBOARD_READ",
    BILLING_DASHBOARD_CREATE: "PERMISSION_BILLING_DASHBOARD_CREATE",
    BILLING_DASHBOARD_UPDATE: "PERMISSION_BILLING_DASHBOARD_UPDATE",
    BILLING_DASHBOARD_SOFT_DELETE: "PERMISSION_BILLING_DASHBOARD_SOFT_DELETE",
    // Répertoire clients 
    BILLING_CUSTOMER_DIRECTORY_READ: "PERMISSION_BILLING_CUSTOMER_DIRECTORY_READ",
    BILLING_CUSTOMER_DIRECTORY_CREATE: "PERMISSION_BILLING_CUSTOMER_DIRECTORY_CREATE",
    BILLING_CUSTOMER_DIRECTORY_UPDATE: "PERMISSION_BILLING_CUSTOMER_DIRECTORY_UPDATE",
    BILLING_CUSTOMER_DIRECTORY_SOFT_DELETE: "PERMISSION_BILLING_CUSTOMER_DIRECTORY_SOFT_DELETE",
    // Devis / AO 
    BILLING_QUOTATION_OR_AO_READ: "PERMISSION_BILLING_QUOTATION_OR_AO_READ",
    BILLING_QUOTATION_OR_AO_CREATE: "PERMISSION_BILLING_QUOTATION_OR_AO_CREATE",
    BILLING_QUOTATION_OR_AO_UPDATE: "PERMISSION_BILLING_QUOTATION_OR_AO_UPDATE",
    BILLING_QUOTATION_OR_AO_SOFT_DELETE: "PERMISSION_BILLING_QUOTATION_OR_AO_SOFT_DELETE",
    // Attachements 
    BILLING_ATTACHMENTS_READ: "PERMISSION_BILLING_ATTACHMENTS_READ",
    BILLING_ATTACHMENTS_CREATE: "PERMISSION_BILLING_ATTACHMENTS_CREATE",
    BILLING_ATTACHMENTS_UPDATE: "PERMISSION_BILLING_ATTACHMENTS_UPDATE",
    BILLING_ATTACHMENTS_SOFT_DELETE: "PERMISSION_BILLING_ATTACHMENTS_SOFT_DELETE",
    // Commandes 
    BILLING_ORDERS_READ: "PERMISSION_BILLING_ORDERS_READ",
    BILLING_ORDERS_CREATE: "PERMISSION_BILLING_ORDERS_CREATE",
    BILLING_ORDERS_UPDATE: "PERMISSION_BILLING_ORDERS_UPDATE",
    BILLING_ORDERS_SOFT_DELETE: "PERMISSION_BILLING_ORDERS_SOFT_DELETE",
    // Facturation client 
    BILLING_CUSTOMER_BILLING_READ: "PERMISSION_BILLING_CUSTOMER_BILLING_READ",
    BILLING_CUSTOMER_BILLING_CREATE: "PERMISSION_BILLING_CUSTOMER_BILLING_CREATE",
    BILLING_CUSTOMER_BILLING_UPDATE: "PERMISSION_BILLING_CUSTOMER_BILLING_UPDATE",
    BILLING_CUSTOMER_BILLING_SOFT_DELETE: "PERMISSION_BILLING_CUSTOMER_BILLING_SOFT_DELETE",
    // Recouvrement / Relance 
    BILLING_RECOVERY_OR_DUNNING_READ: "PERMISSION_BILLING_RECOVERY_OR_DUNNING_READ",
    BILLING_RECOVERY_OR_DUNNING_CREATE: "PERMISSION_BILLING_RECOVERY_OR_DUNNING_CREATE",
    BILLING_RECOVERY_OR_DUNNING_UPDATE: "PERMISSION_BILLING_RECOVERY_OR_DUNNING_UPDATE",
    BILLING_RECOVERY_OR_DUNNING_SOFT_DELETE: "PERMISSION_BILLING_RECOVERY_OR_DUNNING_SOFT_DELETE",
    // Facturation sous-traitants 
    BILLING_SUBCONTRACTOR_BILLING_READ: "PERMISSION_BILLING_SUBCONTRACTOR_BILLING_READ",
    BILLING_SUBCONTRACTOR_BILLING_CREATE: "PERMISSION_BILLING_SUBCONTRACTOR_BILLING_CREATE",
    BILLING_SUBCONTRACTOR_BILLING_UPDATE: "PERMISSION_BILLING_SUBCONTRACTOR_BILLING_UPDATE",
    BILLING_SUBCONTRACTOR_BILLING_SOFT_DELETE: "PERMISSION_BILLING_SUBCONTRACTOR_BILLING_SOFT_DELETE",
    // Paiement direct sous-traitants 
    BILLING_DIRECT_PAYMENT_TO_SUBCONTRACTORS_READ: "PERMISSION_BILLING_DIRECT_PAYMENT_TO_SUBCONTRACTORS_READ",
    BILLING_DIRECT_PAYMENT_TO_SUBCONTRACTORS_CREATE: "PERMISSION_BILLING_DIRECT_PAYMENT_TO_SUBCONTRACTORS_CREATE",
    BILLING_DIRECT_PAYMENT_TO_SUBCONTRACTORS_UPDATE: "PERMISSION_BILLING_DIRECT_PAYMENT_TO_SUBCONTRACTORS_UPDATE",
    BILLING_DIRECT_PAYMENT_TO_SUBCONTRACTORS_SOFT_DELETE: "PERMISSION_BILLING_DIRECT_PAYMENT_TO_SUBCONTRACTORS_SOFT_DELETE",
    // Facturation co-traitants 
    BILLING_CO_CONTRACTOR_INVOICING_READ: "PERMISSION_BILLING_CO_CONTRACTOR_INVOICING_READ",
    BILLING_CO_CONTRACTOR_INVOICING_CREATE: "PERMISSION_BILLING_CO_CONTRACTOR_INVOICING_CREATE",
    BILLING_CO_CONTRACTOR_INVOICING_UPDATE: "PERMISSION_BILLING_CO_CONTRACTOR_INVOICING_UPDATE",
    BILLING_CO_CONTRACTOR_INVOICING_SOFT_DELETE: "PERMISSION_BILLING_CO_CONTRACTOR_INVOICING_SOFT_DELETE",
    // Comptabilisation 
    BILLING_ACCOUNTING_READ: "PERMISSION_BILLING_ACCOUNTING_READ",
    BILLING_ACCOUNTING_CREATE: "PERMISSION_BILLING_ACCOUNTING_CREATE",
    BILLING_ACCOUNTING_UPDATE: "PERMISSION_BILLING_ACCOUNTING_UPDATE",
    BILLING_ACCOUNTING_SOFT_DELETE: "PERMISSION_BILLING_ACCOUNTING_SOFT_DELETE",
    // Suivi retenues de garanties 
    BILLING_FOLLOW_UP_OF_HOLDBACKS_READ: "PERMISSION_BILLING_FOLLOW_UP_OF_HOLDBACKS_READ",
    BILLING_FOLLOW_UP_OF_HOLDBACKS_CREATE: "PERMISSION_BILLING_FOLLOW_UP_OF_HOLDBACKS_CREATE",
    BILLING_FOLLOW_UP_OF_HOLDBACKS_UPDATE: "PERMISSION_BILLING_FOLLOW_UP_OF_HOLDBACKS_UPDATE",
    BILLING_FOLLOW_UP_OF_HOLDBACKS_SOFT_DELETE: "PERMISSION_BILLING_FOLLOW_UP_OF_HOLDBACKS_SOFT_DELETE",
    // Etats d'avancement 
    BILLING_PROGRESS_REPORTS_READ: "PERMISSION_BILLING_PROGRESS_REPORTS_READ",
    BILLING_PROGRESS_REPORTS_CREATE: "PERMISSION_BILLING_PROGRESS_REPORTS_CREATE",
    BILLING_PROGRESS_REPORTS_UPDATE: "PERMISSION_BILLING_PROGRESS_REPORTS_UPDATE",
    BILLING_PROGRESS_REPORTS_SOFT_DELETE: "PERMISSION_BILLING_PROGRESS_REPORTS_SOFT_DELETE",
    // Factures cédées en banque 
    BILLING_INVOICES_TRANSFERRED_TO_THE_BANK_READ: "PERMISSION_BILLING_INVOICES_TRANSFERRED_TO_THE_BANK_READ",
    BILLING_INVOICES_TRANSFERRED_TO_THE_BANK_CREATE: "PERMISSION_BILLING_INVOICES_TRANSFERRED_TO_THE_BANK_CREATE",
    BILLING_INVOICES_TRANSFERRED_TO_THE_BANK_UPDATE: "PERMISSION_BILLING_INVOICES_TRANSFERRED_TO_THE_BANK_UPDATE",
    BILLING_INVOICES_TRANSFERRED_TO_THE_BANK_SOFT_DELETE: "PERMISSION_BILLING_INVOICES_TRANSFERRED_TO_THE_BANK_SOFT_DELETE",

    // :::::::::::::::::::::::::::::::::::::::::: All of Parc matériel ::::::::::::::::::::::::::::::::::::::::::
    // Dashboard 
    MATERIAL_PARK_DASHBOARD_READ: "PERMISSION_MATERIAL_PARK_DASHBOARD_READ",
    MATERIAL_PARK_DASHBOARD_CREATE: "PERMISSION_MATERIAL_PARK_DASHBOARD_CREATE",
    MATERIAL_PARK_DASHBOARD_UPDATE: "PERMISSION_MATERIAL_PARK_DASHBOARD_UPDATE",
    MATERIAL_PARK_DASHBOARD_SOFT_DELETE: "PERMISSION_MATERIAL_PARK_DASHBOARD_SOFT_DELETE",
    // Magasin 
    MATERIAL_PARK_STORE_READ: "PERMISSION_MATERIAL_STORE_READ",
    MATERIAL_PARK_STORE_CREATE: "PERMISSION_MATERIAL_STORE_CREATE",
    MATERIAL_PARK_STORE_UPDATE: "PERMISSION_MATERIAL_STORE_UPDATE",
    MATERIAL_PARK_STORE_SOFT_DELETE: "PERMISSION_MATERIAL_STORE_SOFT_DELETE",
    // Fournisseurs
    MATERIAL_PARK_SUPPLIERS_READ: "PERMISSION_MATERIAL_SUPPLIERS_READ",
    MATERIAL_PARK_SUPPLIERS_CREATE: "PERMISSION_MATERIAL_SUPPLIERS_CREATE",
    MATERIAL_PARK_SUPPLIERS_UPDATE: "PERMISSION_MATERIAL_SUPPLIERS_UPDATE",
    MATERIAL_PARK_SUPPLIERS_SOFT_DELETE: "PERMISSION_MATERIAL_SUPPLIERS_SOFT_DELETE",
    // Matériel 
    MATERIAL_PARK_MATERIAL_READ: "PERMISSION_MATERIAL_MATERIAL_READ",
    MATERIAL_PARK_MATERIAL_CREATE: "PERMISSION_MATERIAL_MATERIAL_CREATE",
    MATERIAL_PARK_MATERIAL_UPDATE: "PERMISSION_MATERIAL_MATERIAL_UPDATE",
    MATERIAL_PARK_MATERIAL_SOFT_DELETE: "PERMISSION_MATERIAL_MATERIAL_SOFT_DELETE",
    // Flotte 
    MATERIAL_PARK_FLEET_READ: "PERMISSION_MATERIAL_FLEET_READ",
    MATERIAL_PARK_FLEET_CREATE: "PERMISSION_MATERIAL_FLEET_CREATE",
    MATERIAL_PARK_FLEET_UPDATE: "PERMISSION_MATERIAL_FLEET_UPDATE",
    MATERIAL_PARK_FLEET_SOFT_DELETE: "PERMISSION_MATERIAL_FLEET_SOFT_DELETE",
    // Engin 
    MATERIAL_PARK_MACHINE_READ: "PERMISSION_MATERIAL_MACHINE_READ",
    MATERIAL_PARK_MACHINE_CREATE: "PERMISSION_MATERIAL_MACHINE_CREATE",
    MATERIAL_PARK_MACHINE_UPDATE: "PERMISSION_MATERIAL_MACHINE_UPDATE",
    MATERIAL_PARK_MACHINE_SOFT_DELETE: "PERMISSION_MATERIAL_MACHINE_SOFT_DELETE",
    // Petit matériel 
    MATERIAL_PARK_SMALL_EQUIPMENT_READ: "PERMISSION_MATERIAL_SMALL_EQUIPMENT_READ",
    MATERIAL_PARK_SMALL_EQUIPMENT_CREATE: "PERMISSION_MATERIAL_SMALL_EQUIPMENT_CREATE",
    MATERIAL_PARK_SMALL_EQUIPMENT_UPDATE: "PERMISSION_MATERIAL_SMALL_EQUIPMENT_UPDATE",
    MATERIAL_PARK_SMALL_EQUIPMENT_SOFT_DELETE: "PERMISSION_MATERIAL_SMALL_EQUIPMENT_SOFT_DELETE",
    // Planning matériel 
    MATERIAL_PARK_MATERIAL_PLANNING_READ: "PERMISSION_MATERIAL_MATERIAL_PLANNING_READ",
    MATERIAL_PARK_MATERIAL_PLANNING_CREATE: "PERMISSION_MATERIAL_MATERIAL_PLANNING_CREATE",
    MATERIAL_PARK_MATERIAL_PLANNING_UPDATE: "PERMISSION_MATERIAL_MATERIAL_PLANNING_UPDATE",
    MATERIAL_PARK_MATERIAL_PLANNING_SOFT_DELETE: "PERMISSION_MATERIAL_MATERIAL_PLANNING_SOFT_DELETE",
    // Maintenance 
    MATERIAL_PARK_MAINTENANCE_READ: "PERMISSION_MATERIAL_MAINTENANCE_READ",
    MATERIAL_PARK_MAINTENANCE_CREATE: "PERMISSION_MATERIAL_MAINTENANCE_CREATE",
    MATERIAL_PARK_MAINTENANCE_UPDATE: "PERMISSION_MATERIAL_MAINTENANCE_UPDATE",
    MATERIAL_PARK_MAINTENANCE_SOFT_DELETE: "PERMISSION_MATERIAL_MAINTENANCE_SOFT_DELETE",
    // Planning mécanique 
    MATERIAL_PARK_MECHANICAL_PLANNING_READ: "PERMISSION_MATERIAL_MECHANICAL_PLANNING_READ",
    MATERIAL_PARK_MECHANICAL_PLANNING_CREATE: "PERMISSION_MATERIAL_MECHANICAL_PLANNING_CREATE",
    MATERIAL_PARK_MECHANICAL_PLANNING_UPDATE: "PERMISSION_MATERIAL_MECHANICAL_PLANNING_UPDATE",
    MATERIAL_PARK_MECHANICAL_PLANNING_SOFT_DELETE: "PERMISSION_MATERIAL_MECHANICAL_PLANNING_SOFT_DELETE",
    // Carburant 
    MATERIAL_PARK_FUEL_READ: "PERMISSION_MATERIAL_FUEL_READ",
    MATERIAL_PARK_FUEL_CREATE: "PERMISSION_MATERIAL_FUEL_CREATE",
    MATERIAL_PARK_FUEL_UPDATE: "PERMISSION_MATERIAL_FUEL_UPDATE",
    MATERIAL_PARK_FUEL_SOFT_DELETE: "PERMISSION_MATERIAL_FUEL_SOFT_DELETE",
    // Approvisionnement 
    MATERIAL_PARK_PROCUREMENT_READ: "PERMISSION_MATERIAL_PROCUREMENT_READ",
    MATERIAL_PARK_PROCUREMENT_CREATE: "PERMISSION_MATERIAL_PROCUREMENT_CREATE",
    MATERIAL_PARK_PROCUREMENT_UPDATE: "PERMISSION_MATERIAL_PROCUREMENT_UPDATE",
    MATERIAL_PARK_PROCUREMENT_SOFT_DELETE: "PERMISSION_MATERIAL_PROCUREMENT_SOFT_DELETE",
    // Location 
    MATERIAL_PARK_RENTAL_READ: "PERMISSION_MATERIAL_RENTAL_READ",
    MATERIAL_PARK_RENTAL_CREATE: "PERMISSION_MATERIAL_RENTAL_CREATE",
    MATERIAL_PARK_RENTAL_UPDATE: "PERMISSION_MATERIAL_RENTAL_UPDATE",
    MATERIAL_PARK_RENTAL_SOFT_DELETE: "PERMISSION_MATERIAL_RENTAL_SOFT_DELETE",
    // Sinistres 
    MATERIAL_PARK_CLAIMS_READ: "PERMISSION_MATERIAL_CLAIMS_READ",
    MATERIAL_PARK_CLAIMS_CREATE: "PERMISSION_MATERIAL_CLAIMS_CREATE",
    MATERIAL_PARK_CLAIMS_UPDATE: "PERMISSION_MATERIAL_CLAIMS_UPDATE",
    MATERIAL_PARK_CLAIMS_SOFT_DELETE: "PERMISSION_MATERIAL_CLAIMS_SOFT_DELETE",
    // Amende 
    MATERIAL_PARK_PENALTY_READ: "PERMISSION_MATERIAL_PENALTY_READ",
    MATERIAL_PARK_PENALTY_CREATE: "PERMISSION_MATERIAL_PENALTY_CREATE",
    MATERIAL_PARK_PENALTY_UPDATE: "PERMISSION_MATERIAL_PENALTY_UPDATE",
    MATERIAL_PARK_PENALTY_SOFT_DELETE: "PERMISSION_MATERIAL_PENALTY_SOFT_DELETE",
    // Refacturation parc 
    MATERIAL_PARK_RE_BILLING_OF_THE_PARK_READ: "PERMISSION_MATERIAL_RE_BILLING_OF_THE_PARK_READ",
    MATERIAL_PARK_RE_BILLING_OF_THE_PARK_CREATE: "PERMISSION_MATERIAL_RE_BILLING_OF_THE_PARK_CREATE",
    MATERIAL_PARK_RE_BILLING_OF_THE_PARK_UPDATE: "PERMISSION_MATERIAL_RE_BILLING_OF_THE_PARK_UPDATE",
    MATERIAL_PARK_RE_BILLING_OF_THE_PARK_SOFT_DELETE: "PERMISSION_MATERIAL_RE_BILLING_OF_THE_PARK_SOFT_DELETE",
    // Taux matériel 
    MATERIAL_PARK_MATERIAL_RATE_READ: "PERMISSION_MATERIAL_MATERIAL_RATE_READ",
    MATERIAL_PARK_MATERIAL_RATE_CREATE: "PERMISSION_MATERIAL_MATERIAL_RATE_CREATE",
    MATERIAL_PARK_MATERIAL_RATE_UPDATE: "PERMISSION_MATERIAL_MATERIAL_RATE_UPDATE",
    MATERIAL_PARK_MATERIAL_RATE_SOFT_DELETE: "PERMISSION_MATERIAL_MATERIAL_RATE_SOFT_DELETE",

    // :::::::::::::::::::::::::::::::::::::::::: All of QSE ::::::::::::::::::::::::::::::::::::::::::
    // Dashboard
    QSE_DASHBOARD_READ: "PERMISSION_QSE_DASHBOARD_READ",
    QSE_DASHBOARD_CREATE: "PERMISSION_QSE_DASHBOARD_CREATE",
    QSE_DASHBOARD_UPDATE: "PERMISSION_QSE_DASHBOARD_UPDATE",
    QSE_DASHBOARD_SOFT_DELETE: "PERMISSION_QSE_DASHBOARD_SOFT_DELETE",
    // Audits 
    QSE_AUDITS_READ: "PERMISSION_QSE_AUDITS_READ",
    QSE_AUDITS_CREATE: "PERMISSION_QSE_AUDITS_CREATE",
    QSE_AUDITS_UPDATE: "PERMISSION_QSE_AUDITS_UPDATE",
    QSE_AUDITS_SOFT_DELETE: "PERMISSION_QSE_AUDITS_SOFT_DELETE",
    // Remontées d'informations 
    QSE_INFORMATION_FEEDBACK_READ: "PERMISSION_QSE_INFORMATION_FEEDBACK_READ",
    QSE_INFORMATION_FEEDBACK_CREATE: "PERMISSION_QSE_INFORMATION_FEEDBACK_CREATE",
    QSE_INFORMATION_FEEDBACK_UPDATE: "PERMISSION_QSE_INFORMATION_FEEDBACK_UPDATE",
    QSE_INFORMATION_FEEDBACK_SOFT_DELETE: "PERMISSION_QSE_INFORMATION_FEEDBACK_SOFT_DELETE",
    // Satisfaction client 
    QSE_CUSTOMER_SATISFACTION_READ: "PERMISSION_QSE_CUSTOMER_SATISFACTION_READ",
    QSE_CUSTOMER_SATISFACTION_CREATE: "PERMISSION_QSE_CUSTOMER_SATISFACTION_CREATE",
    QSE_CUSTOMER_SATISFACTION_UPDATE: "PERMISSION_QSE_CUSTOMER_SATISFACTION_UPDATE",
    QSE_CUSTOMER_SATISFACTION_SOFT_DELETE: "PERMISSION_QSE_CUSTOMER_SATISFACTION_SOFT_DELETE",
    // Contrôles règlementaires 
    QSE_REGULATORY_CONTROLS_READ: "PERMISSION_QSE_REGULATORY_CONTROLS_READ",
    QSE_REGULATORY_CONTROLS_CREATE: "PERMISSION_QSE_REGULATORY_CONTROLS_CREATE",
    QSE_REGULATORY_CONTROLS_UPDATE: "PERMISSION_QSE_REGULATORY_CONTROLS_UPDATE",
    QSE_REGULATORY_CONTROLS_SOFT_DELETE: "PERMISSION_QSE_REGULATORY_CONTROLS_SOFT_DELETE",
    // Evaluation des risques 
    QSE_RISK_ASSESSMENT_READ: "PERMISSION_QSE_RISK_ASSESSMENT_READ",
    QSE_RISK_ASSESSMENT_CREATE: "PERMISSION_QSE_RISK_ASSESSMENT_CREATE",
    QSE_RISK_ASSESSMENT_UPDATE: "PERMISSION_QSE_RISK_ASSESSMENT_UPDATE",
    QSE_RISK_ASSESSMENT_SOFT_DELETE: "PERMISSION_QSE_RISK_ASSESSMENT_SOFT_DELETE",
    // 1/4 sécurité 
    QSE_SECURITY_SHIFT_READ: "PERMISSION_QSE_SECURITY_SHIFT_READ",
    QSE_SECURITY_SHIFT_CREATE: "PERMISSION_QSE_SECURITY_SHIFT_CREATE",
    QSE_SECURITY_SHIFT_UPDATE: "PERMISSION_QSE_SECURITY_SHIFT_UPDATE",
    QSE_SECURITY_SHIFT_SOFT_DELETE: "PERMISSION_QSE_SECURITY_SHIFT_SOFT_DELETE",
    // Levage 
    QSE_LIFTING_READ: "PERMISSION_QSE_LIFTING_READ",
    QSE_LIFTING_CREATE: "PERMISSION_QSE_LIFTING_CREATE",
    QSE_LIFTING_UPDATE: "PERMISSION_QSE_LIFTING_UPDATE",
    QSE_LIFTING_SOFT_DELETE: "PERMISSION_QSE_LIFTING_SOFT_DELETE",
    // HSE
    QSE_HSE_READ: "PERMISSION_QSE_HSE_READ",
    QSE_HSE_CREATE: "PERMISSION_QSE_HSE_CREATE",
    QSE_HSE_UPDATE: "PERMISSION_QSE_HSE_UPDATE",
    QSE_HSE_SOFT_DELETE: "PERMISSION_QSE_HSE_SOFT_DELETE",
    // Accident du travail 
    QSE_ACCIDENT_AT_WORK_READ: "PERMISSION_QSE_ACCIDENT_AT_WORK_READ",
    QSE_ACCIDENT_AT_WORK_CREATE: "PERMISSION_QSE_ACCIDENT_AT_WORK_CREATE",
    QSE_ACCIDENT_AT_WORK_UPDATE: "PERMISSION_QSE_ACCIDENT_AT_WORK_UPDATE",
    QSE_ACCIDENT_AT_WORK_SOFT_DELETE: "PERMISSION_QSE_ACCIDENT_AT_WORK_SOFT_DELETE",
    // Analyse AT 
    QSE_TA_ANALYSIS_READ: "PERMISSION_QSE_TA_ANALYSIS_READ",
    QSE_TA_ANALYSIS_CREATE: "PERMISSION_QSE_TA_ANALYSIS_CREATE",
    QSE_TA_ANALYSIS_UPDATE: "PERMISSION_QSE_TA_ANALYSIS_UPDATE",
    QSE_TA_ANALYSIS_SOFT_DELETE: "PERMISSION_QSE_TA_ANALYSIS_SOFT_DELETE",
    // Base qualité 
    QSE_QUALITY_BASE_READ: "PERMISSION_QSE_QUALITY_BASE_READ",
    QSE_QUALITY_BASE_CREATE: "PERMISSION_QSE_QUALITY_BASE_CREATE",
    QSE_QUALITY_BASE_UPDATE: "PERMISSION_QSE_QUALITY_BASE_UPDATE",
    QSE_QUALITY_BASE_SOFT_DELETE: "PERMISSION_QSE_QUALITY_BASE_SOFT_DELETE",

    // :::::::::::::::::::::::::::::::::::::::::: All of CRM ::::::::::::::::::::::::::::::::::::::::::
    // Dashboard
    CRM_DASHBOARD_READ: "PERMISSION_CRM_DASHBOARD_READ",
    CRM_DASHBOARD_CREATE: "PERMISSION_CRM_DASHBOARD_CREATE",
    CRM_DASHBOARD_UPDATE: "PERMISSION_CRM_DASHBOARD_UPDATE",
    CRM_DASHBOARD_SOFT_DELETE: "PERMISSION_CRM_DASHBOARD_SOFT_DELETE",
    // Clients / Prospect 
    CRM_CUSTOMERS_OR_PROSPECTS_READ: "PERMISSION_CRM_CUSTOMERS_OR_PROSPECTS_READ",
    CRM_CUSTOMERS_OR_PROSPECTS_CREATE: "PERMISSION_CRM_CUSTOMERS_OR_PROSPECTS_CREATE",
    CRM_CUSTOMERS_OR_PROSPECTS_UPDATE: "PERMISSION_CRM_CUSTOMERS_OR_PROSPECTS_UPDATE",
    CRM_CUSTOMERS_OR_PROSPECTS_SOFT_DELETE: "PERMISSION_CRM_CUSTOMERS_OR_PROSPECTS_SOFT_DELETE",
    // Affaires 
    CRM_BUSINESS_READ: "PERMISSION_CRM_BUSINESS_READ",
    CRM_BUSINESS_CREATE: "PERMISSION_CRM_BUSINESS_CREATE",
    CRM_BUSINESS_UPDATE: "PERMISSION_CRM_BUSINESS_UPDATE",
    CRM_BUSINESS_SOFT_DELETE: "PERMISSION_CRM_BUSINESS_SOFT_DELETE",
    // Tâches à faire 
    CRM_TASKS_TO_DO_READ: "PERMISSION_CRM_TASKS_TO_DO_READ",
    CRM_TASKS_TO_DO_CREATE: "PERMISSION_CRM_TASKS_TO_DO_CREATE",
    CRM_TASKS_TO_DO_UPDATE: "PERMISSION_CRM_TASKS_TO_DO_UPDATE",
    CRM_TASKS_TO_DO_SOFT_DELETE: "PERMISSION_CRM_TASKS_TO_DO_SOFT_DELETE",
    // Carnet à date 
    CRM_DATE_BOOK_READ: "PERMISSION_CRM_DATE_BOOK_READ",
    CRM_DATE_BOOK_CREATE: "PERMISSION_CRM_DATE_BOOK_CREATE",
    CRM_DATE_BOOK_UPDATE: "PERMISSION_CRM_DATE_BOOK_UPDATE",
    CRM_DATE_BOOK_SOFT_DELETE: "PERMISSION_CRM_DATE_BOOK_SOFT_DELETE",
    // Tableau de suivi 
    CRM_FOLLOW_UP_TABLE_READ: "PERMISSION_CRM_FOLLOW_UP_TABLE_READ",
    CRM_FOLLOW_UP_TABLE_CREATE: "PERMISSION_CRM_FOLLOW_UP_TABLE_CREATE",
    CRM_FOLLOW_UP_TABLE_UPDATE: "PERMISSION_CRM_FOLLOW_UP_TABLE_UPDATE",
    CRM_FOLLOW_UP_TABLE_SOFT_DELETE: "PERMISSION_CRM_FOLLOW_UP_TABLE_SOFT_DELETE",

    // :::::::::::::::::::::::::::::::::::::::::: All of Chiffrage ::::::::::::::::::::::::::::::::::::::::::
    // Dashboard
    COSTING_DASHBOARD_READ: "PERMISSION_COSTING_DASHBOARD_READ",
    COSTING_DASHBOARD_CREATE: "PERMISSION_COSTING_DASHBOARD_CREATE",
    COSTING_DASHBOARD_UPDATE: "PERMISSION_COSTING_DASHBOARD_UPDATE",
    COSTING_DASHBOARD_SOFT_DELETE: "PERMISSION_COSTING_DASHBOARD_SOFT_DELETE",
    // Liste des chiffrages 
    COSTING_LIST_OF_COSTINGS_READ: "PERMISSION_COSTING_LIST_OF_COSTINGS_READ",
    COSTING_LIST_OF_COSTINGS_CREATE: "PERMISSION_COSTING_LIST_OF_COSTINGS_CREATE",
    COSTING_LIST_OF_COSTINGS_UPDATE: "PERMISSION_COSTING_LIST_OF_COSTINGS_UPDATE",
    COSTING_LIST_OF_COSTINGS_SOFT_DELETE: "PERMISSION_COSTING_LIST_OF_COSTINGS_SOFT_DELETE",
    // Devis
    COSTING_QUOTE_READ: "PERMISSION_COSTING_QUOTE_READ",
    COSTING_QUOTE_CREATE: "PERMISSION_COSTING_QUOTE_CREATE",
    COSTING_QUOTE_UPDATE: "PERMISSION_COSTING_QUOTE_UPDATE",
    COSTING_QUOTE_SOFT_DELETE: "PERMISSION_COSTING_QUOTE_SOFT_DELETE",
    // Appels d'offre 
    COSTING_CALLS_FOR_TENDER_READ: "PERMISSION_COSTING_CALLS_FOR_TENDER_READ",
    COSTING_CALLS_FOR_TENDER_CREATE: "PERMISSION_COSTING_CALLS_FOR_TENDER_CREATE",
    COSTING_CALLS_FOR_TENDER_UPDATE: "PERMISSION_COSTING_CALLS_FOR_TENDER_UPDATE",
    COSTING_CALLS_FOR_TENDER_SOFT_DELETE: "PERMISSION_COSTING_CALLS_FOR_TENDER_SOFT_DELETE",
    // BDD matériaux 
    COSTING_BDD_MATERIALS_READ: "PERMISSION_COSTING_BDD_MATERIALS_READ",
    COSTING_BDD_MATERIALS_CREATE: "PERMISSION_COSTING_BDD_MATERIALS_CREATE",
    COSTING_BDD_MATERIALS_UPDATE: "PERMISSION_COSTING_BDD_MATERIALS_UPDATE",
    COSTING_BDD_MATERIALS_SOFT_DELETE: "PERMISSION_COSTING_BDD_MATERIALS_SOFT_DELETE",
    // BDD travaux 
    COSTING_BDD_WORKS_READ: "PERMISSION_COSTING_BDD_WORKS_READ",
    COSTING_BDD_WORKS_CREATE: "PERMISSION_COSTING_BDD_WORKS_CREATE",
    COSTING_BDD_WORKS_UPDATE: "PERMISSION_COSTING_BDD_WORKS_UPDATE",
    COSTING_BDD_WORKS_SOFT_DELETE: "PERMISSION_COSTING_BDD_WORKS_SOFT_DELETE",
    // M.O
    COSTING_MO_READ: "PERMISSION_COSTING_MO_READ",
    COSTING_MO_CREATE: "PERMISSION_COSTING_MO_CREATE",
    COSTING_MO_UPDATE: "PERMISSION_COSTING_MO_UPDATE",
    COSTING_MO_SOFT_DELETE: "PERMISSION_COSTING_MO_SOFT_DELETE",
    // Fournisseurs
    COSTING_SUPPLIERS_READ: "PERMISSION_COSTING_SUPPLIERS_READ",
    COSTING_SUPPLIERS_CREATE: "PERMISSION_COSTING_SUPPLIERS_CREATE",
    COSTING_SUPPLIERS_UPDATE: "PERMISSION_COSTING_SUPPLIERS_UPDATE",
    COSTING_SUPPLIERS_SOFT_DELETE: "PERMISSION_COSTING_SUPPLIERS_SOFT_DELETE",
    // Sous-traitants 
    COSTING_SUBCONTRACTORS_READ: "PERMISSION_COSTING_SUBCONTRACTORS_READ",
    COSTING_SUBCONTRACTORS_CREATE: "PERMISSION_COSTING_SUBCONTRACTORS_CREATE",
    COSTING_SUBCONTRACTORS_UPDATE: "PERMISSION_COSTING_SUBCONTRACTORS_UPDATE",
    COSTING_SUBCONTRACTORS_SOFT_DELETE: "PERMISSION_COSTING_SUBCONTRACTORS_SOFT_DELETE",
    // Tâches à faire 
    COSTING_TASKS_TO_DO_READ: "PERMISSION_COSTING_TASKS_TO_DO_READ",
    COSTING_TASKS_TO_DO_CREATE: "PERMISSION_COSTING_TASKS_TO_DO_CREATE",
    COSTING_TASKS_TO_DO_UPDATE: "PERMISSION_COSTING_TASKS_TO_DO_UPDATE",
    COSTING_TASKS_TO_DO_SOFT_DELETE: "PERMISSION_COSTING_TASKS_TO_DO_SOFT_DELETE",

    // :::::::::::::::::::::::::::::::::::::::::: All of Sablière ::::::::::::::::::::::::::::::::::::::::::
    // Dashboard
    SABLIERE_DASHBOARD_READ: "PERMISSION_SABLIERE_DASHBOARD_READ",
    SABLIERE_DASHBOARD_CREATE: "PERMISSION_SABLIERE_DASHBOARD_CREATE",
    SABLIERE_DASHBOARD_UPDATE: "PERMISSION_SABLIERE_DASHBOARD_UPDATE",
    SABLIERE_DASHBOARD_SOFT_DELETE: "PERMISSION_SABLIERE_DASHBOARD_SOFT_DELETE",
    // Répertoire clients 
    SABLIERE_CUSTOMER_DIRECTORY_READ: "PERMISSION_SABLIERE_CUSTOMER_DIRECTORY_READ",
    SABLIERE_CUSTOMER_DIRECTORY_CREATE: "PERMISSION_SABLIERE_CUSTOMER_DIRECTORY_CREATE",
    SABLIERE_CUSTOMER_DIRECTORY_UPDATE: "PERMISSION_SABLIERE_CUSTOMER_DIRECTORY_UPDATE",
    SABLIERE_CUSTOMER_DIRECTORY_SOFT_DELETE: "PERMISSION_SABLIERE_CUSTOMER_DIRECTORY_SOFT_DELETE",
    // Répertoire véhicules 
    SABLIERE_VEHICLE_DIRECTORY_READ: "PERMISSION_SABLIERE_VEHICLE_DIRECTORY_READ",
    SABLIERE_VEHICLE_DIRECTORY_CREATE: "PERMISSION_SABLIERE_VEHICLE_DIRECTORY_CREATE",
    SABLIERE_VEHICLE_DIRECTORY_UPDATE: "PERMISSION_SABLIERE_VEHICLE_DIRECTORY_UPDATE",
    SABLIERE_VEHICLE_DIRECTORY_SOFT_DELETE: "PERMISSION_SABLIERE_VEHICLE_DIRECTORY_SOFT_DELETE",
    // Répertoire produits 
    SABLIERE_PRODUCT_DIRECTORY_READ: "PERMISSION_SABLIERE_PRODUCT_DIRECTORY_READ",
    SABLIERE_PRODUCT_DIRECTORY_CREATE: "PERMISSION_SABLIERE_PRODUCT_DIRECTORY_CREATE",
    SABLIERE_PRODUCT_DIRECTORY_UPDATE: "PERMISSION_SABLIERE_PRODUCT_DIRECTORY_UPDATE",
    SABLIERE_PRODUCT_DIRECTORY_SOFT_DELETE: "PERMISSION_SABLIERE_PRODUCT_DIRECTORY_SOFT_DELETE",
    // Devis 
    SABLIERE_QUOTE_READ: "PERMISSION_SABLIERE_QUOTE_READ",
    SABLIERE_QUOTE_CREATE: "PERMISSION_SABLIERE_QUOTE_CREATE",
    SABLIERE_QUOTE_UPDATE: "PERMISSION_SABLIERE_QUOTE_UPDATE",
    SABLIERE_QUOTE_SOFT_DELETE: "PERMISSION_SABLIERE_QUOTE_SOFT_DELETE",
    // BL
    SABLIERE_BL_READ: "PERMISSION_SABLIERE_BL_READ",
    SABLIERE_BL_CREATE: "PERMISSION_SABLIERE_BL_CREATE",
    SABLIERE_BL_UPDATE: "PERMISSION_SABLIERE_BL_UPDATE",
    SABLIERE_BL_SOFT_DELETE: "PERMISSION_SABLIERE_BL_SOFT_DELETE",
    // Ticket de pesée 
    SABLIERE_WEIGHING_TICKET_READ: "PERMISSION_SABLIERE_WEIGHING_TICKET_READ",
    SABLIERE_WEIGHING_TICKET_CREATE: "PERMISSION_SABLIERE_WEIGHING_TICKET_CREATE",
    SABLIERE_WEIGHING_TICKET_UPDATE: "PERMISSION_SABLIERE_WEIGHING_TICKET_UPDATE",
    SABLIERE_WEIGHING_TICKET_SOFT_DELETE: "PERMISSION_SABLIERE_WEIGHING_TICKET_SOFT_DELETE",
    // Facture 
    SABLIERE_INVOICE_READ: "PERMISSION_SABLIERE_INVOICE_READ",
    SABLIERE_INVOICE_CREATE: "PERMISSION_SABLIERE_INVOICE_CREATE",
    SABLIERE_INVOICE_UPDATE: "PERMISSION_SABLIERE_INVOICE_UPDATE",
    SABLIERE_INVOICE_SOFT_DELETE: "PERMISSION_SABLIERE_INVOICE_SOFT_DELETE",
    // Comptabilisation 
    SABLIERE_ACCOUNTING_READ: "PERMISSION_SABLIERE_ACCOUNTING_READ",
    SABLIERE_ACCOUNTING_CREATE: "PERMISSION_SABLIERE_ACCOUNTING_CREATE",
    SABLIERE_ACCOUNTING_UPDATE: "PERMISSION_SABLIERE_ACCOUNTING_UPDATE",
    SABLIERE_ACCOUNTING_SOFT_DELETE: "PERMISSION_SABLIERE_ACCOUNTING_SOFT_DELETE",
    // Registre d'admission 
    SABLIERE_ADMISSION_REGISTER_READ: "PERMISSION_SABLIERE_ADMISSION_REGISTER_READ",
    SABLIERE_ADMISSION_REGISTER_CREATE: "PERMISSION_SABLIERE_ADMISSION_REGISTER_CREATE",
    SABLIERE_ADMISSION_REGISTER_UPDATE: "PERMISSION_SABLIERE_ADMISSION_REGISTER_UPDATE",
    SABLIERE_ADMISSION_REGISTER_SOFT_DELETE: "PERMISSION_SABLIERE_ADMISSION_REGISTER_SOFT_DELETE",
    // DAP
    SABLIERE_DAP_READ: "PERMISSION_SABLIERE_DAP_READ",
    SABLIERE_DAP_CREATE: "PERMISSION_SABLIERE_DAP_CREATE",
    SABLIERE_DAP_UPDATE: "PERMISSION_SABLIERE_DAP_UPDATE",
    SABLIERE_DAP_SOFT_DELETE: "PERMISSION_SABLIERE_DAP_SOFT_DELETE",
    // Planning livraisons 
    SABLIERE_DELIVERY_SCHEDULE_READ: "PERMISSION_SABLIERE_DELIVERY_SCHEDULE_READ",
    SABLIERE_DELIVERY_SCHEDULE_CREATE: "PERMISSION_SABLIERE_DELIVERY_SCHEDULE_CREATE",
    SABLIERE_DELIVERY_SCHEDULE_UPDATE: "PERMISSION_SABLIERE_DELIVERY_SCHEDULE_UPDATE",
    SABLIERE_DELIVERY_SCHEDULE_SOFT_DELETE: "PERMISSION_SABLIERE_DELIVERY_SCHEDULE_SOFT_DELETE",
    // Rapports journaliers 
    SABLIERE_DAILY_REPORTS_READ: "PERMISSION_SABLIERE_DAILY_REPORTS_READ",
    SABLIERE_DAILY_REPORTS_CREATE: "PERMISSION_SABLIERE_DAILY_REPORTS_CREATE",
    SABLIERE_DAILY_REPORTS_UPDATE: "PERMISSION_SABLIERE_DAILY_REPORTS_UPDATE",
    SABLIERE_DAILY_REPORTS_SOFT_DELETE: "PERMISSION_SABLIERE_DAILY_REPORTS_SOFT_DELETE",
    // Registre suivi écologique 
    SABLIERE_ECOLOGICAL_MONITORING_REGISTER_READ: "PERMISSION_SABLIERE_ECOLOGICAL_MONITORING_REGISTER_READ",
    SABLIERE_ECOLOGICAL_MONITORING_REGISTER_CREATE: "PERMISSION_SABLIERE_ECOLOGICAL_MONITORING_REGISTER_CREATE",
    SABLIERE_ECOLOGICAL_MONITORING_REGISTER_UPDATE: "PERMISSION_SABLIERE_ECOLOGICAL_MONITORING_REGISTER_UPDATE",
    SABLIERE_ECOLOGICAL_MONITORING_REGISTER_SOFT_DELETE: "PERMISSION_SABLIERE_ECOLOGICAL_MONITORING_REGISTER_SOFT_DELETE",
    // Registre QSE 
    SABLIERE_QSE_REGISTER_READ: "PERMISSION_SABLIERE_QSE_REGISTER_READ",
    SABLIERE_QSE_REGISTER_CREATE: "PERMISSION_SABLIERE_QSE_REGISTER_CREATE",
    SABLIERE_QSE_REGISTER_UPDATE: "PERMISSION_SABLIERE_QSE_REGISTER_UPDATE",
    SABLIERE_QSE_REGISTER_SOFT_DELETE: "PERMISSION_SABLIERE_QSE_REGISTER_SOFT_DELETE",

    // :::::::::::::::::::::::::::::::::::::::::: All of CGR ::::::::::::::::::::::::::::::::::::::::::
    // Dashboard
    CGR_DASHBOARD_READ: "PERMISSION_CGR_DASHBOARD_READ",
    CGR_DASHBOARD_CREATE: "PERMISSION_CGR_DASHBOARD_CREATE",
    CGR_DASHBOARD_UPDATE: "PERMISSION_CGR_DASHBOARD_UPDATE",
    CGR_DASHBOARD_SOFT_DELETE: "PERMISSION_CGR_DASHBOARD_SOFT_DELETE",
    // Répertoire clients 
    CGR_CUSTOMER_DIRECTORY_READ: "PERMISSION_CGR_CUSTOMER_DIRECTORY_READ",
    CGR_CUSTOMER_DIRECTORY_CREATE: "PERMISSION_CGR_CUSTOMER_DIRECTORY_CREATE",
    CGR_CUSTOMER_DIRECTORY_UPDATE: "PERMISSION_CGR_CUSTOMER_DIRECTORY_UPDATE",
    CGR_CUSTOMER_DIRECTORY_SOFT_DELETE: "PERMISSION_CGR_CUSTOMER_DIRECTORY_SOFT_DELETE",
    // Répertoire véhicules 
    CGR_VEHICLE_DIRECTORY_READ: "PERMISSION_CGR_VEHICLE_DIRECTORY_READ",
    CGR_VEHICLE_DIRECTORY_CREATE: "PERMISSION_CGR_VEHICLE_DIRECTORY_CREATE",
    CGR_VEHICLE_DIRECTORY_UPDATE: "PERMISSION_CGR_VEHICLE_DIRECTORY_UPDATE",
    CGR_VEHICLE_DIRECTORY_SOFT_DELETE: "PERMISSION_CGR_VEHICLE_DIRECTORY_SOFT_DELETE",
    // Répertoire produits 
    CGR_PRODUCT_DIRECTORY_READ: "PERMISSION_CGR_PRODUCT_DIRECTORY_READ",
    CGR_PRODUCT_DIRECTORY_CREATE: "PERMISSION_CGR_PRODUCT_DIRECTORY_CREATE",
    CGR_PRODUCT_DIRECTORY_UPDATE: "PERMISSION_CGR_PRODUCT_DIRECTORY_UPDATE",
    CGR_PRODUCT_DIRECTORY_SOFT_DELETE: "PERMISSION_CGR_PRODUCT_DIRECTORY_SOFT_DELETE",
    // Devis 
    CGR_QUOTE_READ: "PERMISSION_CGR_QUOTE_READ",
    CGR_QUOTE_CREATE: "PERMISSION_CGR_QUOTE_CREATE",
    CGR_QUOTE_UPDATE: "PERMISSION_CGR_QUOTE_UPDATE",
    CGR_QUOTE_SOFT_DELETE: "PERMISSION_CGR_QUOTE_SOFT_DELETE",
    // BL
    CGR_BL_READ: "PERMISSION_CGR_BL_READ",
    CGR_BL_CREATE: "PERMISSION_CGR_BL_CREATE",
    CGR_BL_UPDATE: "PERMISSION_CGR_BL_UPDATE",
    CGR_BL_SOFT_DELETE: "PERMISSION_CGR_BL_SOFT_DELETE",
    // Ticket de pesée 
    CGR_WEIGHING_TICKET_READ: "PERMISSION_CGR_WEIGHING_TICKET_READ",
    CGR_WEIGHING_TICKET_CREATE: "PERMISSION_CGR_WEIGHING_TICKET_CREATE",
    CGR_WEIGHING_TICKET_UPDATE: "PERMISSION_CGR_WEIGHING_TICKET_UPDATE",
    CGR_WEIGHING_TICKET_SOFT_DELETE: "PERMISSION_CGR_WEIGHING_TICKET_SOFT_DELETE",
    // Facture 
    CGR_INVOICE_READ: "PERMISSION_CGR_INVOICE_READ",
    CGR_INVOICE_CREATE: "PERMISSION_CGR_INVOICE_CREATE",
    CGR_INVOICE_UPDATE: "PERMISSION_CGR_INVOICE_UPDATE",
    CGR_INVOICE_SOFT_DELETE: "PERMISSION_CGR_INVOICE_SOFT_DELETE",
    // Comptabilisation 
    CGR_ACCOUNTING_READ: "PERMISSION_CGR_ACCOUNTING_READ",
    CGR_ACCOUNTING_CREATE: "PERMISSION_CGR_ACCOUNTING_CREATE",
    CGR_ACCOUNTING_UPDATE: "PERMISSION_CGR_ACCOUNTING_UPDATE",
    CGR_ACCOUNTING_SOFT_DELETE: "PERMISSION_CGR_ACCOUNTING_SOFT_DELETE",
    // Registre d'admission 
    CGR_ADMISSION_REGISTER_READ: "PERMISSION_CGR_ADMISSION_REGISTER_READ",
    CGR_ADMISSION_REGISTER_CREATE: "PERMISSION_CGR_ADMISSION_REGISTER_CREATE",
    CGR_ADMISSION_REGISTER_UPDATE: "PERMISSION_CGR_ADMISSION_REGISTER_UPDATE",
    CGR_ADMISSION_REGISTER_SOFT_DELETE: "PERMISSION_CGR_ADMISSION_REGISTER_SOFT_DELETE",
    // DAP
    CGR_DAP_READ: "PERMISSION_CGR_DAP_READ",
    CGR_DAP_CREATE: "PERMISSION_CGR_DAP_CREATE",
    CGR_DAP_UPDATE: "PERMISSION_CGR_DAP_UPDATE",
    CGR_DAP_SOFT_DELETE: "PERMISSION_CGR_DAP_SOFT_DELETE",
    // Planning livraisons 
    CGR_DELIVERY_SCHEDULE_READ: "PERMISSION_CGR_DELIVERY_SCHEDULE_READ",
    CGR_DELIVERY_SCHEDULE_CREATE: "PERMISSION_CGR_DELIVERY_SCHEDULE_CREATE",
    CGR_DELIVERY_SCHEDULE_UPDATE: "PERMISSION_CGR_DELIVERY_SCHEDULE_UPDATE",
    CGR_DELIVERY_SCHEDULE_SOFT_DELETE: "PERMISSION_CGR_DELIVERY_SCHEDULE_SOFT_DELETE",
    // Rapports journaliers 
    CGR_DAILY_REPORTS_READ: "PERMISSION_CGR_DAILY_REPORTS_READ",
    CGR_DAILY_REPORTS_CREATE: "PERMISSION_CGR_DAILY_REPORTS_CREATE",
    CGR_DAILY_REPORTS_UPDATE: "PERMISSION_CGR_DAILY_REPORTS_UPDATE",
    CGR_DAILY_REPORTS_SOFT_DELETE: "PERMISSION_CGR_DAILY_REPORTS_SOFT_DELETE",
    // Registre suivi écologique 
    CGR_ECOLOGICAL_MONITORING_REGISTER_READ: "PERMISSION_CGR_ECOLOGICAL_MONITORING_REGISTER_READ",
    CGR_ECOLOGICAL_MONITORING_REGISTER_CREATE: "PERMISSION_CGR_ECOLOGICAL_MONITORING_REGISTER_CREATE",
    CGR_ECOLOGICAL_MONITORING_REGISTER_UPDATE: "PERMISSION_CGR_ECOLOGICAL_MONITORING_REGISTER_UPDATE",
    CGR_ECOLOGICAL_MONITORING_REGISTER_SOFT_DELETE: "PERMISSION_CGR_ECOLOGICAL_MONITORING_REGISTER_SOFT_DELETE",
    // Registre QSE 
    CGR_QSE_REGISTER_READ: "PERMISSION_CGR_QSE_REGISTER_READ",
    CGR_QSE_REGISTER_CREATE: "PERMISSION_CGR_QSE_REGISTER_CREATE",
    CGR_QSE_REGISTER_UPDATE: "PERMISSION_CGR_QSE_REGISTER_UPDATE",
    CGR_QSE_REGISTER_SOFT_DELETE: "PERMISSION_CGR_QSE_REGISTER_SOFT_DELETE",

    // :::::::::::::::::::::::::::::::::::::::::: All of Administration ::::::::::::::::::::::::::::::::::::::::::
    // Répertoire utilisateurs 
    ADMIN_USER_DIRECTORY_READ: "PERMISSION_ADMIN_USER_DIRECTORY_READ",
    ADMIN_USER_DIRECTORY_CREATE: "PERMISSION_ADMIN_USER_DIRECTORY_CREATE",
    ADMIN_USER_DIRECTORY_UPDATE: "PERMISSION_ADMIN_USER_DIRECTORY_UPDATE",
    ADMIN_USER_DIRECTORY_SOFT_DELETE: "PERMISSION_ADMIN_USER_DIRECTORY_SOFT_DELETE",
    // Gestion des accès 
    ADMIN_ACCESS_MANAGEMENT_READ: "PERMISSION_ADMIN_ACCESS_MANAGEMENT_READ",
    ADMIN_ACCESS_MANAGEMENT_CREATE: "PERMISSION_ADMIN_ACCESS_MANAGEMENT_CREATE",
    ADMIN_ACCESS_MANAGEMENT_UPDATE: "PERMISSION_ADMIN_ACCESS_MANAGEMENT_UPDATE",
    ADMIN_ACCESS_MANAGEMENT_SOFT_DELETE: "PERMISSION_ADMIN_ACCESS_MANAGEMENT_SOFT_DELETE",
    // Log ERP
    ADMIN_LOG_READ: "PERMISSION_ADMIN_LOG_READ",
    ADMIN_LOG_CREATE: "PERMISSION_ADMIN_LOG_CREATE",
    ADMIN_LOG_UPDATE: "PERMISSION_ADMIN_LOG_UPDATE",
    ADMIN_LOG_SOFT_DELETE: "PERMISSION_ADMIN_LOG_SOFT_DELETE",
    // Formulaires 
    ADMIN_FORMS_READ: "PERMISSION_ADMIN_FORMS_READ",
    ADMIN_FORMS_CREATE: "PERMISSION_ADMIN_FORMS_CREATE",
    ADMIN_FORMS_UPDATE: "PERMISSION_ADMIN_FORMS_UPDATE",
    ADMIN_FORMS_SOFT_DELETE: "PERMISSION_ADMIN_FORMS_SOFT_DELETE",
    // Actualités 
    ADMIN_NEWS_READ: "PERMISSION_ADMIN_NEWS_READ",
    ADMIN_NEWS_CREATE: "PERMISSION_ADMIN_NEWS_CREATE",
    ADMIN_NEWS_UPDATE: "PERMISSION_ADMIN_NEWS_UPDATE",
    ADMIN_NEWS_SOFT_DELETE: "PERMISSION_ADMIN_NEWS_SOFT_DELETE",
    // Enquêtes 
    ADMIN_SURVEYS_READ: "PERMISSION_ADMIN_SURVEYS_READ",
    ADMIN_SURVEYS_CREATE: "PERMISSION_ADMIN_SURVEYS_CREATE",
    ADMIN_SURVEYS_UPDATE: "PERMISSION_ADMIN_SURVEYS_UPDATE",
    ADMIN_SURVEYS_SOFT_DELETE: "PERMISSION_ADMIN_SURVEYS_SOFT_DELETE",
    // Organigramme 
    ADMIN_ORGANIZATION_CHART_READ: "PERMISSION_ADMIN_ORGANIZATION_CHART_READ",
    ADMIN_ORGANIZATION_CHART_CREATE: "PERMISSION_ADMIN_ORGANIZATION_CHART_CREATE",
    ADMIN_ORGANIZATION_CHART_UPDATE: "PERMISSION_ADMIN_ORGANIZATION_CHART_UPDATE",
    ADMIN_ORGANIZATION_CHART_SOFT_DELETE: "PERMISSION_ADMIN_ORGANIZATION_CHART_SOFT_DELETE",
    // Informations Groupe 
    ADMIN_ROLE_INFORMATION_READ: "PERMISSION_ADMIN_ROLE_INFORMATION_READ",
    ADMIN_ROLE_INFORMATION_CREATE: "PERMISSION_ADMIN_ROLE_INFORMATION_CREATE",
    ADMIN_ROLE_INFORMATION_UPDATE: "PERMISSION_ADMIN_ROLE_INFORMATION_UPDATE",
    ADMIN_ROLE_INFORMATION_SOFT_DELETE: "PERMISSION_ADMIN_ROLE_INFORMATION_SOFT_DELETE",
    // Documents 
    ADMIN_DOCUMENTS_READ: "PERMISSION_ADMIN_DOCUMENTS_READ",
    ADMIN_DOCUMENTS_CREATE: "PERMISSION_ADMIN_DOCUMENTS_CREATE",
    ADMIN_DOCUMENTS_UPDATE: "PERMISSION_ADMIN_DOCUMENTS_UPDATE",
    ADMIN_DOCUMENTS_SOFT_DELETE: "PERMISSION_ADMIN_DOCUMENTS_SOFT_DELETE",
    // Traiteur 
    ADMIN_CATERER_READ: "PERMISSION_ADMIN_CATERER_READ",
    ADMIN_CATERER_CREATE: "PERMISSION_ADMIN_CATERER_CREATE",
    ADMIN_CATERER_UPDATE: "PERMISSION_ADMIN_CATERER_UPDATE",
    ADMIN_CATERER_SOFT_DELETE: "PERMISSION_ADMIN_CATERER_SOFT_DELETE",
    // Contrat (RH) 
    ADMIN_RH_CONTRACT_READ: "PERMISSION_ADMIN_RH_CONTRACT_READ",
    ADMIN_RH_CONTRACT_CREATE: "PERMISSION_ADMIN_RH_CONTRACT_CREATE",
    ADMIN_RH_CONTRACT_UPDATE: "PERMISSION_ADMIN_RH_CONTRACT_UPDATE",
    ADMIN_RH_CONTRACT_SOFT_DELETE: "PERMISSION_ADMIN_RH_CONTRACT_SOFT_DELETE",
    // Documents (RH)
    ADMIN_RH_DOCUMENT_READ: "PERMISSION_ADMIN_RH_DOCUMENT_READ",
    ADMIN_RH_DOCUMENT_CREATE: "PERMISSION_ADMIN_RH_DOCUMENT_CREATE",
    ADMIN_RH_DOCUMENT_UPDATE: "PERMISSION_ADMIN_RH_DOCUMENT_UPDATE",
    ADMIN_RH_DOCUMENT_SOFT_DELETE: "PERMISSION_ADMIN_RH_DOCUMENT_SOFT_DELETE",
    // Paie (RH) 
    ADMIN_RH_PAYMENT_READ: "PERMISSION_ADMIN_RH_PAYMENT_READ",
    ADMIN_RH_PAYMENT_CREATE: "PERMISSION_ADMIN_RH_PAYMENT_CREATE",
    ADMIN_RH_PAYMENT_UPDATE: "PERMISSION_ADMIN_RH_PAYMENT_UPDATE",
    ADMIN_RH_PAYMENT_SOFT_DELETE: "PERMISSION_ADMIN_RH_PAYMENT_SOFT_DELETE",
    // Matériel (RH) 
    ADMIN_RH_MATERIAL_READ: "PERMISSION_ADMIN_RH_MATERIAL_READ",
    ADMIN_RH_MATERIAL_CREATE: "PERMISSION_ADMIN_RH_MATERIAL_CREATE",
    ADMIN_RH_MATERIAL_UPDATE: "PERMISSION_ADMIN_RH_MATERIAL_UPDATE",
    ADMIN_RH_MATERIAL_SOFT_DELETE: "PERMISSION_ADMIN_RH_MATERIAL_SOFT_DELETE",
    // Enquêtes (RH) 
    ADMIN_RH_SURVEYS_READ: "PERMISSION_ADMIN_RH_SURVEYS_READ",
    ADMIN_RH_SURVEYS_CREATE: "PERMISSION_ADMIN_RH_SURVEYS_CREATE",
    ADMIN_RH_SURVEYS_UPDATE: "PERMISSION_ADMIN_RH_SURVEYS_UPDATE",
    ADMIN_RH_SURVEYS_SOFT_DELETE: "PERMISSION_ADMIN_RH_SURVEYS_SOFT_DELETE",
    // Punch out (Achat) 
    ADMIN_PURCHASE_PUNCH_OUT_READ: "PERMISSION_ADMIN_PURCHASE_PUNCH_OUT_READ",
    ADMIN_PURCHASE_PUNCH_OUT_CREATE: "PERMISSION_ADMIN_PURCHASE_PUNCH_OUT_CREATE",
    ADMIN_PURCHASE_PUNCH_OUT_UPDATE: "PERMISSION_ADMIN_PURCHASE_PUNCH_OUT_UPDATE",
    ADMIN_PURCHASE_PUNCH_OUT_SOFT_DELETE: "PERMISSION_ADMIN_PURCHASE_PUNCH_OUT_SOFT_DELETE",
    // Carte (Chantier) 
    ADMIN_JOB_SITE_CARTE_READ: "PERMISSION_ADMIN_JOB_SITE_CARTE_READ",
    ADMIN_JOB_SITE_CARTE_CREATE: "PERMISSION_ADMIN_JOB_SITE_CARTE_CREATE",
    ADMIN_JOB_SITE_CARTE_UPDATE: "PERMISSION_ADMIN_JOB_SITE_CARTE_UPDATE",
    ADMIN_JOB_SITE_CARTE_SOFT_DELETE: "PERMISSION_ADMIN_JOB_SITE_CARTE_SOFT_DELETE",
    // Rapport journalier (Sablière) 
    ADMIN_SABLIERE_DAILY_REPORT_READ: "PERMISSION_ADMIN_SABLIERE_DAILY_REPORT_READ",
    ADMIN_SABLIERE_DAILY_REPORT_CREATE: "PERMISSION_ADMIN_SABLIERE_DAILY_REPORT_CREATE",
    ADMIN_SABLIERE_DAILY_REPORT_UPDATE: "PERMISSION_ADMIN_SABLIERE_DAILY_REPORT_UPDATE",
    ADMIN_SABLIERE_DAILY_REPORT_SOFT_DELETE: "PERMISSION_ADMIN_SABLIERE_DAILY_REPORT_SOFT_DELETE",
    // Validation devis (Chiffrage) 
    ADMIN_CODING_VALIDATION_OF_QUOTATION_READ: "PERMISSION_ADMIN_CODING_VALIDATION_OF_QUOTATION_READ",
    ADMIN_CODING_VALIDATION_OF_QUOTATION_CREATE: "PERMISSION_ADMIN_CODING_VALIDATION_OF_QUOTATION_CREATE",
    ADMIN_CODING_VALIDATION_OF_QUOTATION_UPDATE: "PERMISSION_ADMIN_CODING_VALIDATION_OF_QUOTATION_UPDATE",
    ADMIN_CODING_VALIDATION_OF_QUOTATION_SOFT_DELETE: "PERMISSION_ADMIN_CODING_VALIDATION_OF_QUOTATION_SOFT_DELETE",
    // Répertoire des clients 
    ADMIN_CLIENT_DIRECTORY_READ: "PERMISSION_ADMIN_CLIENT_DIRECTORY_READ",
    ADMIN_CLIENT_DIRECTORY_CREATE: "PERMISSION_ADMIN_CLIENT_DIRECTORY_CREATE",
    ADMIN_CLIENT_DIRECTORY_UPDATE: "PERMISSION_ADMIN_CLIENT_DIRECTORY_UPDATE",
    ADMIN_CLIENT_DIRECTORY_SOFT_DELETE: "PERMISSION_ADMIN_CLIENT_DIRECTORY_SOFT_DELETE",
    // Formulaires clients 
    ADMIN_CUSTOMER_FORMS_READ: "PERMISSION_ADMIN_CUSTOMER_FORMS_READ",
    ADMIN_CUSTOMER_FORMS_CREATE: "PERMISSION_ADMIN_CUSTOMER_FORMS_CREATE",
    ADMIN_CUSTOMER_FORMS_UPDATE: "PERMISSION_ADMIN_CUSTOMER_FORMS_UPDATE",
    ADMIN_CUSTOMER_FORMS_SOFT_DELETE: "PERMISSION_ADMIN_CUSTOMER_FORMS_SOFT_DELETE",
    // Information (Espace client) 
    ADMIN_CUSTOMER_AREA_INFORMATION_READ: "PERMISSION_ADMIN_CUSTOMER_AREA_INFORMATION_READ",
    ADMIN_CUSTOMER_AREA_INFORMATION_CREATE: "PERMISSION_ADMIN_CUSTOMER_AREA_INFORMATION_CREATE",
    ADMIN_CUSTOMER_AREA_INFORMATION_UPDATE: "PERMISSION_ADMIN_CUSTOMER_AREA_INFORMATION_UPDATE",
    ADMIN_CUSTOMER_AREA_INFORMATION_SOFT_DELETE: "PERMISSION_ADMIN_CUSTOMER_AREA_INFORMATION_SOFT_DELETE",
} as const;

/**
 * Type of PERMISSIONS
 */
export type PERMISSIONS_TYPES = ValueOf<typeof PERMISSIONS_NAMES>;

/**
 * List of group name
 */
export const PERMISSIONS_LIST: PERMISSIONS_TYPES[] = enumToArray(PERMISSIONS_NAMES);