export enum EquipmentGenreEnum {
  MTL = 'MTL',
  MTT1 = 'MTT1',
  MTT2 = 'MTT2',
  TM = 'TM',
  QM = 'QM',
  CYCL = 'CYCL',
  CL = 'CL',
  VP = 'VP',
  TCP = 'TCP',
  TRR = 'TRR',
  CTTE = 'CTTE',
  CAM = 'CAM',
  SRAT = 'SRAT',
  SREM = 'SREM',
  REM = 'REM',
  SRTC = 'SRTC',
  RETC = 'RETC',
  VASP = 'VASP',
  SRSP = 'SRSP',
  RESP = 'RESP',
  TRA = 'TRA',
  REA = 'REA',
  SREA = 'SREA',
  MAGA = 'MAGA',
  MIAR = 'MIAR',
}
